
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 解析种类
/// </summary>
public sealed partial class AnalysisKind : Luban.BeanBase
{
    public AnalysisKind(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Seconds = _buf.ReadFloat();
        TechFirst = _buf.ReadInt();
        TechRepeat = _buf.ReadInt();
        Consumed = _buf.ReadInt();
        Queued = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static AnalysisKind DeserializeAnalysisKind(ByteBuf _buf)
    {
        return new fg.AnalysisKind(_buf);
    }

    /// <summary>
    /// 物品ID(=fg.TbEcoItem.id;三类敌方物品 + 残骸)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 解析一件的游戏秒(1x;残骸 = 处理一件)
    /// </summary>
    public readonly float Seconds;
    /// <summary>
    /// 首次解析给的技术数据(残骸:每件)
    /// </summary>
    public readonly int TechFirst;
    /// <summary>
    /// 重复解析 / 身份不明时给的技术数据
    /// </summary>
    public readonly int TechRepeat;
    /// <summary>
    /// 解析后物品是否消耗:1=消耗,0=不消耗(加密固件变成已破解的固件芯片)
    /// </summary>
    public readonly int Consumed;
    /// <summary>
    /// 1=走解析队列(FGR-RND-020);0=队列空闲时处理(残骸,FGR-RND-024)
    /// </summary>
    public readonly int Queued;
    /// <summary>
    /// 面板排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 717621437;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "seconds:" + Seconds + ","
        + "techFirst:" + TechFirst + ","
        + "techRepeat:" + TechRepeat + ","
        + "consumed:" + Consumed + ","
        + "queued:" + Queued + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

