
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 背景资料
/// </summary>
public sealed partial class AnalysisLore : Luban.BeanBase
{
    public AnalysisLore(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        TitleKey = _buf.ReadString();
        BodyKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static AnalysisLore DeserializeAnalysisLore(ByteBuf _buf)
    {
        return new fg.AnalysisLore(_buf);
    }

    /// <summary>
    /// 资料ID(数据核心的身份;存档 LoreRead 引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 标题文本键
    /// </summary>
    public readonly string TitleKey;
    /// <summary>
    /// 正文文本键
    /// </summary>
    public readonly string BodyKey;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 717657119;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "titleKey:" + TitleKey + ","
        + "bodyKey:" + BodyKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

