
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 过滤器预设
/// </summary>
public sealed partial class BeltFilterPreset : Luban.BeanBase
{
    public BeltFilterPreset(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        RatioL = _buf.ReadInt();
        RatioR = _buf.ReadInt();
        Priority = _buf.ReadString();
        FilterL = _buf.ReadString();
        FilterR = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static BeltFilterPreset DeserializeBeltFilterPreset(ByteBuf _buf)
    {
        return new fg.BeltFilterPreset(_buf);
    }

    /// <summary>
    /// 预设ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(悬停)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 左口份数 1~9
    /// </summary>
    public readonly int RatioL;
    /// <summary>
    /// 右口份数 1~9
    /// </summary>
    public readonly int RatioR;
    /// <summary>
    /// 优先输出口:none/left/right
    /// </summary>
    public readonly string Priority;
    /// <summary>
    /// 左口过滤:any/none/scrap
    /// </summary>
    public readonly string FilterL;
    /// <summary>
    /// 右口过滤:any/none/scrap
    /// </summary>
    public readonly string FilterR;
    /// <summary>
    /// 下拉框排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 49047247;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "ratioL:" + RatioL + ","
        + "ratioR:" + RatioR + ","
        + "priority:" + Priority + ","
        + "filterL:" + FilterL + ","
        + "filterR:" + FilterR + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

