
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑等级
/// </summary>
public sealed partial class BuildingTier : Luban.BeanBase
{
    public BuildingTier(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        TypeId = _buf.ReadString();
        Tier = _buf.ReadInt();
        DiffScrap = _buf.ReadInt();
        Seconds = _buf.ReadFloat();
        UnlockRule = _buf.ReadString();
        UnlockHintKey = _buf.ReadString();
        Value = _buf.ReadFloat();
        ValueKey = _buf.ReadString();
    }

    public static BuildingTier DeserializeBuildingTier(ByteBuf _buf)
    {
        return new fg.BuildingTier(_buf);
    }

    /// <summary>
    /// 行ID(typeId.tN)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 建筑类型ID
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 等级(1 起,连续)
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 从上一级升到这一级的废料差额(T1=0)
    /// </summary>
    public readonly int DiffScrap;
    /// <summary>
    /// 升到这一级的施工工期(秒,T1=0)
    /// </summary>
    public readonly float Seconds;
    /// <summary>
    /// 解锁规则(同 fg.TbBuildingGrid.unlockRule;研发门槛在 FG5-RND-01)
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 未解锁时的说明文本键
    /// </summary>
    public readonly string UnlockHintKey;
    /// <summary>
    /// 这一级的效果值(仓库=容量;信号塔=覆盖半径)
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 效果的说明文本键,{0}=效果值
    /// </summary>
    public readonly string ValueKey;
   
    public const int __ID__ = 1483756259;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "typeId:" + TypeId + ","
        + "tier:" + Tier + ","
        + "diffScrap:" + DiffScrap + ","
        + "seconds:" + Seconds + ","
        + "unlockRule:" + UnlockRule + ","
        + "unlockHintKey:" + UnlockHintKey + ","
        + "value:" + Value + ","
        + "valueKey:" + ValueKey + ","
        + "}";
    }
}
}

