
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑格网属性
/// </summary>
public sealed partial class BuildingGrid : Luban.BeanBase
{
    public BuildingGrid(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        FootprintW = _buf.ReadInt();
        FootprintH = _buf.ReadInt();
        Placeable = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
        UnlockRule = _buf.ReadString();
        Critical = _buf.ReadInt();
        RequiredTerrain = _buf.ReadString();
        DescKey = _buf.ReadString();
        UnlockHintKey = _buf.ReadString();
    }

    public static BuildingGrid DeserializeBuildingGrid(ByteBuf _buf)
    {
        return new fg.BuildingGrid(_buf);
    }

    /// <summary>
    /// 建筑类型ID(=fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 占地宽(旋转0时x向格数),&gt;=1
    /// </summary>
    public readonly int FootprintW;
    /// <summary>
    /// 占地高(旋转0时y向格数),&gt;=1
    /// </summary>
    public readonly int FootprintH;
    /// <summary>
    /// 1=玩家可放置,0=仅开局预置
    /// </summary>
    public readonly int Placeable;
    /// <summary>
    /// 可放置数量上限,0=不限
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 解锁规则:always/beacon
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 1=关键建筑,拆除需确认
    /// </summary>
    public readonly int Critical;
    /// <summary>
    /// any 或 fg.TbGridTerrain 的地形ID(至少一格压在其上)
    /// </summary>
    public readonly string RequiredTerrain;
    /// <summary>
    /// 说明文本键(fg.TbLocText)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 未解锁时的解锁条件文本键(fg.TbLocText)
    /// </summary>
    public readonly string UnlockHintKey;
   
    public const int __ID__ = 1483377735;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "footprintW:" + FootprintW + ","
        + "footprintH:" + FootprintH + ","
        + "placeable:" + Placeable + ","
        + "maxCount:" + MaxCount + ","
        + "unlockRule:" + UnlockRule + ","
        + "critical:" + Critical + ","
        + "requiredTerrain:" + RequiredTerrain + ","
        + "descKey:" + DescKey + ","
        + "unlockHintKey:" + UnlockHintKey + ","
        + "}";
    }
}
}

