
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 多座建筑叠加
/// </summary>
public sealed partial class BuildingStack : Luban.BeanBase
{
    public BuildingStack(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        TypeId = _buf.ReadString();
        Nth = _buf.ReadInt();
        Bonus = _buf.ReadFloat();
    }

    public static BuildingStack DeserializeBuildingStack(ByteBuf _buf)
    {
        return new fg.BuildingStack(_buf);
    }

    /// <summary>
    /// 行ID(typeId.第几座)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 建筑类型(fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 第几座工作中的这类建筑(按建筑 ID 排序;1 起)
    /// </summary>
    public readonly int Nth;
    /// <summary>
    /// 这一座贡献的速度(1.0 = 一座的速度;表里没有的第 n 座贡献 0)
    /// </summary>
    public readonly float Bonus;
   
    public const int __ID__ = -1248796249;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "typeId:" + TypeId + ","
        + "nth:" + Nth + ","
        + "bonus:" + Bonus + ","
        + "}";
    }
}
}

