
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑通用
/// </summary>
public sealed partial class BuildingService : Luban.BeanBase
{
    public BuildingService(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        MaxDurability = _buf.ReadFloat();
        RepairKits = _buf.ReadInt();
        RepairSeconds = _buf.ReadFloat();
        CodexId = _buf.ReadString();
        CanDisable = _buf.ReadInt();
        RebuildScrap = _buf.ReadInt();
        RebuildSeconds = _buf.ReadFloat();
    }

    public static BuildingService DeserializeBuildingService(ByteBuf _buf)
    {
        return new fg.BuildingService(_buf);
    }

    /// <summary>
    /// 建筑类型ID(=fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 最大耐久(受损不影响效率;归零=摧毁,留下虚影)
    /// </summary>
    public readonly float MaxDurability;
    /// <summary>
    /// 从 0 修满要几件维修件(按缺的比例收,至少 1 件);0=不能用维修件修
    /// </summary>
    public readonly int RepairKits;
    /// <summary>
    /// 从 0 修满的工期(秒,按比例,至少 building.repair.min_seconds)
    /// </summary>
    public readonly float RepairSeconds;
    /// <summary>
    /// 面板“?”打开的图鉴条目(fg.TbCodexEntry.id)
    /// </summary>
    public readonly string CodexId;
    /// <summary>
    /// 1=玩家可以启用/禁用(归还核心 0)
    /// </summary>
    public readonly int CanDisable;
    /// <summary>
    /// 被摧毁后原地重建的废料(0=按 fg.TbBuilding 的修复造价,没有再按新建造价);开局预置、不能新建的建筑必须填
    /// </summary>
    public readonly int RebuildScrap;
    /// <summary>
    /// 原地重建工期(秒;rebuildScrap&gt;0 时要 &gt;0)
    /// </summary>
    public readonly float RebuildSeconds;
   
    public const int __ID__ = 2084477460;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "maxDurability:" + MaxDurability + ","
        + "repairKits:" + RepairKits + ","
        + "repairSeconds:" + RepairSeconds + ","
        + "codexId:" + CodexId + ","
        + "canDisable:" + CanDisable + ","
        + "rebuildScrap:" + RebuildScrap + ","
        + "rebuildSeconds:" + RebuildSeconds + ","
        + "}";
    }
}
}

