
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑流体端口
/// </summary>
public sealed partial class BuildingFluidPort : Luban.BeanBase
{
    public BuildingFluidPort(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        TypeId = _buf.ReadString();
        LocalX = _buf.ReadInt();
        LocalY = _buf.ReadInt();
        Dir = _buf.ReadString();
        Kind = _buf.ReadString();
        Fluid = _buf.ReadString();
    }

    public static BuildingFluidPort DeserializeBuildingFluidPort(ByteBuf _buf)
    {
        return new fg.BuildingFluidPort(_buf);
    }

    /// <summary>
    /// 端口ID(&lt;建筑&gt;.&lt;序号&gt;)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 建筑类型ID(=fg.TbBuildingGrid.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 局部格x(相对枢轴格,旋转0)
    /// </summary>
    public readonly int LocalX;
    /// <summary>
    /// 局部格y(相对枢轴格,旋转0,+y=北)
    /// </summary>
    public readonly int LocalY;
    /// <summary>
    /// 朝外方向:N/E/S/W(旋转0)
    /// </summary>
    public readonly string Dir;
    /// <summary>
    /// in=流体输入,out=流体输出
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 物品表里的流体ID;any=收任何流体(只用于输入);source=脚下流体源的流体(只用于流体泵输出)
    /// </summary>
    public readonly string Fluid;
   
    public const int __ID__ = 1055115530;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "typeId:" + TypeId + ","
        + "localX:" + LocalX + ","
        + "localY:" + LocalY + ","
        + "dir:" + Dir + ","
        + "kind:" + Kind + ","
        + "fluid:" + Fluid + ","
        + "}";
    }
}
}

