
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑
/// </summary>
public sealed partial class Building : Luban.BeanBase
{
    public Building(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        NameKey = _buf.ReadString();
        PowerDemand = _buf.ReadFloat();
        PowerPriority = _buf.ReadInt();
        PowerSupply = _buf.ReadFloat();
        RepairScrap = _buf.ReadInt();
        RepairSeconds = _buf.ReadFloat();
        BuildScrap = _buf.ReadInt();
        BuildSeconds = _buf.ReadFloat();
    }

    public static Building DeserializeBuilding(ByteBuf _buf)
    {
        return new fg.Building(_buf);
    }

    /// <summary>
    /// 建筑类型ID(BuildingRecord.BuildingTypeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// Operational时电力需求,0=不用电
    /// </summary>
    public readonly float PowerDemand;
    /// <summary>
    /// 默认电力优先级1~4,不用电填0
    /// </summary>
    public readonly int PowerPriority;
    /// <summary>
    /// Operational时电力供给,0=不供电
    /// </summary>
    public readonly float PowerSupply;
    /// <summary>
    /// 修复废料,不需修复填0
    /// </summary>
    public readonly int RepairScrap;
    /// <summary>
    /// 修复秒数,0=不需修复
    /// </summary>
    public readonly float RepairSeconds;
    /// <summary>
    /// 新建废料,不可新建填0
    /// </summary>
    public readonly int BuildScrap;
    /// <summary>
    /// 新建秒数,0=不可新建
    /// </summary>
    public readonly float BuildSeconds;
   
    public const int __ID__ = -276028063;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "nameKey:" + NameKey + ","
        + "powerDemand:" + PowerDemand + ","
        + "powerPriority:" + PowerPriority + ","
        + "powerSupply:" + PowerSupply + ","
        + "repairScrap:" + RepairScrap + ","
        + "repairSeconds:" + RepairSeconds + ","
        + "buildScrap:" + BuildScrap + ","
        + "buildSeconds:" + BuildSeconds + ","
        + "}";
    }
}
}

