
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建造菜单工具
/// </summary>
public sealed partial class BuildTool : Luban.BeanBase
{
    public BuildTool(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        Tier = _buf.ReadInt();
        Category = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        ScrapPerCell = _buf.ReadInt();
        UnlockRule = _buf.ReadString();
        UnlockHintKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static BuildTool DeserializeBuildTool(ByteBuf _buf)
    {
        return new fg.BuildTool(_buf);
    }

    /// <summary>
    /// 工具ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// belt=传送带(按住拖拽铺设);splitter=分流器;merger=合流器(单击放置);underground=地下传送带(从入口拖到出口)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 传送带等级:0=T1,1=T2,2=T3(分流器/合流器=内部速度档)
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 建造菜单分类(fg.TbBuildCategory.id)
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明 / 用途文本键(搜索也按它)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 每格废料,&gt;=1
    /// </summary>
    public readonly int ScrapPerCell;
    /// <summary>
    /// 解锁规则:always/beacon(同 fg.TbBuildingGrid)
    /// </summary>
    public readonly string UnlockRule;
    /// <summary>
    /// 未解锁时的解锁条件文本键
    /// </summary>
    public readonly string UnlockHintKey;
    /// <summary>
    /// 同分类内的排序(建筑按表顺序排在工具之后)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 32440345;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "tier:" + Tier + ","
        + "category:" + Category + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "scrapPerCell:" + ScrapPerCell + ","
        + "unlockRule:" + UnlockRule + ","
        + "unlockHintKey:" + UnlockHintKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

