
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 载体读法
/// </summary>
public sealed partial class CarrierReading : Luban.BeanBase
{
    public CarrierReading(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Field = _buf.ReadString();
        Carrier = _buf.ReadString();
        Verb = _buf.ReadString();
        A = _buf.ReadFloat();
        B = _buf.ReadFloat();
        C = _buf.ReadFloat();
        Mag = _buf.ReadString();
        Place = _buf.ReadString();
        TextKey = _buf.ReadString();
    }

    public static CarrierReading DeserializeCarrierReading(ByteBuf _buf)
    {
        return new fg.CarrierReading(_buf);
    }

    /// <summary>
    /// 行ID:&lt;字段&gt;.&lt;载体&gt;.&lt;序号&gt;
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 读法字段(fg.TbFirmwareKind readFields 里的字段名)
    /// </summary>
    public readonly string Field;
    /// <summary>
    /// 载体:projectile=射弹,melee=格斗,summon=无人机,aura=力场,field=布区
    /// </summary>
    public readonly string Carrier;
    /// <summary>
    /// 内核动作(C# CarrierReadingVerb):dmg/cooldown/extra/pierce/chain/blast/sweep/echo/pull/knock/lunge/armor/execute/leech/amp/zone/zonegrow/zonetick/weave/escort/drones/heatburst/jump/reach/cone
    /// </summary>
    public readonly string Verb;
    /// <summary>
    /// 参数 a(含义随动作,见 CarrierReadings.Accumulate)
    /// </summary>
    public readonly float A;
    /// <summary>
    /// 参数 b
    /// </summary>
    public readonly float B;
    /// <summary>
    /// 参数 c
    /// </summary>
    public readonly float C;
    /// <summary>
    /// 固件幅度乘到哪个参数:none/a/b/c
    /// </summary>
    public readonly string Mag;
    /// <summary>
    /// 区域放在哪(只对 zone):hit=命中点,mid=攻击者与命中点的中点,self=攻击者脚下,none
    /// </summary>
    public readonly string Place;
    /// <summary>
    /// 读法短语文本键(同一 字段+载体 只有第一行有;其余 none);{a}{b}{c} 为乘过幅度的参数,{ap}{bp}{cp} 为百分数
    /// </summary>
    public readonly string TextKey;
   
    public const int __ID__ = -646718111;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "field:" + Field + ","
        + "carrier:" + Carrier + ","
        + "verb:" + Verb + ","
        + "a:" + A + ","
        + "b:" + B + ","
        + "c:" + C + ","
        + "mag:" + Mag + ","
        + "place:" + Place + ","
        + "textKey:" + TextKey + ","
        + "}";
    }
}
}

