
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机制图鉴条目
/// </summary>
public sealed partial class CodexEntry : Luban.BeanBase
{
    public CodexEntry(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Tab = _buf.ReadString();
        TitleKey = _buf.ReadString();
        BodyKey = _buf.ReadString();
        HintKey = _buf.ReadString();
        Links = _buf.ReadString();
        Hooks = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static CodexEntry DeserializeCodexEntry(ByteBuf _buf)
    {
        return new fg.CodexEntry(_buf);
    }

    /// <summary>
    /// 条目ID(小写点分段,MechanicCodex 与“?”按钮引用)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 页签:system=系统说明(FG13 FGR-UX-050);其余页签由 FG2-FW-05 扩
    /// </summary>
    public readonly string Tab;
    /// <summary>
    /// 标题文本键
    /// </summary>
    public readonly string TitleKey;
    /// <summary>
    /// 正文文本键
    /// </summary>
    public readonly string BodyKey;
    /// <summary>
    /// 未解锁时的获取提示文本键(FGR-UX-051:剪影 + 获取途径)
    /// </summary>
    public readonly string HintKey;
    /// <summary>
    /// 相关条目ID,逗号分隔(互相链接)
    /// </summary>
    public readonly string Links;
    /// <summary>
    /// 解锁它的引导钩子ID(GuidanceHooks 常量值),逗号分隔;至少 1 个
    /// </summary>
    public readonly string Hooks;
    /// <summary>
    /// 列表排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 1580959348;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tab:" + Tab + ","
        + "titleKey:" + TitleKey + ","
        + "bodyKey:" + BodyKey + ","
        + "hintKey:" + HintKey + ","
        + "links:" + Links + ","
        + "hooks:" + Hooks + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

