
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 作战组件
/// </summary>
public sealed partial class CombatComponent : Luban.BeanBase
{
    public CombatComponent(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Slot = _buf.ReadString();
        Carrier = _buf.ReadString();
        SubtypeKey = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        LegacyOrgan = _buf.ReadString();
        Damage = _buf.ReadFloat();
        Turret = _buf.ReadString();
        TurretReasonKey = _buf.ReadString();
        TurretReadingKey = _buf.ReadString();
        Approach = _buf.ReadFloat();
        Cone = _buf.ReadFloat();
        Area = _buf.ReadFloat();
        FieldSeconds = _buf.ReadFloat();
        FieldDpsRatio = _buf.ReadFloat();
        Drones = _buf.ReadInt();
        DroneSeconds = _buf.ReadFloat();
        DroneRatio = _buf.ReadFloat();
        DroneCooldown = _buf.ReadFloat();
        DroneLeash = _buf.ReadFloat();
        Knockback = _buf.ReadFloat();
        TurretKnockback = _buf.ReadFloat();
        Scrap = _buf.ReadInt();
        Load = _buf.ReadInt();
        Source = _buf.ReadString();
        Icon = _buf.ReadString();
        FieldPlace = _buf.ReadString();
        DroneMode = _buf.ReadString();
        EchoCount = _buf.ReadInt();
        EchoDelay = _buf.ReadFloat();
        EchoRatio = _buf.ReadFloat();
        Thorns = _buf.ReadFloat();
        ThornsReach = _buf.ReadFloat();
    }

    public static CombatComponent DeserializeCombatComponent(ByteBuf _buf)
    {
        return new fg.CombatComponent(_buf);
    }

    /// <summary>
    /// 组件ID(ComponentCatalog)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 槽位:main=主组件,function=功能组件
    /// </summary>
    public readonly string Slot;
    /// <summary>
    /// 载体(决定固件读法):projectile/melee/summon/aura/field;功能组件填 none(武器载体由主组件决定)
    /// </summary>
    public readonly string Carrier;
    /// <summary>
    /// 载体细分文本键(射弹&#183;光束 / 格斗&#183;扇形……)
    /// </summary>
    public readonly string SubtypeKey;
    /// <summary>
    /// 名称文本键;Demo 组件填 none(名称仍在 ComponentCatalog)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键;Demo 组件填 none
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 旧器官(电路 8 号汇槽编译用);Demo 组件填 none(沿用 ComponentCatalog)
    /// </summary>
    public readonly string LegacyOrgan;
    /// <summary>
    /// 基础伤害:&gt;0 时用本值(新组件);0 = 沿用 Demo 规则(连射器 / 切割束按电路编译伤害,重炮 55);反伤功能组件 = 反伤固定值
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 固定底盘(炮塔)兼容:ok=直接兼容,adjusted=兼容但读法调整,no=不兼容(FGR-FW-012)
    /// </summary>
    public readonly string Turret;
    /// <summary>
    /// 不兼容的原因文本键(带一个参数:组件名);其余 none
    /// </summary>
    public readonly string TurretReasonKey;
    /// <summary>
    /// 装在炮塔上的读法说明文本键(adjusted 必填);其余 none
    /// </summary>
    public readonly string TurretReadingKey;
    /// <summary>
    /// 接近距离(米):&gt;0 时编队攻击贴到这么近才出手(格斗 / 力场)
    /// </summary>
    public readonly float Approach;
    /// <summary>
    /// 格斗扇形半角(度)
    /// </summary>
    public readonly float Cone;
    /// <summary>
    /// 格斗触及 / 力场半径 / 布区半径(米)
    /// </summary>
    public readonly float Area;
    /// <summary>
    /// 布区持续秒数
    /// </summary>
    public readonly float FieldSeconds;
    /// <summary>
    /// 布区每秒伤害 = 基础伤害 &#215; 本值
    /// </summary>
    public readonly float FieldDpsRatio;
    /// <summary>
    /// 无人机舱同时挂几架
    /// </summary>
    public readonly int Drones;
    /// <summary>
    /// 每架无人机存活秒数(母机开火时刷新)
    /// </summary>
    public readonly float DroneSeconds;
    /// <summary>
    /// 每架无人机每次命中 = 基础伤害 &#215; 本值
    /// </summary>
    public readonly float DroneRatio;
    /// <summary>
    /// 无人机出手间隔(游戏秒)
    /// </summary>
    public readonly float DroneCooldown;
    /// <summary>
    /// 无人机离母机最远(米)
    /// </summary>
    public readonly float DroneLeash;
    /// <summary>
    /// 组件自带击退(米,推铲)
    /// </summary>
    public readonly float Knockback;
    /// <summary>
    /// 装在炮塔上的击退(米;adjusted 用,例:推铲 → 击退铲)
    /// </summary>
    public readonly float TurretKnockback;
    /// <summary>
    /// 装配废料(新组件;Demo 组件填 0,沿用 ComponentCatalog)
    /// </summary>
    public readonly int Scrap;
    /// <summary>
    /// 负载(新组件;Demo 组件填 0)
    /// </summary>
    public readonly int Load;
    /// <summary>
    /// 获取途径:base=基础蓝图库;Demo 组件填 none(沿用 ComponentCatalog)
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 图标ID
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 布区落点:hit=目标脚下,self=自己脚下(布区&#183;脉冲,要贴近才出手)
    /// </summary>
    public readonly string FieldPlace;
    /// <summary>
    /// 无人机方式:follow=伴飞母机,post=定点(哨戒桩:插在身前不动,射程=droneLeash)
    /// </summary>
    public readonly string DroneMode;
    /// <summary>
    /// 组件自带回波次数(拆解钳:夹住后持续拆解)
    /// </summary>
    public readonly int EchoCount;
    /// <summary>
    /// 组件自带回波间隔(游戏秒)
    /// </summary>
    public readonly float EchoDelay;
    /// <summary>
    /// 组件自带回波每次伤害 = 基础伤害 &#215; 本值
    /// </summary>
    public readonly float EchoRatio;
    /// <summary>
    /// 反伤比例(功能组件尖刺外装:被近身即时攻击时,攻击者吃 damage 列的固定值 + 这一击伤害 &#215; 本值)
    /// </summary>
    public readonly float Thorns;
    /// <summary>
    /// 反伤触及(米,另加双方半径):攻击者在这个距离内才算近战
    /// </summary>
    public readonly float ThornsReach;
   
    public const int __ID__ = -2113875684;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "slot:" + Slot + ","
        + "carrier:" + Carrier + ","
        + "subtypeKey:" + SubtypeKey + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "legacyOrgan:" + LegacyOrgan + ","
        + "damage:" + Damage + ","
        + "turret:" + Turret + ","
        + "turretReasonKey:" + TurretReasonKey + ","
        + "turretReadingKey:" + TurretReadingKey + ","
        + "approach:" + Approach + ","
        + "cone:" + Cone + ","
        + "area:" + Area + ","
        + "fieldSeconds:" + FieldSeconds + ","
        + "fieldDpsRatio:" + FieldDpsRatio + ","
        + "drones:" + Drones + ","
        + "droneSeconds:" + DroneSeconds + ","
        + "droneRatio:" + DroneRatio + ","
        + "droneCooldown:" + DroneCooldown + ","
        + "droneLeash:" + DroneLeash + ","
        + "knockback:" + Knockback + ","
        + "turretKnockback:" + TurretKnockback + ","
        + "scrap:" + Scrap + ","
        + "load:" + Load + ","
        + "source:" + Source + ","
        + "icon:" + Icon + ","
        + "fieldPlace:" + FieldPlace + ","
        + "droneMode:" + DroneMode + ","
        + "echoCount:" + EchoCount + ","
        + "echoDelay:" + EchoDelay + ","
        + "echoRatio:" + EchoRatio + ","
        + "thorns:" + Thorns + ","
        + "thornsReach:" + ThornsReach + ","
        + "}";
    }
}
}

