
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 物品
/// </summary>
public sealed partial class EcoItem : Luban.BeanBase
{
    public EcoItem(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        BeltId = _buf.ReadInt();
        Form = _buf.ReadString();
        Tier = _buf.ReadString();
        FluidId = _buf.ReadInt();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        SourceKey = _buf.ReadString();
        UseKey = _buf.ReadString();
        Color = _buf.ReadString();
        Shape = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static EcoItem DeserializeEcoItem(ByteBuf _buf)
    {
        return new fg.EcoItem(_buf);
    }

    /// <summary>
    /// 物品ID(小写英文;存档与配方引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 传送带物品编号1~999;0=不上传送带(流体/保管库/数字资源/实体)
    /// </summary>
    public readonly int BeltId;
    /// <summary>
    /// 形态:solid固体/fluid流体/vault核心保管库/digital数字资源/entity产出后成为实体
    /// </summary>
    public readonly string Form;
    /// <summary>
    /// 层级:raw原料/intermediate中间品/product成品/endgame终局/expedition远征物/key关键材料/fluid流体/digital数字资源
    /// </summary>
    public readonly string Tier;
    /// <summary>
    /// 流体编号(fg.TbFluid.id);0=不是流体
    /// </summary>
    public readonly int FluidId;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(图鉴正文第一段)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 来源文本键(配方之外的来源:采集/远征/任务……;图鉴“从哪来”)
    /// </summary>
    public readonly string SourceKey;
    /// <summary>
    /// 用途文本键(配方之外的用途;图鉴“拿去干什么”)
    /// </summary>
    public readonly string UseKey;
    /// <summary>
    /// 占位图标颜色 #RRGGBB(传送带上的物品方块同色)
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// 占位图标形状:square/circle/diamond/pill/ring/bar/drop
    /// </summary>
    public readonly string Shape;
    /// <summary>
    /// 排序(物资面板与图鉴)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -1736529417;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "beltId:" + BeltId + ","
        + "form:" + Form + ","
        + "tier:" + Tier + ","
        + "fluidId:" + FluidId + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "sourceKey:" + SourceKey + ","
        + "useKey:" + UseKey + ","
        + "color:" + Color + ","
        + "shape:" + Shape + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

