
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 固件种类
/// </summary>
public sealed partial class FirmwareKind : Luban.BeanBase
{
    public FirmwareKind(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        NameKey = _buf.ReadString();
        Cooldown = _buf.ReadFloat();
        Protocol = _buf.ReadString();
        Faction = _buf.ReadString();
    }

    public static FirmwareKind DeserializeFirmwareKind(ByteBuf _buf)
    {
        return new fg.FirmwareKind(_buf);
    }

    /// <summary>
    /// 固件ID(FirmwareCatalog / PrimitiveChipRecord.CardDefId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 种类:regular=常规(可装机器也可放信号核),core=核心(只能由信号携带,FGR-SIG-012)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 核心固件发动后的冷却秒数(FGR-SIG-033:冷却属于信号,跳到别的机器不重置;按游戏时间计,暂停不走);只在 kind=core 时生效,常规固件填 0
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 协议:own=己方/中立(无需破解),enemy=敌方加密(解析台破解前只能放进信号核裸跑,不能装进机器电路或炮塔)
    /// </summary>
    public readonly string Protocol;
    /// <summary>
    /// 来源阵营:reclaim=归还,silent=静默,foundry=铸造;暴露面板“各阵营贡献”与异派技术判定读这里,名称走文本键 faction.&lt;值&gt;
    /// </summary>
    public readonly string Faction;
   
    public const int __ID__ = -1131444196;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "nameKey:" + NameKey + ","
        + "cooldown:" + Cooldown + ","
        + "protocol:" + Protocol + ","
        + "faction:" + Faction + ","
        + "}";
    }
}
}

