
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 固件种类
/// </summary>
public sealed partial class FirmwareKind : Luban.BeanBase
{
    public FirmwareKind(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        NameKey = _buf.ReadString();
    }

    public static FirmwareKind DeserializeFirmwareKind(ByteBuf _buf)
    {
        return new fg.FirmwareKind(_buf);
    }

    /// <summary>
    /// 固件ID(FirmwareCatalog / PrimitiveChipRecord.CardDefId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 种类:regular=常规(可装机器也可放信号核),core=核心(只能由信号携带,FGR-SIG-012)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
   
    public const int __ID__ = -1131444196;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "nameKey:" + NameKey + ","
        + "}";
    }
}
}

