
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 流体
/// </summary>
public sealed partial class Fluid : Luban.BeanBase
{
    public Fluid(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        NameKey = _buf.ReadString();
        Color = _buf.ReadString();
        Glyph = _buf.ReadString();
        SourceTerrain = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static Fluid DeserializeFluid(ByteBuf _buf)
    {
        return new fg.Fluid(_buf);
    }

    /// <summary>
    /// 流体编号(1~200,内核与存档里存它)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 流体键(小写英文)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 管线颜色 #RRGGBB
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// 管线图标形状:drop/dot/cross/triangle/diamond
    /// </summary>
    public readonly string Glyph;
    /// <summary>
    /// 泵抽取这种流体的地形(fg.TbGridTerrain.id);none=无天然来源
    /// </summary>
    public readonly string SourceTerrain;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -18485699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "nameKey:" + NameKey + ","
        + "color:" + Color + ","
        + "glyph:" + Glyph + ","
        + "sourceTerrain:" + SourceTerrain + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

