
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 流体泄漏
/// </summary>
public sealed partial class FluidLeak : Luban.BeanBase
{
    public FluidLeak(ByteBuf _buf) 
    {
        Fluid = _buf.ReadInt();
        Tag = _buf.ReadString();
        RadiusScale = _buf.ReadFloat();
        SortOrder = _buf.ReadInt();
    }

    public static FluidLeak DeserializeFluidLeak(ByteBuf _buf)
    {
        return new fg.FluidLeak(_buf);
    }

    /// <summary>
    /// 流体编号(fg.TbFluid.id)
    /// </summary>
    public readonly int Fluid;
    /// <summary>
    /// 液洼挂的状态标签(fg.TbStatusTag 主标签 ID;站进液洼的单位按节拍挂上,液洼本身按 fg.TbReaction 的残留规则整片反应)
    /// </summary>
    public readonly string Tag;
    /// <summary>
    /// 液洼半径倍率(&#215; logistics.leak.base_radius / max_radius)
    /// </summary>
    public readonly float RadiusScale;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 566139712;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "fluid:" + Fluid + ","
        + "tag:" + Tag + ","
        + "radiusScale:" + RadiusScale + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

