
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 熔合配方
/// </summary>
public sealed partial class FusionRecipe : Luban.BeanBase
{
    public FusionRecipe(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        MixId = _buf.ReadString();
        ParentA = _buf.ReadString();
        ParentB = _buf.ReadString();
        Family = _buf.ReadString();
        Reaction = _buf.ReadString();
        NameKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static FusionRecipe DeserializeFusionRecipe(ByteBuf _buf)
    {
        return new fg.FusionRecipe(_buf);
    }

    /// <summary>
    /// 配方ID(存档的配方书 / 线索 / 模拟记录引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 产出的混合固件ID(fg.TbFirmwareKind 里 mixA / mixB 不为 none 的行)
    /// </summary>
    public readonly string MixId;
    /// <summary>
    /// 父固件A(两条父固件不分先后;都必须是已破解后能装的常规 / 核心固件,不能是混合固件)
    /// </summary>
    public readonly string ParentA;
    /// <summary>
    /// 父固件B
    /// </summary>
    public readonly string ParentB;
    /// <summary>
    /// 配方书类别:fuse=引信与弹芯,limiter=限制器与击发逻辑,fluid=流体改道,em=电磁场控(= 混合固件的主类别;“流体类熔合还有 N 个未发现”按它数)
    /// </summary>
    public readonly string Family;
    /// <summary>
    /// 线索对应的具名反应(fg.TbReaction;一条父固件带它的标签A、另一条带标签B)
    /// </summary>
    public readonly string Reaction;
    /// <summary>
    /// 名称文本键(混合固件的名字也用它,FGR-FW-050“名称来自配方表的文本键”)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 配方书排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -1802039585;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mixId:" + MixId + ","
        + "parentA:" + ParentA + ","
        + "parentB:" + ParentB + ","
        + "family:" + Family + ","
        + "reaction:" + Reaction + ","
        + "nameKey:" + NameKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

