
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 熔合合并上限
/// </summary>
public sealed partial class FusionMerge : Luban.BeanBase
{
    public FusionMerge(ByteBuf _buf) 
    {
        Field = _buf.ReadString();
        Cap = _buf.ReadFloat();
    }

    public static FusionMerge DeserializeFusionMerge(ByteBuf _buf)
    {
        return new fg.FusionMerge(_buf);
    }

    /// <summary>
    /// 读法字段(fgdata_reading.READING_FIELDS)
    /// </summary>
    public readonly string Field;
    /// <summary>
    /// 两条父固件同一字段幅度相加后的上限(混合固件的 readFields = min(A + B, cap))
    /// </summary>
    public readonly float Cap;
   
    public const int __ID__ = -1725301561;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "field:" + Field + ","
        + "cap:" + Cap + ","
        + "}";
    }
}
}

