
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 地形类型
/// </summary>
public sealed partial class GridTerrain : Luban.BeanBase
{
    public GridTerrain(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Code = _buf.ReadInt();
        NameKey = _buf.ReadString();
        Buildable = _buf.ReadInt();
        Color = _buf.ReadString();
        Pattern = _buf.ReadString();
    }

    public static GridTerrain DeserializeGridTerrain(ByteBuf _buf)
    {
        return new fg.GridTerrain(_buf);
    }

    /// <summary>
    /// 地形ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 格网里存的字节值,0=可建空地
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 1=可以放建筑
    /// </summary>
    public readonly int Buildable;
    /// <summary>
    /// 叠加层颜色 #RRGGBB
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// 叠加层图案:none/hatch/dots/waves/cross/grid
    /// </summary>
    public readonly string Pattern;
   
    public const int __ID__ = -578070718;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "nameKey:" + NameKey + ","
        + "buildable:" + Buildable + ","
        + "color:" + Color + ","
        + "pattern:" + Pattern + ","
        + "}";
    }
}
}

