
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 家园与格网调参
/// </summary>
public sealed partial class HomeTuning : Luban.BeanBase
{
    public HomeTuning(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Value = _buf.ReadFloat();
        Note = _buf.ReadString();
    }

    public static HomeTuning DeserializeHomeTuning(ByteBuf _buf)
    {
        return new fg.HomeTuning(_buf);
    }

    /// <summary>
    /// 参数ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 含义与出处
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -1882515487;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

