
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 情报类型
/// </summary>
public sealed partial class IntelKind : Luban.BeanBase
{
    public IntelKind(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Glyph = _buf.ReadString();
        Color = _buf.ReadString();
        SortOrder = _buf.ReadInt();
        DecipherSeconds = _buf.ReadFloat();
        ValiditySeconds = _buf.ReadFloat();
        Condition = _buf.ReadString();
        OpensIn = _buf.ReadString();
        CodexId = _buf.ReadString();
    }

    public static IntelKind DeserializeIntelKind(ByteBuf _buf)
    {
        return new fg.IntelKind(_buf);
    }

    /// <summary>
    /// 情报类型ID(存档 IntelRecord.Kind 引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(面板悬停 / 图鉴)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 占位标记字(行首方括号里的字,颜色之外的区分;美术阶段换图标)
    /// </summary>
    public readonly string Glyph;
    /// <summary>
    /// 颜色 #RRGGBB
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// 优先级与排序:越小越先破译、越靠前
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 一座监听站破译一条要多少游戏秒(多座按 fg.TbBuildingStack 加速)
    /// </summary>
    public readonly float DecipherSeconds;
    /// <summary>
    /// 有效期(游戏秒);0 = 突袭预报,有效到预报的抵达窗口结束
    /// </summary>
    public readonly float ValiditySeconds;
    /// <summary>
    /// 什么时候需要破译:raid=有逼近家园且没有有效预报的突袭部队;expedition=没有有效的反制预览;boss=有遭遇过、未击败、没有有效弱点情报的首领;tier:N=要求工作中的监听站等级 N;act:N=第 N 幕起且有未截获的片段
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 数据来源系统还没做:承接 Story ID(此时这一类不会被破译,面板写“后续版本开放”);已就绪 = none
    /// </summary>
    public readonly string OpensIn;
    /// <summary>
    /// 图鉴条目(fg.TbCodexEntry.id)
    /// </summary>
    public readonly string CodexId;
   
    public const int __ID__ = 1929706621;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "glyph:" + Glyph + ","
        + "color:" + Color + ","
        + "sortOrder:" + SortOrder + ","
        + "decipherSeconds:" + DecipherSeconds + ","
        + "validitySeconds:" + ValiditySeconds + ","
        + "condition:" + Condition + ","
        + "opensIn:" + OpensIn + ","
        + "codexId:" + CodexId + ","
        + "}";
    }
}
}

