
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 首领弱点情报
/// </summary>
public sealed partial class IntelBoss : Luban.BeanBase
{
    public IntelBoss(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        Rule = _buf.ReadString();
        PhasesKey = _buf.ReadString();
        WeaknessKey = _buf.ReadString();
        AdviceKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static IntelBoss DeserializeIntelBoss(ByteBuf _buf)
    {
        return new fg.IntelBoss(_buf);
    }

    /// <summary>
    /// 首领ID(存档 IntelRecord.Subject)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 遭遇 / 击败的判定(代码里的规则名):foundry_core=铸造前哨主核心(进过核心分区 = 遭遇过)
    /// </summary>
    public readonly string Rule;
    /// <summary>
    /// 阶段机制文本键(数值由代码按首领常量填,单一真相)
    /// </summary>
    public readonly string PhasesKey;
    /// <summary>
    /// 弱点文本键
    /// </summary>
    public readonly string WeaknessKey;
    /// <summary>
    /// 应对建议文本键
    /// </summary>
    public readonly string AdviceKey;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 1929444438;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "rule:" + Rule + ","
        + "phasesKey:" + PhasesKey + ","
        + "weaknessKey:" + WeaknessKey + ","
        + "adviceKey:" + AdviceKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

