
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 本地化文本
/// </summary>
public sealed partial class LocText : Luban.BeanBase
{
    public LocText(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Zh = _buf.ReadString();
        En = _buf.ReadString();
    }

    public static LocText DeserializeLocText(ByteBuf _buf)
    {
        return new fg.LocText(_buf);
    }

    /// <summary>
    /// 文本键
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 简体中文
    /// </summary>
    public readonly string Zh;
    /// <summary>
    /// English
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = 513810496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "zh:" + Zh + ","
        + "en:" + En + ","
        + "}";
    }
}
}

