
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机械敌人
/// </summary>
public sealed partial class MechEnemy : Luban.BeanBase
{
    public MechEnemy(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        MaxHp = _buf.ReadFloat();
        FrontalDamageReduction = _buf.ReadFloat();
        ScrapLoot = _buf.ReadInt();
    }

    public static MechEnemy DeserializeMechEnemy(ByteBuf _buf)
    {
        return new fg.MechEnemy(_buf);
    }

    /// <summary>
    /// 敌人类型ID(RegionEnemyRecord.EnemyTypeId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly float MaxHp;
    /// <summary>
    /// 正面受击减伤比例0~1,0=无正面护甲
    /// </summary>
    public readonly float FrontalDamageReduction;
    /// <summary>
    /// 击破掉落废料,0=不走普通废料掉落
    /// </summary>
    public readonly int ScrapLoot;
   
    public const int __ID__ = -1662319490;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "maxHp:" + MaxHp + ","
        + "frontalDamageReduction:" + FrontalDamageReduction + ","
        + "scrapLoot:" + ScrapLoot + ","
        + "}";
    }
}
}

