
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 通知分级
/// </summary>
public sealed partial class NotifyTier : Luban.BeanBase
{
    public NotifyTier(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        Rank = _buf.ReadInt();
        SfxId = _buf.ReadString();
        SoundCooldownSeconds = _buf.ReadFloat();
        ToastSeconds = _buf.ReadFloat();
    }

    public static NotifyTier DeserializeNotifyTier(ByteBuf _buf)
    {
        return new fg.NotifyTier(_buf);
    }

    /// <summary>
    /// 等级ID:urgent/warning/info
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 等级名文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 排序,0=最紧急
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 该等级提示音(Assets/GameRes/Raw/Audios/Sfx/&lt;id&gt;.wav)
    /// </summary>
    public readonly string SfxId;
    /// <summary>
    /// 同一等级提示音最小间隔(真实秒)
    /// </summary>
    public readonly float SoundCooldownSeconds;
    /// <summary>
    /// 弹出提示默认停留(真实秒),乘以设置里的停留倍率
    /// </summary>
    public readonly float ToastSeconds;
   
    public const int __ID__ = 321432632;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "rank:" + Rank + ","
        + "sfxId:" + SfxId + ","
        + "soundCooldownSeconds:" + SoundCooldownSeconds + ","
        + "toastSeconds:" + ToastSeconds + ","
        + "}";
    }
}
}

