
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 通知类型
/// </summary>
public sealed partial class NotifyType : Luban.BeanBase
{
    public NotifyType(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Tier = _buf.ReadString();
        NameKey = _buf.ReadString();
        SingleKey = _buf.ReadString();
        ManyKey = _buf.ReadString();
        Cues = _buf.ReadString();
        AutoPauseDefault = _buf.ReadInt();
        AggregateWindowSeconds = _buf.ReadFloat();
        KeepInHistory = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static NotifyType DeserializeNotifyType(ByteBuf _buf)
    {
        return new fg.NotifyType(_buf);
    }

    /// <summary>
    /// 通知类型ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 等级:urgent/warning/info
    /// </summary>
    public readonly string Tier;
    /// <summary>
    /// 类型名文本键(筛选用)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 单条正文文本键,{0}=细节
    /// </summary>
    public readonly string SingleKey;
    /// <summary>
    /// 聚合正文文本键,{0}=条数
    /// </summary>
    public readonly string ManyKey;
    /// <summary>
    /// 自动转换的反馈时刻 FeedbackCueId,|分隔;none=只由代码发
    /// </summary>
    public readonly string Cues;
    /// <summary>
    /// 1=默认触发时自动暂停
    /// </summary>
    public readonly int AutoPauseDefault;
    /// <summary>
    /// 同类通知在此窗口内合并(真实秒)
    /// </summary>
    public readonly float AggregateWindowSeconds;
    /// <summary>
    /// 1=进入通知历史与存档
    /// </summary>
    public readonly int KeepInHistory;
    /// <summary>
    /// 筛选下拉里的排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 321448336;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tier:" + Tier + ","
        + "nameKey:" + NameKey + ","
        + "singleKey:" + SingleKey + ","
        + "manyKey:" + ManyKey + ","
        + "cues:" + Cues + ","
        + "autoPauseDefault:" + AutoPauseDefault + ","
        + "aggregateWindowSeconds:" + AggregateWindowSeconds + ","
        + "keepInHistory:" + KeepInHistory + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

