
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 电力节点
/// </summary>
public sealed partial class PowerNode : Luban.BeanBase
{
    public PowerNode(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        CoverRadius = _buf.ReadFloat();
        StorageCapacity = _buf.ReadFloat();
        StorageRate = _buf.ReadFloat();
    }

    public static PowerNode DeserializePowerNode(ByteBuf _buf)
    {
        return new fg.PowerNode(_buf);
    }

    /// <summary>
    /// 建筑类型ID(=fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 电力覆盖半径(格),0=不是电力节点;节点之间距离&lt;=两者较大半径即相连
    /// </summary>
    public readonly float CoverRadius;
    /// <summary>
    /// 储能容量(电&#183;分钟),0=不储能
    /// </summary>
    public readonly float StorageCapacity;
    /// <summary>
    /// 最大充放电功率(电),0=不储能
    /// </summary>
    public readonly float StorageRate;
   
    public const int __ID__ = -2016549990;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "coverRadius:" + CoverRadius + ","
        + "storageCapacity:" + StorageCapacity + ","
        + "storageRate:" + StorageRate + ","
        + "}";
    }
}
}

