
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 发电类别
/// </summary>
public sealed partial class PowerSource : Luban.BeanBase
{
    public PowerSource(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        SourceClass = _buf.ReadString();
        Kind = _buf.ReadString();
        LegendKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static PowerSource DeserializePowerSource(ByteBuf _buf)
    {
        return new fg.PowerSource(_buf);
    }

    /// <summary>
    /// 发电建筑类型ID(=fg.TbBuilding.typeId;core=归还核心自带的基础供电)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 发电类别(曲线上分开显示;同类合一条线)
    /// </summary>
    public readonly string SourceClass;
    /// <summary>
    /// fixed=运转即满额/fuel=烧燃油按负荷出力/solar=乘昼夜天气系数
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 类别名文本键(曲线图例/读数)
    /// </summary>
    public readonly string LegendKey;
    /// <summary>
    /// 排序(类别按首次出现的顺序编号,最多8类)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -730622029;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "sourceClass:" + SourceClass + ","
        + "kind:" + Kind + ","
        + "legendKey:" + LegendKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

