
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 生产参数
/// </summary>
public sealed partial class Producer : Luban.BeanBase
{
    public Producer(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        Mode = _buf.ReadString();
        Recipes = _buf.ReadString();
        InBatches = _buf.ReadInt();
        OutBatches = _buf.ReadInt();
        CycleSeconds = _buf.ReadFloat();
        CycleAmount = _buf.ReadInt();
        ItemSeconds = _buf.ReadFloat();
        FluidLpm = _buf.ReadFloat();
        VibrationPerMinute = _buf.ReadFloat();
        PlaceHintKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static Producer DeserializeProducer(ByteBuf _buf)
    {
        return new fg.Producer(_buf);
    }

    /// <summary>
    /// 建筑类型ID(=fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// recycler=回收站/drill=提取钻/recipe=按配方/waste=废液池/pump=流体泵
    /// </summary>
    public readonly string Mode;
    /// <summary>
    /// 可用配方ID,逗号分隔;none=不用配方
    /// </summary>
    public readonly string Recipes;
    /// <summary>
    /// 输入缓存:配方建筑=几批;回收站=件数;其余0
    /// </summary>
    public readonly int InBatches;
    /// <summary>
    /// 输出缓存:配方建筑=几批;回收站/提取钻=件数;流体泵=出口存量几秒的抽取量;废液池0
    /// </summary>
    public readonly int OutBatches;
    /// <summary>
    /// 提取钻每份矿/回收站每批废墟废料的秒数(1x 现实秒);其余0
    /// </summary>
    public readonly float CycleSeconds;
    /// <summary>
    /// 每个周期产出几份(提取钻的矿/回收站拆废墟的废料);其余0
    /// </summary>
    public readonly int CycleAmount;
    /// <summary>
    /// 回收站分解一件固体的秒数;其余0
    /// </summary>
    public readonly float ItemSeconds;
    /// <summary>
    /// 废液池销毁速率/流体泵抽取速率(升/分钟);其余0
    /// </summary>
    public readonly float FluidLpm;
    /// <summary>
    /// 工作时每分钟增加的家园震动值(FG10);0=不产生震动
    /// </summary>
    public readonly float VibrationPerMinute;
    /// <summary>
    /// 放在哪里、为什么(文本键)
    /// </summary>
    public readonly string PlaceHintKey;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 150856255;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "mode:" + Mode + ","
        + "recipes:" + Recipes + ","
        + "inBatches:" + InBatches + ","
        + "outBatches:" + OutBatches + ","
        + "cycleSeconds:" + CycleSeconds + ","
        + "cycleAmount:" + CycleAmount + ","
        + "itemSeconds:" + ItemSeconds + ","
        + "fluidLpm:" + FluidLpm + ","
        + "vibrationPerMinute:" + VibrationPerMinute + ","
        + "placeHintKey:" + PlaceHintKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

