
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭编成
/// </summary>
public sealed partial class RaidUnit : Luban.BeanBase
{
    public RaidUnit(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Faction = _buf.ReadString();
        EnemyTypeId = _buf.ReadString();
        Role = _buf.ReadString();
        Points = _buf.ReadInt();
        MinLevel = _buf.ReadInt();
        Weight = _buf.ReadFloat();
        ElitePoints = _buf.ReadInt();
        Tags = _buf.ReadString();
    }

    public static RaidUnit DeserializeRaidUnit(ByteBuf _buf)
    {
        return new fg.RaidUnit(_buf);
    }

    /// <summary>
    /// 行ID(阵营.单位)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 阵营键(silent / foundry / clarity / overclock)
    /// </summary>
    public readonly string Faction;
    /// <summary>
    /// 敌人类型(fg.TbMechEnemy.id)
    /// </summary>
    public readonly string EnemyTypeId;
    /// <summary>
    /// 职能(FGR-DEF-030):assault=突击,sabotage=破坏,siege=攻城
    /// </summary>
    public readonly string Role;
    /// <summary>
    /// 普通单位的点数
    /// </summary>
    public readonly int Points;
    /// <summary>
    /// 最低突袭等级(0 = 骚扰也会出现)
    /// </summary>
    public readonly int MinLevel;
    /// <summary>
    /// 编成时的抽取权重
    /// </summary>
    public readonly float Weight;
    /// <summary>
    /// 精英的点数(单位数到上限后,剩余预算把普通单位换成精英,FG16 第 5 节)
    /// </summary>
    public readonly int ElitePoints;
    /// <summary>
    /// 反制标签(逗号分隔;fg.TbRaidCounter.tag 命中时权重 &#215; boost);none=没有
    /// </summary>
    public readonly string Tags;
   
    public const int __ID__ = 1261098715;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "faction:" + Faction + ","
        + "enemyTypeId:" + EnemyTypeId + ","
        + "role:" + Role + ","
        + "points:" + Points + ","
        + "minLevel:" + MinLevel + ","
        + "weight:" + Weight + ","
        + "elitePoints:" + ElitePoints + ","
        + "tags:" + Tags + ","
        + "}";
    }
}
}

