
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭等级
/// </summary>
public sealed partial class RaidLevel : Luban.BeanBase
{
    public RaidLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Level = _buf.ReadInt();
        Budget = _buf.ReadInt();
        NameKey = _buf.ReadString();
    }

    public static RaidLevel DeserializeRaidLevel(ByteBuf _buf)
    {
        return new fg.RaidLevel(_buf);
    }

    /// <summary>
    /// 行ID(level.等级)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 突袭等级:0=低强度骚扰,1～4=暴露阈值等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 等级基础预算(单位点数;再乘幕系数、难度规模、间隔系数)
    /// </summary>
    public readonly int Budget;
    /// <summary>
    /// 等级名称文本键
    /// </summary>
    public readonly string NameKey;
   
    public const int __ID__ = 430786829;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "budget:" + Budget + ","
        + "nameKey:" + NameKey + ","
        + "}";
    }
}
}

