
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 剧情突袭
/// </summary>
public sealed partial class RaidStory : Luban.BeanBase
{
    public RaidStory(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Rule = _buf.ReadString();
        Faction = _buf.ReadString();
        Level = _buf.ReadInt();
        NameKey = _buf.ReadString();
    }

    public static RaidStory DeserializeRaidStory(ByteBuf _buf)
    {
        return new fg.RaidStory(_buf);
    }

    /// <summary>
    /// 剧情突袭ID(存档记“已触发”)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 判定规则(代码里的规则名):foundry_core=铸造前哨主核心被击败
    /// </summary>
    public readonly string Rule;
    /// <summary>
    /// 报复的阵营键
    /// </summary>
    public readonly string Faction;
    /// <summary>
    /// 突袭等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 名称文本键(预警 / 历史)
    /// </summary>
    public readonly string NameKey;
   
    public const int __ID__ = 437692030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "rule:" + Rule + ","
        + "faction:" + Faction + ","
        + "level:" + Level + ","
        + "nameKey:" + NameKey + ","
        + "}";
    }
}
}

