
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭难度
/// </summary>
public sealed partial class RaidDifficulty : Luban.BeanBase
{
    public RaidDifficulty(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        StoryOnly = _buf.ReadInt();
        Scale = _buf.ReadFloat();
        Frequency = _buf.ReadFloat();
        Warning = _buf.ReadFloat();
        NameKey = _buf.ReadString();
    }

    public static RaidDifficulty DeserializeRaidDifficulty(ByteBuf _buf)
    {
        return new fg.RaidDifficulty(_buf);
    }

    /// <summary>
    /// 难度ID(= 存档 CampaignState.DifficultyId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 1=只有剧情突袭(建造者)
    /// </summary>
    public readonly int StoryOnly;
    /// <summary>
    /// 突袭规模倍率(乘到预算上)
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 突袭频率倍率(最短间隔 &#247; 本值)
    /// </summary>
    public readonly float Frequency;
    /// <summary>
    /// 预警时间倍率(最短预警 &#215; 本值)
    /// </summary>
    public readonly float Warning;
    /// <summary>
    /// 难度名称文本键
    /// </summary>
    public readonly string NameKey;
   
    public const int __ID__ = -125020206;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "storyOnly:" + StoryOnly + ","
        + "scale:" + Scale + ","
        + "frequency:" + Frequency + ","
        + "warning:" + Warning + ","
        + "nameKey:" + NameKey + ","
        + "}";
    }
}
}

