
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭反制
/// </summary>
public sealed partial class RaidCounter : Luban.BeanBase
{
    public RaidCounter(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Faction = _buf.ReadString();
        Category = _buf.ReadString();
        Tag = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Boost = _buf.ReadFloat();
    }

    public static RaidCounter DeserializeRaidCounter(ByteBuf _buf)
    {
        return new fg.RaidCounter(_buf);
    }

    /// <summary>
    /// 行ID(阵营.被针对的固件类别)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 阵营键
    /// </summary>
    public readonly string Faction;
    /// <summary>
    /// 玩家防线里用得最多的固件类别(fuse / limiter / fluid / em)
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 对策标签(编成表 tags 里带它的单位更容易被选中)
    /// </summary>
    public readonly string Tag;
    /// <summary>
    /// 对策名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 对策说明文本键(情报 / 预警悬停)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 带对策标签的单位的权重倍率
    /// </summary>
    public readonly float Boost;
   
    public const int __ID__ = -1737636539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "faction:" + Faction + ","
        + "category:" + Category + ","
        + "tag:" + Tag + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "boost:" + Boost + ","
        + "}";
    }
}
}

