
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭触发
/// </summary>
public sealed partial class RaidTrigger : Luban.BeanBase
{
    public RaidTrigger(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Exempt = _buf.ReadInt();
        LevelRule = _buf.ReadString();
        OpensIn = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static RaidTrigger DeserializeRaidTrigger(ByteBuf _buf)
    {
        return new fg.RaidTrigger(_buf);
    }

    /// <summary>
    /// 触发种类ID(存档 RaidPlanRecord.Trigger 引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(图鉴 / 预警悬停)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 1=不受最短间隔限制,与时间重叠的普通突袭合并为一波(剧情 / 静默夜 / 巨构阶段);0=普通触发
    /// </summary>
    public readonly int Exempt;
    /// <summary>
    /// 等级怎么定:exposure=按越过的阈值;request=调用方给出;tier=按当前暴露档位(至少 1 级);harass=骚扰(raid.level 表 level=0 那一行)
    /// </summary>
    public readonly string LevelRule;
    /// <summary>
    /// 触发来源系统还没做:承接 Story ID(此前只有接口与自检);已接入 = none
    /// </summary>
    public readonly string OpensIn;
    /// <summary>
    /// 排序(图鉴 / 历史显示顺序)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 539608321;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "exempt:" + Exempt + ","
        + "levelRule:" + LevelRule + ","
        + "opensIn:" + OpensIn + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

