
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 靶子类型
/// </summary>
public sealed partial class RangeTarget : Luban.BeanBase
{
    public RangeTarget(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Archetype = _buf.ReadString();
        UnlockEnemies = _buf.ReadString();
        Hp = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        Count = _buf.ReadInt();
        Armor = _buf.ReadFloat();
        ArmorHalfAngle = _buf.ReadFloat();
        Speed = _buf.ReadFloat();
        PatrolRadius = _buf.ReadFloat();
        SortOrder = _buf.ReadInt();
    }

    public static RangeTarget DeserializeRangeTarget(ByteBuf _buf)
    {
        return new fg.RangeTarget(_buf);
    }

    /// <summary>
    /// 靶子类型ID(存档的靶子布置 / 预设引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 原型:basic=标准/heavy=重甲(正面减伤)/fast=高速(摆动)/swarm=集群(多个小靶)/shield=护盾(全方位减伤)
    /// </summary>
    public readonly string Archetype;
    /// <summary>
    /// 解锁条件:always=一开始就有;否则 fg.TbMechEnemy.id 逗号分隔,击败过其中任意一种即解锁
    /// </summary>
    public readonly string UnlockEnemies;
    /// <summary>
    /// 每个靶的生命
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 半径(米)
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 一个靶位放几个(集群 &gt;1)
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 减伤比例 0~0.9,0=没有
    /// </summary>
    public readonly float Armor;
    /// <summary>
    /// 减伤覆盖的半角(度):60=只挡正面,180=全方位
    /// </summary>
    public readonly float ArmorHalfAngle;
    /// <summary>
    /// 摆动速度(米/秒),0=不动
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 摆动半径(米),0=不动
    /// </summary>
    public readonly float PatrolRadius;
    /// <summary>
    /// 面板排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -1932507295;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "archetype:" + Archetype + ","
        + "unlockEnemies:" + UnlockEnemies + ","
        + "hp:" + Hp + ","
        + "radius:" + Radius + ","
        + "count:" + Count + ","
        + "armor:" + Armor + ","
        + "armorHalfAngle:" + ArmorHalfAngle + ","
        + "speed:" + Speed + ","
        + "patrolRadius:" + PatrolRadius + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

