
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 配方
/// </summary>
public sealed partial class Recipe : Luban.BeanBase
{
    public Recipe(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        Building = _buf.ReadString();
        BuildingNameKey = _buf.ReadString();
        Seconds = _buf.ReadFloat();
        Kind = _buf.ReadString();
        Provisional = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static Recipe DeserializeRecipe(ByteBuf _buf)
    {
        return new fg.Recipe(_buf);
    }

    /// <summary>
    /// 配方ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 生产它的建筑类型ID(BuildingTypeId;建筑本身由 FG4-ECO-02/03 入建筑表)
    /// </summary>
    public readonly string Building;
    /// <summary>
    /// 建筑名文本键(图鉴与悬停显示)
    /// </summary>
    public readonly string BuildingNameKey;
    /// <summary>
    /// 1x 下的现实秒(运行时换成游戏时钟步数)
    /// </summary>
    public readonly float Seconds;
    /// <summary>
    /// fixed=表即最终值;component_table=按组件表(表里是初值基准);blueprint=按蓝图(表里是初值基准);firmware=输出指定的已破解固件
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 1=设计文档没给数、本 Story 补的初值(FG16 调;待用户复核);0=设计文档原值
    /// </summary>
    public readonly int Provisional;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -236507269;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "building:" + Building + ","
        + "buildingNameKey:" + BuildingNameKey + ","
        + "seconds:" + Seconds + ","
        + "kind:" + Kind + ","
        + "provisional:" + Provisional + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

