
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 配方行
/// </summary>
public sealed partial class RecipeIo : Luban.BeanBase
{
    public RecipeIo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Recipe = _buf.ReadString();
        Item = _buf.ReadString();
        Amount = _buf.ReadInt();
        Role = _buf.ReadString();
    }

    public static RecipeIo DeserializeRecipeIo(ByteBuf _buf)
    {
        return new fg.RecipeIo(_buf);
    }

    /// <summary>
    /// 行ID(配方序号*100+行序号,唯一)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 配方ID(fg.TbRecipe.id)
    /// </summary>
    public readonly string Recipe;
    /// <summary>
    /// 物品ID(fg.TbItem.id)
    /// </summary>
    public readonly string Item;
    /// <summary>
    /// 数量(固体按件,流体按升)
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// in=输入/out=产出/byproduct=副产品(必须有去处,FG4-ECO-10)
    /// </summary>
    public readonly string Role;
   
    public const int __ID__ = 349783553;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "recipe:" + Recipe + ","
        + "item:" + Item + ","
        + "amount:" + Amount + ","
        + "role:" + Role + ","
        + "}";
    }
}
}

