
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 已移除内容
/// </summary>
public sealed partial class RemovedContent : Luban.BeanBase
{
    public RemovedContent(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        NameKey = _buf.ReadString();
        ScrapRefund = _buf.ReadInt();
        RemovedInContentVersion = _buf.ReadInt();
    }

    public static RemovedContent DeserializeRemovedContent(ByteBuf _buf)
    {
        return new fg.RemovedContent(_buf);
    }

    /// <summary>
    /// 已移除的内容ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 内容类别:primitive_chip
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 名称文本键(fg.TbLocText),读档通知用
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 每件转换成的废料数,&gt;=0
    /// </summary>
    public readonly int ScrapRefund;
    /// <summary>
    /// 从哪个内容版本起移除,&gt;=2
    /// </summary>
    public readonly int RemovedInContentVersion;
   
    public const int __ID__ = -1676401434;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "nameKey:" + NameKey + ","
        + "scrapRefund:" + ScrapRefund + ","
        + "removedInContentVersion:" + RemovedInContentVersion + ","
        + "}";
    }
}
}

