
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 研发分支
/// </summary>
public sealed partial class ResearchBranch : Luban.BeanBase
{
    public ResearchBranch(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        Kind = _buf.ReadString();
        Faction = _buf.ReadString();
        Color = _buf.ReadString();
        Glyph = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static ResearchBranch DeserializeResearchBranch(ByteBuf _buf)
    {
        return new fg.ResearchBranch(_buf);
    }

    /// <summary>
    /// 分支ID(节点ID的前缀)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// general=通用分支(开局开放);faction=阵营分支(破解该阵营第一件技术后开放)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 阵营分支的阵营ID(fg.TbFirmwareKind.faction:silent/foundry/clarity/overclock);通用分支 none
    /// </summary>
    public readonly string Faction;
    /// <summary>
    /// 分支颜色 #RRGGBB(树上节点左边的色条;状态另有文字,不只靠颜色)
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// 占位图标上的字(美术阶段换正式图标)
    /// </summary>
    public readonly string Glyph;
    /// <summary>
    /// 排序(树上从上到下、筛选按钮从左到右)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 1737330698;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "kind:" + Kind + ","
        + "faction:" + Faction + ","
        + "color:" + Color + ","
        + "glyph:" + Glyph + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

