
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 研发节点
/// </summary>
public sealed partial class ResearchNode : Luban.BeanBase
{
    public ResearchNode(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Branch = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Kind = _buf.ReadString();
        Cost = _buf.ReadInt();
        Prereqs = _buf.ReadString();
        KeyItems = _buf.ReadString();
        Unlocks = _buf.ReadString();
        EffectKind = _buf.ReadString();
        EffectTarget = _buf.ReadString();
        EffectValue = _buf.ReadFloat();
        Col = _buf.ReadInt();
        Row = _buf.ReadInt();
        OpensIn = _buf.ReadString();
    }

    public static ResearchNode DeserializeResearchNode(ByteBuf _buf)
    {
        return new fg.ResearchNode(_buf);
    }

    /// <summary>
    /// 节点ID(分支ID.名字;存档与 unlockRule research:&lt;ID&gt; 引用它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 分支(fg.TbResearchBranch.id)
    /// </summary>
    public readonly string Branch;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// building=建筑/工具解锁;upgrade=建筑升级;efficiency=效率;capacity=容量;slot=超控阵列槽位;blueprint=阵营蓝图
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 研究点,&gt;=1
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 前置节点ID,逗号分隔(都完成才能开始投入;可以按顺序一起排进队列)
    /// </summary>
    public readonly string Prereqs;
    /// <summary>
    /// 需要核心保管库里有的关键材料 itemId:件数,逗号分隔(门槛,不消耗)
    /// </summary>
    public readonly string KeyItems;
    /// <summary>
    /// 解锁:build:&lt;建造菜单条目ID&gt; / tier:&lt;typeId&gt;.tN,逗号分隔
    /// </summary>
    public readonly string Unlocks;
    /// <summary>
    /// 效果:none/speed(生产建筑工作速度)/lab(实验室转换效率)/capacity(容量)
    /// </summary>
    public readonly string EffectKind;
    /// <summary>
    /// speed=建造菜单分类(gathering/processing/manufacturing);lab=sim_lab;capacity=warehouse/energy_storage;none 空
    /// </summary>
    public readonly string EffectTarget;
    /// <summary>
    /// 效果值(0.10=+10%)
    /// </summary>
    public readonly float EffectValue;
    /// <summary>
    /// 树上的列(0 起;前置必须在更左的列)
    /// </summary>
    public readonly int Col;
    /// <summary>
    /// 分支内的行(0 起)
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 内容还没做:承接 Story ID(此时不能加入队列;界面写“后续版本开放”);内容已就绪 = 空
    /// </summary>
    public readonly string OpensIn;
   
    public const int __ID__ = -1812360598;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "branch:" + Branch + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "kind:" + Kind + ","
        + "cost:" + Cost + ","
        + "prereqs:" + Prereqs + ","
        + "keyItems:" + KeyItems + ","
        + "unlocks:" + Unlocks + ","
        + "effectKind:" + EffectKind + ","
        + "effectTarget:" + EffectTarget + ","
        + "effectValue:" + EffectValue + ","
        + "col:" + Col + ","
        + "row:" + Row + ","
        + "opensIn:" + OpensIn + ","
        + "}";
    }
}
}

