
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机器岗位
/// </summary>
public sealed partial class RosterRole : Luban.BeanBase
{
    public RosterRole(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Code = _buf.ReadInt();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Settable = _buf.ReadInt();
        TakesLabor = _buf.ReadInt();
        AutoActions = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static RosterRole DeserializeRosterRole(ByteBuf _buf)
    {
        return new fg.RosterRole(_buf);
    }

    /// <summary>
    /// 岗位ID(代码里的 MachineRole 枚举名的小写下划线形式)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// MachineRole 枚举值(存档里存这个整数;0 = 劳动,旧档缺字段读成劳动)
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 岗位名文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 一句话说明文本键(名册下拉框悬停与图鉴)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 1 = 玩家能在名册里选;0 = 只能由系统进入(远征中)
    /// </summary>
    public readonly int Settable;
    /// <summary>
    /// 1 = 接劳动工作单(施工、搬运、拆解、维修、充电、补给)
    /// </summary>
    public readonly int TakesLabor;
    /// <summary>
    /// 1 = 常驻规则可以自动派遣它(送修、驻防);0 = 闲置,什么都不做
    /// </summary>
    public readonly int AutoActions;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -1069973234;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "settable:" + Settable + ","
        + "takesLabor:" + TakesLabor + ","
        + "autoActions:" + AutoActions + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

