
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 规则类型
/// </summary>
public sealed partial class RuleKind : Luban.BeanBase
{
    public RuleKind(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        ThresholdKey = _buf.ReadString();
        ThresholdDefault = _buf.ReadInt();
        ThresholdMin = _buf.ReadInt();
        ThresholdMax = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static RuleKind DeserializeRuleKind(ByteBuf _buf)
    {
        return new fg.RuleKind(_buf);
    }

    /// <summary>
    /// 规则类型ID(代码里的种类常量)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 类型名文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 一句话说明文本键(新建菜单与图鉴)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 数值的含义文本键({0}=数值);none=这一类没有数值
    /// </summary>
    public readonly string ThresholdKey;
    /// <summary>
    /// 数值默认值
    /// </summary>
    public readonly int ThresholdDefault;
    /// <summary>
    /// 数值下限
    /// </summary>
    public readonly int ThresholdMin;
    /// <summary>
    /// 数值上限
    /// </summary>
    public readonly int ThresholdMax;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 1917811549;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "thresholdKey:" + ThresholdKey + ","
        + "thresholdDefault:" + ThresholdDefault + ","
        + "thresholdMin:" + ThresholdMin + ","
        + "thresholdMax:" + ThresholdMax + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

