
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 规则预设
/// </summary>
public sealed partial class RulePreset : Luban.BeanBase
{
    public RulePreset(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        NameKey = _buf.ReadString();
        ItemId = _buf.ReadString();
        Threshold = _buf.ReadInt();
        Batch = _buf.ReadInt();
        RecipeId = _buf.ReadString();
        BoostRepair = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static RulePreset DeserializeRulePreset(ByteBuf _buf)
    {
        return new fg.RulePreset(_buf);
    }

    /// <summary>
    /// 预设ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 规则类型(fg.TbRuleKind.id)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 预设名文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 物品(fg.TbEcoItem.id);none=不需要
    /// </summary>
    public readonly string ItemId;
    /// <summary>
    /// 数值(含义见 fg.TbRuleKind.thresholdKey)
    /// </summary>
    public readonly int Threshold;
    /// <summary>
    /// 阈值补给:每次送几件;其余 0
    /// </summary>
    public readonly int Batch;
    /// <summary>
    /// 库存维持:排产的配方(fg.TbRecipe.id);none=按物品自动选
    /// </summary>
    public readonly string RecipeId;
    /// <summary>
    /// 战时预案:1=维修单提到最高优先级
    /// </summary>
    public readonly int BoostRepair;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 627135592;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "nameKey:" + NameKey + ","
        + "itemId:" + ItemId + ","
        + "threshold:" + Threshold + ","
        + "batch:" + Batch + ","
        + "recipeId:" + RecipeId + ","
        + "boostRepair:" + BoostRepair + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

