
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 护盾状态机
/// </summary>
public sealed partial class ShieldState : Luban.BeanBase
{
    public ShieldState(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Code = _buf.ReadInt();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        Initial = _buf.ReadInt();
        Absorbs = _buf.ReadInt();
        Seconds = _buf.ReadFloat();
        Next = _buf.ReadString();
        OnDepleted = _buf.ReadString();
        OnPowerLost = _buf.ReadString();
        OnPowerBack = _buf.ReadString();
        RegenPerSec = _buf.ReadFloat();
        PowerMul = _buf.ReadFloat();
        EnterHp = _buf.ReadFloat();
        StatusKey = _buf.ReadString();
        StatusKind = _buf.ReadString();
    }

    public static ShieldState DeserializeShieldState(ByteBuf _buf)
    {
        return new fg.ShieldState(_buf);
    }

    /// <summary>
    /// 状态ID(存档存它;代码只认 initial / absorbs 等列,不认 ID)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 排序与内核用的编号(0 起,不重复)
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 状态名文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 状态说明文本键(面板 / 悬停:现在怎样、什么时候恢复)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 1 = 新建成的护盾从这个状态开始(恰好一行)
    /// </summary>
    public readonly int Initial;
    /// <summary>
    /// 1 = 这个状态下护盾展开、吸收敌方弹体
    /// </summary>
    public readonly int Absorbs;
    /// <summary>
    /// 持续游戏秒(0 = 不会自己结束)
    /// </summary>
    public readonly float Seconds;
    /// <summary>
    /// 时间到之后进入的状态(seconds&gt;0 时必填;none)
    /// </summary>
    public readonly string Next;
    /// <summary>
    /// 护盾值耗尽时进入的状态(absorbs=1 时必填;none)
    /// </summary>
    public readonly string OnDepleted;
    /// <summary>
    /// 断电 / 禁用时进入的状态(none = 不变)
    /// </summary>
    public readonly string OnPowerLost;
    /// <summary>
    /// 来电时进入的状态(none = 不变)
    /// </summary>
    public readonly string OnPowerBack;
    /// <summary>
    /// 每游戏秒回复护盾值上限的比例(0 = 不回复)
    /// </summary>
    public readonly float RegenPerSec;
    /// <summary>
    /// 基础耗电倍率(过载时低功耗、重启充能时高功耗)
    /// </summary>
    public readonly float PowerMul;
    /// <summary>
    /// 进入时护盾值 = 上限 &#215; 本值(-1 = 不变)
    /// </summary>
    public readonly float EnterHp;
    /// <summary>
    /// 建筑状态行文本键(参数:{0} 护盾值 {1} 上限 {2} 剩余秒 {3} 耗电;代码不认状态 ID)
    /// </summary>
    public readonly string StatusKey;
    /// <summary>
    /// 建筑状态分类:working 工作中 / idle 待机 / nopower 缺电
    /// </summary>
    public readonly string StatusKind;
   
    public const int __ID__ = -1485618981;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "initial:" + Initial + ","
        + "absorbs:" + Absorbs + ","
        + "seconds:" + Seconds + ","
        + "next:" + Next + ","
        + "onDepleted:" + OnDepleted + ","
        + "onPowerLost:" + OnPowerLost + ","
        + "onPowerBack:" + OnPowerBack + ","
        + "regenPerSec:" + RegenPerSec + ","
        + "powerMul:" + PowerMul + ","
        + "enterHp:" + EnterHp + ","
        + "statusKey:" + StatusKey + ","
        + "statusKind:" + StatusKind + ","
        + "}";
    }
}
}

