
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城建筑类别
/// </summary>
public sealed partial class SiegeCategory : Luban.BeanBase
{
    public SiegeCategory(ByteBuf _buf) 
    {
        TypeId = _buf.ReadString();
        Category = _buf.ReadString();
    }

    public static SiegeCategory DeserializeSiegeCategory(ByteBuf _buf)
    {
        return new fg.SiegeCategory(_buf);
    }

    /// <summary>
    /// 建筑类型ID(fg.TbBuilding.typeId)
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 攻城目标类别:core / power / signal / defense / listening(other 不用登记)
    /// </summary>
    public readonly string Category;
   
    public const int __ID__ = -1489221762;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "category:" + Category + ","
        + "}";
    }
}
}

