
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城单位参数
/// </summary>
public sealed partial class SiegeUnit : Luban.BeanBase
{
    public SiegeUnit(ByteBuf _buf) 
    {
        EnemyTypeId = _buf.ReadString();
        Speed = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        Range = _buf.ReadFloat();
        Damage = _buf.ReadFloat();
        Cooldown = _buf.ReadFloat();
        ProjectileSpeed = _buf.ReadFloat();
        ProjectileRadius = _buf.ReadFloat();
        StructureMult = _buf.ReadFloat();
        HealAmount = _buf.ReadFloat();
        HealRange = _buf.ReadFloat();
        HealCooldown = _buf.ReadFloat();
    }

    public static SiegeUnit DeserializeSiegeUnit(ByteBuf _buf)
    {
        return new fg.SiegeUnit(_buf);
    }

    /// <summary>
    /// 敌人类型(fg.TbMechEnemy.id)
    /// </summary>
    public readonly string EnemyTypeId;
    /// <summary>
    /// 移动速度(米/游戏秒)
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 半径(米)
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 射程(米)
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// 每发伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 开火间隔(游戏秒)
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 弹速(米/游戏秒)
    /// </summary>
    public readonly float ProjectileSpeed;
    /// <summary>
    /// 弹体半径(米)
    /// </summary>
    public readonly float ProjectileRadius;
    /// <summary>
    /// 打建筑(炮塔 / 屏障 / 建筑)时的伤害倍率
    /// </summary>
    public readonly float StructureMult;
    /// <summary>
    /// 随队维修:每次修理友军的量;0=不会修
    /// </summary>
    public readonly float HealAmount;
    /// <summary>
    /// 随队维修:多远内的友军(米);不会修填0
    /// </summary>
    public readonly float HealRange;
    /// <summary>
    /// 随队维修:间隔(游戏秒);不会修填0
    /// </summary>
    public readonly float HealCooldown;
   
    public const int __ID__ = 534356996;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyTypeId:" + EnemyTypeId + ","
        + "speed:" + Speed + ","
        + "radius:" + Radius + ","
        + "range:" + Range + ","
        + "damage:" + Damage + ","
        + "cooldown:" + Cooldown + ","
        + "projectileSpeed:" + ProjectileSpeed + ","
        + "projectileRadius:" + ProjectileRadius + ","
        + "structureMult:" + StructureMult + ","
        + "healAmount:" + HealAmount + ","
        + "healRange:" + HealRange + ","
        + "healCooldown:" + HealCooldown + ","
        + "}";
    }
}
}

