
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城职能目标
/// </summary>
public sealed partial class SiegeTarget : Luban.BeanBase
{
    public SiegeTarget(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Role = _buf.ReadString();
        Category = _buf.ReadString();
        BiasMeters = _buf.ReadFloat();
    }

    public static SiegeTarget DeserializeSiegeTarget(ByteBuf _buf)
    {
        return new fg.SiegeTarget(_buf);
    }

    /// <summary>
    /// 行ID(职能.类别)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 职能键(assault / sabotage / siege)
    /// </summary>
    public readonly string Role;
    /// <summary>
    /// 目标类别(fg.TbSiegeCategory.category)
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 偏好:流场里这类目标的起点值(米);0=主目标;越大越要顺路才去;没有行=不当目标
    /// </summary>
    public readonly float BiasMeters;
   
    public const int __ID__ = -1919378415;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "role:" + Role + ","
        + "category:" + Category + ","
        + "biasMeters:" + BiasMeters + ","
        + "}";
    }
}
}

