
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城职能
/// </summary>
public sealed partial class SiegeRole : Luban.BeanBase
{
    public SiegeRole(ByteBuf _buf) 
    {
        Role = _buf.ReadString();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        IconShape = _buf.ReadInt();
        IconColor = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static SiegeRole DeserializeSiegeRole(ByteBuf _buf)
    {
        return new fg.SiegeRole(_buf);
    }

    /// <summary>
    /// 职能键:assault=突击,sabotage=破坏,siege=攻城,retreat=撤退中(不是编成职能,只用来画图标)
    /// </summary>
    public readonly string Role;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(图鉴 / 叠加层图例:它要去哪里)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 头顶图标形状序号(CombatInstanced.shader:14=上箭头,15=闪电,16=城垛,17=下箭头;形状为主颜色为辅,B15)
    /// </summary>
    public readonly int IconShape;
    /// <summary>
    /// 头顶图标颜色(打包 0xRRGGBB)
    /// </summary>
    public readonly int IconColor;
    /// <summary>
    /// 排序(图例显示顺序)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 534268662;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "role:" + Role + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "iconShape:" + IconShape + ","
        + "iconColor:" + IconColor + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

