
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 开局布局
/// </summary>
public sealed partial class StartLayout : Luban.BeanBase
{
    public StartLayout(ByteBuf _buf) 
    {
        AnchorId = _buf.ReadString();
        Kind = _buf.ReadString();
        TypeId = _buf.ReadString();
        OffsetX = _buf.ReadInt();
        OffsetY = _buf.ReadInt();
        Rotation = _buf.ReadInt();
        State = _buf.ReadString();
        Health = _buf.ReadFloat();
        Clearance = _buf.ReadFloat();
    }

    public static StartLayout DeserializeStartLayout(ByteBuf _buf)
    {
        return new fg.StartLayout(_buf);
    }

    /// <summary>
    /// 锚点ID(=Demo HomeValleyLayout.Anchor.Id)
    /// </summary>
    public readonly string AnchorId;
    /// <summary>
    /// building/site/spawn/wreckage/target/exit/camera
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 建筑类型ID;非建筑填none
    /// </summary>
    public readonly string TypeId;
    /// <summary>
    /// 相对核心枢轴格的x(格)
    /// </summary>
    public readonly int OffsetX;
    /// <summary>
    /// 相对核心枢轴格的y(格,+y=北)
    /// </summary>
    public readonly int OffsetY;
    /// <summary>
    /// 0/90/180/270
    /// </summary>
    public readonly int Rotation;
    /// <summary>
    /// 开局状态:operational/damaged;非建筑填none
    /// </summary>
    public readonly string State;
    /// <summary>
    /// 开局生命;非建筑填0
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 净空半径(米),不重叠自检用
    /// </summary>
    public readonly float Clearance;
   
    public const int __ID__ = 1043704927;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "anchorId:" + AnchorId + ","
        + "kind:" + Kind + ","
        + "typeId:" + TypeId + ","
        + "offsetX:" + OffsetX + ","
        + "offsetY:" + OffsetY + ","
        + "rotation:" + Rotation + ","
        + "state:" + State + ","
        + "health:" + Health + ","
        + "clearance:" + Clearance + ","
        + "}";
    }
}
}

