
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 状态标签
/// </summary>
public sealed partial class StatusTag : Luban.BeanBase
{
    public StatusTag(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        AliasOf = _buf.ReadString();
        Shape = _buf.ReadString();
        Color = _buf.ReadString();
        Kind = _buf.ReadString();
        Bit = _buf.ReadInt();
        Effect = _buf.ReadString();
        Amount = _buf.ReadFloat();
    }

    public static StatusTag DeserializeStatusTag(ByteBuf _buf)
    {
        return new fg.StatusTag(_buf);
    }

    /// <summary>
    /// 旧引擎标签字符串(ComposeEngine HitEvent.Tags;只在数据和调试层出现)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 机械名文本键(fg.TbLocText,FGR-FW-030)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 同义主标签ID(none=本身是主标签;显示时按主标签合并)
    /// </summary>
    public readonly string AliasOf;
    /// <summary>
    /// 头顶图标形状字形(色盲安全:形状为主,FG00 B15);别名填 none
    /// </summary>
    public readonly string Shape;
    /// <summary>
    /// 图标颜色 #RRGGBB(辅助通道);别名与机制标记填 none
    /// </summary>
    public readonly string Color;
    /// <summary>
    /// status=状态标签(单位头顶显示,FGR-FW-031);marker=机制标记(旧引擎模块给能量包打的行为记号,只给反应判定/伤害归因/调试用,不在头顶显示)
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 战斗内核状态位 0～30(31 保留给区域减速);同义标签与主标签相同;机制标记 -1
    /// </summary>
    public readonly int Bit;
    /// <summary>
    /// 内核效果:none/dot/slow/vuln/leech/execute(dot=每秒伤害,slow=减速比例,vuln=易伤比例,leech=回收修复比例,execute=处决阈值,none=只是反应用的标签)
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 效果数值(见 effect)
    /// </summary>
    public readonly float Amount;
   
    public const int __ID__ = -636789445;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "aliasOf:" + AliasOf + ","
        + "shape:" + Shape + ","
        + "color:" + Color + ","
        + "kind:" + Kind + ","
        + "bit:" + Bit + ","
        + "effect:" + Effect + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

