
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 表面
/// </summary>
public sealed partial class Surface : Luban.BeanBase
{
    public Surface(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Kind = _buf.ReadString();
        NameKey = _buf.ReadString();
        Salt = _buf.ReadInt();
        WidthChunks = _buf.ReadInt();
        HeightChunks = _buf.ReadInt();
    }

    public static Surface DeserializeSurface(ByteBuf _buf)
    {
        return new fg.Surface(_buf);
    }

    /// <summary>
    /// 表面ID(存档区块差异的 SurfaceId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// planet/interior
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 表面种子盐,&gt;0且唯一,发布后不能改
    /// </summary>
    public readonly int Salt;
    /// <summary>
    /// 室内宽(区块数);星球填0
    /// </summary>
    public readonly int WidthChunks;
    /// <summary>
    /// 室内高(区块数);星球填0
    /// </summary>
    public readonly int HeightChunks;
   
    public const int __ID__ = -1677438880;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "nameKey:" + NameKey + ","
        + "salt:" + Salt + ","
        + "widthChunks:" + WidthChunks + ","
        + "heightChunks:" + HeightChunks + ","
        + "}";
    }
}
}

