
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 解析种类
/// </summary>
public partial class TbAnalysisKind
{
    private readonly System.Collections.Generic.Dictionary<string, fg.AnalysisKind> _dataMap;
    private readonly System.Collections.Generic.List<fg.AnalysisKind> _dataList;
    
    public TbAnalysisKind(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.AnalysisKind>(n);
        _dataList = new System.Collections.Generic.List<fg.AnalysisKind>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.AnalysisKind _v;
            _v = global::GameConfig.fg.AnalysisKind.DeserializeAnalysisKind(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.AnalysisKind> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.AnalysisKind> DataList => _dataList;

    public fg.AnalysisKind GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.AnalysisKind Get(string key) => _dataMap[key];
    public fg.AnalysisKind this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

