
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 背景资料
/// </summary>
public partial class TbAnalysisLore
{
    private readonly System.Collections.Generic.Dictionary<string, fg.AnalysisLore> _dataMap;
    private readonly System.Collections.Generic.List<fg.AnalysisLore> _dataList;
    
    public TbAnalysisLore(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.AnalysisLore>(n);
        _dataList = new System.Collections.Generic.List<fg.AnalysisLore>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.AnalysisLore _v;
            _v = global::GameConfig.fg.AnalysisLore.DeserializeAnalysisLore(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.AnalysisLore> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.AnalysisLore> DataList => _dataList;

    public fg.AnalysisLore GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.AnalysisLore Get(string key) => _dataMap[key];
    public fg.AnalysisLore this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

