
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机器材料
/// </summary>
public partial class TbAssemblyMaterial
{
    private readonly System.Collections.Generic.Dictionary<string, fg.AssemblyMaterial> _dataMap;
    private readonly System.Collections.Generic.List<fg.AssemblyMaterial> _dataList;
    
    public TbAssemblyMaterial(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.AssemblyMaterial>(n);
        _dataList = new System.Collections.Generic.List<fg.AssemblyMaterial>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.AssemblyMaterial _v;
            _v = global::GameConfig.fg.AssemblyMaterial.DeserializeAssemblyMaterial(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.AssemblyMaterial> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.AssemblyMaterial> DataList => _dataList;

    public fg.AssemblyMaterial GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.AssemblyMaterial Get(string key) => _dataMap[key];
    public fg.AssemblyMaterial this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

