
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 过滤器预设
/// </summary>
public partial class TbBeltFilterPreset
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BeltFilterPreset> _dataMap;
    private readonly System.Collections.Generic.List<fg.BeltFilterPreset> _dataList;
    
    public TbBeltFilterPreset(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BeltFilterPreset>(n);
        _dataList = new System.Collections.Generic.List<fg.BeltFilterPreset>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BeltFilterPreset _v;
            _v = global::GameConfig.fg.BeltFilterPreset.DeserializeBeltFilterPreset(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BeltFilterPreset> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BeltFilterPreset> DataList => _dataList;

    public fg.BeltFilterPreset GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BeltFilterPreset Get(string key) => _dataMap[key];
    public fg.BeltFilterPreset this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

