
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑等级
/// </summary>
public partial class TbBuildingTier
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildingTier> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildingTier> _dataList;
    
    public TbBuildingTier(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildingTier>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildingTier>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildingTier _v;
            _v = global::GameConfig.fg.BuildingTier.DeserializeBuildingTier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildingTier> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildingTier> DataList => _dataList;

    public fg.BuildingTier GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildingTier Get(string key) => _dataMap[key];
    public fg.BuildingTier this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

