
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑端口
/// </summary>
public partial class TbBuildingPort
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildingPort> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildingPort> _dataList;
    
    public TbBuildingPort(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildingPort>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildingPort>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildingPort _v;
            _v = global::GameConfig.fg.BuildingPort.DeserializeBuildingPort(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildingPort> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildingPort> DataList => _dataList;

    public fg.BuildingPort GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildingPort Get(string key) => _dataMap[key];
    public fg.BuildingPort this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

