
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建造菜单分类
/// </summary>
public partial class TbBuildCategory
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildCategory> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildCategory> _dataList;
    
    public TbBuildCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildCategory>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildCategory>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildCategory _v;
            _v = global::GameConfig.fg.BuildCategory.DeserializeBuildCategory(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildCategory> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildCategory> DataList => _dataList;

    public fg.BuildCategory GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildCategory Get(string key) => _dataMap[key];
    public fg.BuildCategory this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

