
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 升级路线
/// </summary>
public partial class TbBuildUpgrade
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildUpgrade> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildUpgrade> _dataList;
    
    public TbBuildUpgrade(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildUpgrade>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildUpgrade>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildUpgrade _v;
            _v = global::GameConfig.fg.BuildUpgrade.DeserializeBuildUpgrade(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FromId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildUpgrade> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildUpgrade> DataList => _dataList;

    public fg.BuildUpgrade GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildUpgrade Get(string key) => _dataMap[key];
    public fg.BuildUpgrade this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

