
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 多座建筑叠加
/// </summary>
public partial class TbBuildingStack
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildingStack> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildingStack> _dataList;
    
    public TbBuildingStack(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildingStack>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildingStack>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildingStack _v;
            _v = global::GameConfig.fg.BuildingStack.DeserializeBuildingStack(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildingStack> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildingStack> DataList => _dataList;

    public fg.BuildingStack GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildingStack Get(string key) => _dataMap[key];
    public fg.BuildingStack this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

