
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑格网属性
/// </summary>
public partial class TbBuildingGrid
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildingGrid> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildingGrid> _dataList;
    
    public TbBuildingGrid(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildingGrid>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildingGrid>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildingGrid _v;
            _v = global::GameConfig.fg.BuildingGrid.DeserializeBuildingGrid(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TypeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildingGrid> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildingGrid> DataList => _dataList;

    public fg.BuildingGrid GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildingGrid Get(string key) => _dataMap[key];
    public fg.BuildingGrid this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

