
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建造菜单工具
/// </summary>
public partial class TbBuildTool
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildTool> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildTool> _dataList;
    
    public TbBuildTool(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildTool>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildTool>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildTool _v;
            _v = global::GameConfig.fg.BuildTool.DeserializeBuildTool(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildTool> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildTool> DataList => _dataList;

    public fg.BuildTool GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildTool Get(string key) => _dataMap[key];
    public fg.BuildTool this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

