
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 建筑材料
/// </summary>
public partial class TbBuildMaterial
{
    private readonly System.Collections.Generic.Dictionary<string, fg.BuildMaterial> _dataMap;
    private readonly System.Collections.Generic.List<fg.BuildMaterial> _dataList;
    
    public TbBuildMaterial(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.BuildMaterial>(n);
        _dataList = new System.Collections.Generic.List<fg.BuildMaterial>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.BuildMaterial _v;
            _v = global::GameConfig.fg.BuildMaterial.DeserializeBuildMaterial(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.BuildMaterial> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.BuildMaterial> DataList => _dataList;

    public fg.BuildMaterial GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.BuildMaterial Get(string key) => _dataMap[key];
    public fg.BuildMaterial this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

