
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 载体读法
/// </summary>
public partial class TbCarrierReading
{
    private readonly System.Collections.Generic.Dictionary<string, fg.CarrierReading> _dataMap;
    private readonly System.Collections.Generic.List<fg.CarrierReading> _dataList;
    
    public TbCarrierReading(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.CarrierReading>(n);
        _dataList = new System.Collections.Generic.List<fg.CarrierReading>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.CarrierReading _v;
            _v = global::GameConfig.fg.CarrierReading.DeserializeCarrierReading(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.CarrierReading> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.CarrierReading> DataList => _dataList;

    public fg.CarrierReading GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.CarrierReading Get(string key) => _dataMap[key];
    public fg.CarrierReading this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

