
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机制图鉴条目
/// </summary>
public partial class TbCodexEntry
{
    private readonly System.Collections.Generic.Dictionary<string, fg.CodexEntry> _dataMap;
    private readonly System.Collections.Generic.List<fg.CodexEntry> _dataList;
    
    public TbCodexEntry(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.CodexEntry>(n);
        _dataList = new System.Collections.Generic.List<fg.CodexEntry>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.CodexEntry _v;
            _v = global::GameConfig.fg.CodexEntry.DeserializeCodexEntry(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.CodexEntry> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.CodexEntry> DataList => _dataList;

    public fg.CodexEntry GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.CodexEntry Get(string key) => _dataMap[key];
    public fg.CodexEntry this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

