
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 作战组件
/// </summary>
public partial class TbCombatComponent
{
    private readonly System.Collections.Generic.Dictionary<string, fg.CombatComponent> _dataMap;
    private readonly System.Collections.Generic.List<fg.CombatComponent> _dataList;
    
    public TbCombatComponent(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.CombatComponent>(n);
        _dataList = new System.Collections.Generic.List<fg.CombatComponent>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.CombatComponent _v;
            _v = global::GameConfig.fg.CombatComponent.DeserializeCombatComponent(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.CombatComponent> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.CombatComponent> DataList => _dataList;

    public fg.CombatComponent GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.CombatComponent Get(string key) => _dataMap[key];
    public fg.CombatComponent this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

