
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 物品
/// </summary>
public partial class TbEcoItem
{
    private readonly System.Collections.Generic.Dictionary<string, fg.EcoItem> _dataMap;
    private readonly System.Collections.Generic.List<fg.EcoItem> _dataList;
    
    public TbEcoItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.EcoItem>(n);
        _dataList = new System.Collections.Generic.List<fg.EcoItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.EcoItem _v;
            _v = global::GameConfig.fg.EcoItem.DeserializeEcoItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.EcoItem> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.EcoItem> DataList => _dataList;

    public fg.EcoItem GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.EcoItem Get(string key) => _dataMap[key];
    public fg.EcoItem this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

