
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 固件种类
/// </summary>
public partial class TbFirmwareKind
{
    private readonly System.Collections.Generic.Dictionary<string, fg.FirmwareKind> _dataMap;
    private readonly System.Collections.Generic.List<fg.FirmwareKind> _dataList;
    
    public TbFirmwareKind(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.FirmwareKind>(n);
        _dataList = new System.Collections.Generic.List<fg.FirmwareKind>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.FirmwareKind _v;
            _v = global::GameConfig.fg.FirmwareKind.DeserializeFirmwareKind(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.FirmwareKind> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.FirmwareKind> DataList => _dataList;

    public fg.FirmwareKind GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.FirmwareKind Get(string key) => _dataMap[key];
    public fg.FirmwareKind this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

