
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 流体泄漏
/// </summary>
public partial class TbFluidLeak
{
    private readonly System.Collections.Generic.Dictionary<int, fg.FluidLeak> _dataMap;
    private readonly System.Collections.Generic.List<fg.FluidLeak> _dataList;
    
    public TbFluidLeak(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fg.FluidLeak>(n);
        _dataList = new System.Collections.Generic.List<fg.FluidLeak>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.FluidLeak _v;
            _v = global::GameConfig.fg.FluidLeak.DeserializeFluidLeak(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Fluid, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fg.FluidLeak> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.FluidLeak> DataList => _dataList;

    public fg.FluidLeak GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.FluidLeak Get(int key) => _dataMap[key];
    public fg.FluidLeak this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

