
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 熔合配方
/// </summary>
public partial class TbFusionRecipe
{
    private readonly System.Collections.Generic.Dictionary<string, fg.FusionRecipe> _dataMap;
    private readonly System.Collections.Generic.List<fg.FusionRecipe> _dataList;
    
    public TbFusionRecipe(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.FusionRecipe>(n);
        _dataList = new System.Collections.Generic.List<fg.FusionRecipe>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.FusionRecipe _v;
            _v = global::GameConfig.fg.FusionRecipe.DeserializeFusionRecipe(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.FusionRecipe> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.FusionRecipe> DataList => _dataList;

    public fg.FusionRecipe GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.FusionRecipe Get(string key) => _dataMap[key];
    public fg.FusionRecipe this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

