
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 熔合合并上限
/// </summary>
public partial class TbFusionMerge
{
    private readonly System.Collections.Generic.Dictionary<string, fg.FusionMerge> _dataMap;
    private readonly System.Collections.Generic.List<fg.FusionMerge> _dataList;
    
    public TbFusionMerge(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.FusionMerge>(n);
        _dataList = new System.Collections.Generic.List<fg.FusionMerge>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.FusionMerge _v;
            _v = global::GameConfig.fg.FusionMerge.DeserializeFusionMerge(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Field, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.FusionMerge> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.FusionMerge> DataList => _dataList;

    public fg.FusionMerge GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.FusionMerge Get(string key) => _dataMap[key];
    public fg.FusionMerge this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

