
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 家园与格网调参
/// </summary>
public partial class TbHomeTuning
{
    private readonly System.Collections.Generic.Dictionary<string, fg.HomeTuning> _dataMap;
    private readonly System.Collections.Generic.List<fg.HomeTuning> _dataList;
    
    public TbHomeTuning(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.HomeTuning>(n);
        _dataList = new System.Collections.Generic.List<fg.HomeTuning>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.HomeTuning _v;
            _v = global::GameConfig.fg.HomeTuning.DeserializeHomeTuning(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.HomeTuning> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.HomeTuning> DataList => _dataList;

    public fg.HomeTuning GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.HomeTuning Get(string key) => _dataMap[key];
    public fg.HomeTuning this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

