
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 舰队信号片段
/// </summary>
public partial class TbIntelFragment
{
    private readonly System.Collections.Generic.Dictionary<string, fg.IntelFragment> _dataMap;
    private readonly System.Collections.Generic.List<fg.IntelFragment> _dataList;
    
    public TbIntelFragment(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.IntelFragment>(n);
        _dataList = new System.Collections.Generic.List<fg.IntelFragment>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.IntelFragment _v;
            _v = global::GameConfig.fg.IntelFragment.DeserializeIntelFragment(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.IntelFragment> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.IntelFragment> DataList => _dataList;

    public fg.IntelFragment GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.IntelFragment Get(string key) => _dataMap[key];
    public fg.IntelFragment this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

