
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 首领弱点情报
/// </summary>
public partial class TbIntelBoss
{
    private readonly System.Collections.Generic.Dictionary<string, fg.IntelBoss> _dataMap;
    private readonly System.Collections.Generic.List<fg.IntelBoss> _dataList;
    
    public TbIntelBoss(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.IntelBoss>(n);
        _dataList = new System.Collections.Generic.List<fg.IntelBoss>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.IntelBoss _v;
            _v = global::GameConfig.fg.IntelBoss.DeserializeIntelBoss(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.IntelBoss> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.IntelBoss> DataList => _dataList;

    public fg.IntelBoss GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.IntelBoss Get(string key) => _dataMap[key];
    public fg.IntelBoss this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

