
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 情报类型
/// </summary>
public partial class TbIntelKind
{
    private readonly System.Collections.Generic.Dictionary<string, fg.IntelKind> _dataMap;
    private readonly System.Collections.Generic.List<fg.IntelKind> _dataList;
    
    public TbIntelKind(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.IntelKind>(n);
        _dataList = new System.Collections.Generic.List<fg.IntelKind>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.IntelKind _v;
            _v = global::GameConfig.fg.IntelKind.DeserializeIntelKind(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.IntelKind> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.IntelKind> DataList => _dataList;

    public fg.IntelKind GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.IntelKind Get(string key) => _dataMap[key];
    public fg.IntelKind this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

