
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 输入动作
/// </summary>
public partial class TbInputAction
{
    private readonly System.Collections.Generic.Dictionary<string, fg.InputAction> _dataMap;
    private readonly System.Collections.Generic.List<fg.InputAction> _dataList;
    
    public TbInputAction(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.InputAction>(n);
        _dataList = new System.Collections.Generic.List<fg.InputAction>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.InputAction _v;
            _v = global::GameConfig.fg.InputAction.DeserializeInputAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.InputAction> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.InputAction> DataList => _dataList;

    public fg.InputAction GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.InputAction Get(string key) => _dataMap[key];
    public fg.InputAction this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

