
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机械敌人
/// </summary>
public partial class TbMechEnemy
{
    private readonly System.Collections.Generic.Dictionary<string, fg.MechEnemy> _dataMap;
    private readonly System.Collections.Generic.List<fg.MechEnemy> _dataList;
    
    public TbMechEnemy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.MechEnemy>(n);
        _dataList = new System.Collections.Generic.List<fg.MechEnemy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.MechEnemy _v;
            _v = global::GameConfig.fg.MechEnemy.DeserializeMechEnemy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.MechEnemy> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.MechEnemy> DataList => _dataList;

    public fg.MechEnemy GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.MechEnemy Get(string key) => _dataMap[key];
    public fg.MechEnemy this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

