
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 通知类型
/// </summary>
public partial class TbNotifyType
{
    private readonly System.Collections.Generic.Dictionary<string, fg.NotifyType> _dataMap;
    private readonly System.Collections.Generic.List<fg.NotifyType> _dataList;
    
    public TbNotifyType(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.NotifyType>(n);
        _dataList = new System.Collections.Generic.List<fg.NotifyType>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.NotifyType _v;
            _v = global::GameConfig.fg.NotifyType.DeserializeNotifyType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.NotifyType> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.NotifyType> DataList => _dataList;

    public fg.NotifyType GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.NotifyType Get(string key) => _dataMap[key];
    public fg.NotifyType this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

