
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 通知分级
/// </summary>
public partial class TbNotifyTier
{
    private readonly System.Collections.Generic.Dictionary<string, fg.NotifyTier> _dataMap;
    private readonly System.Collections.Generic.List<fg.NotifyTier> _dataList;
    
    public TbNotifyTier(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.NotifyTier>(n);
        _dataList = new System.Collections.Generic.List<fg.NotifyTier>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.NotifyTier _v;
            _v = global::GameConfig.fg.NotifyTier.DeserializeNotifyTier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.NotifyTier> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.NotifyTier> DataList => _dataList;

    public fg.NotifyTier GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.NotifyTier Get(string key) => _dataMap[key];
    public fg.NotifyTier this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

