
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 发电类别
/// </summary>
public partial class TbPowerSource
{
    private readonly System.Collections.Generic.Dictionary<string, fg.PowerSource> _dataMap;
    private readonly System.Collections.Generic.List<fg.PowerSource> _dataList;
    
    public TbPowerSource(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.PowerSource>(n);
        _dataList = new System.Collections.Generic.List<fg.PowerSource>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.PowerSource _v;
            _v = global::GameConfig.fg.PowerSource.DeserializePowerSource(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TypeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.PowerSource> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.PowerSource> DataList => _dataList;

    public fg.PowerSource GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.PowerSource Get(string key) => _dataMap[key];
    public fg.PowerSource this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

