
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 电力节点
/// </summary>
public partial class TbPowerNode
{
    private readonly System.Collections.Generic.Dictionary<string, fg.PowerNode> _dataMap;
    private readonly System.Collections.Generic.List<fg.PowerNode> _dataList;
    
    public TbPowerNode(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.PowerNode>(n);
        _dataList = new System.Collections.Generic.List<fg.PowerNode>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.PowerNode _v;
            _v = global::GameConfig.fg.PowerNode.DeserializePowerNode(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TypeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.PowerNode> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.PowerNode> DataList => _dataList;

    public fg.PowerNode GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.PowerNode Get(string key) => _dataMap[key];
    public fg.PowerNode this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

