
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 生产参数
/// </summary>
public partial class TbProducer
{
    private readonly System.Collections.Generic.Dictionary<string, fg.Producer> _dataMap;
    private readonly System.Collections.Generic.List<fg.Producer> _dataList;
    
    public TbProducer(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.Producer>(n);
        _dataList = new System.Collections.Generic.List<fg.Producer>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.Producer _v;
            _v = global::GameConfig.fg.Producer.DeserializeProducer(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TypeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.Producer> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.Producer> DataList => _dataList;

    public fg.Producer GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.Producer Get(string key) => _dataMap[key];
    public fg.Producer this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

