
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭编成
/// </summary>
public partial class TbRaidUnit
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RaidUnit> _dataMap;
    private readonly System.Collections.Generic.List<fg.RaidUnit> _dataList;
    
    public TbRaidUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RaidUnit>(n);
        _dataList = new System.Collections.Generic.List<fg.RaidUnit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RaidUnit _v;
            _v = global::GameConfig.fg.RaidUnit.DeserializeRaidUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RaidUnit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RaidUnit> DataList => _dataList;

    public fg.RaidUnit GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RaidUnit Get(string key) => _dataMap[key];
    public fg.RaidUnit this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

