
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 剧情突袭
/// </summary>
public partial class TbRaidStory
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RaidStory> _dataMap;
    private readonly System.Collections.Generic.List<fg.RaidStory> _dataList;
    
    public TbRaidStory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RaidStory>(n);
        _dataList = new System.Collections.Generic.List<fg.RaidStory>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RaidStory _v;
            _v = global::GameConfig.fg.RaidStory.DeserializeRaidStory(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RaidStory> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RaidStory> DataList => _dataList;

    public fg.RaidStory GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RaidStory Get(string key) => _dataMap[key];
    public fg.RaidStory this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

