
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 靶子类型
/// </summary>
public partial class TbRangeTarget
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RangeTarget> _dataMap;
    private readonly System.Collections.Generic.List<fg.RangeTarget> _dataList;
    
    public TbRangeTarget(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RangeTarget>(n);
        _dataList = new System.Collections.Generic.List<fg.RangeTarget>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RangeTarget _v;
            _v = global::GameConfig.fg.RangeTarget.DeserializeRangeTarget(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RangeTarget> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RangeTarget> DataList => _dataList;

    public fg.RangeTarget GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RangeTarget Get(string key) => _dataMap[key];
    public fg.RangeTarget this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

