
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 突袭难度
/// </summary>
public partial class TbRaidDifficulty
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RaidDifficulty> _dataMap;
    private readonly System.Collections.Generic.List<fg.RaidDifficulty> _dataList;
    
    public TbRaidDifficulty(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RaidDifficulty>(n);
        _dataList = new System.Collections.Generic.List<fg.RaidDifficulty>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RaidDifficulty _v;
            _v = global::GameConfig.fg.RaidDifficulty.DeserializeRaidDifficulty(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RaidDifficulty> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RaidDifficulty> DataList => _dataList;

    public fg.RaidDifficulty GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RaidDifficulty Get(string key) => _dataMap[key];
    public fg.RaidDifficulty this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

