
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 配方行
/// </summary>
public partial class TbRecipeIo
{
    private readonly System.Collections.Generic.Dictionary<int, fg.RecipeIo> _dataMap;
    private readonly System.Collections.Generic.List<fg.RecipeIo> _dataList;
    
    public TbRecipeIo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fg.RecipeIo>(n);
        _dataList = new System.Collections.Generic.List<fg.RecipeIo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RecipeIo _v;
            _v = global::GameConfig.fg.RecipeIo.DeserializeRecipeIo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fg.RecipeIo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RecipeIo> DataList => _dataList;

    public fg.RecipeIo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RecipeIo Get(int key) => _dataMap[key];
    public fg.RecipeIo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

