
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 研发分支
/// </summary>
public partial class TbResearchBranch
{
    private readonly System.Collections.Generic.Dictionary<string, fg.ResearchBranch> _dataMap;
    private readonly System.Collections.Generic.List<fg.ResearchBranch> _dataList;
    
    public TbResearchBranch(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.ResearchBranch>(n);
        _dataList = new System.Collections.Generic.List<fg.ResearchBranch>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.ResearchBranch _v;
            _v = global::GameConfig.fg.ResearchBranch.DeserializeResearchBranch(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.ResearchBranch> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.ResearchBranch> DataList => _dataList;

    public fg.ResearchBranch GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.ResearchBranch Get(string key) => _dataMap[key];
    public fg.ResearchBranch this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

