
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 研发节点
/// </summary>
public partial class TbResearchNode
{
    private readonly System.Collections.Generic.Dictionary<string, fg.ResearchNode> _dataMap;
    private readonly System.Collections.Generic.List<fg.ResearchNode> _dataList;
    
    public TbResearchNode(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.ResearchNode>(n);
        _dataList = new System.Collections.Generic.List<fg.ResearchNode>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.ResearchNode _v;
            _v = global::GameConfig.fg.ResearchNode.DeserializeResearchNode(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.ResearchNode> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.ResearchNode> DataList => _dataList;

    public fg.ResearchNode GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.ResearchNode Get(string key) => _dataMap[key];
    public fg.ResearchNode this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

