
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 已移除内容
/// </summary>
public partial class TbRemovedContent
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RemovedContent> _dataMap;
    private readonly System.Collections.Generic.List<fg.RemovedContent> _dataList;
    
    public TbRemovedContent(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RemovedContent>(n);
        _dataList = new System.Collections.Generic.List<fg.RemovedContent>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RemovedContent _v;
            _v = global::GameConfig.fg.RemovedContent.DeserializeRemovedContent(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RemovedContent> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RemovedContent> DataList => _dataList;

    public fg.RemovedContent GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RemovedContent Get(string key) => _dataMap[key];
    public fg.RemovedContent this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

