
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 机器岗位
/// </summary>
public partial class TbRosterRole
{
    private readonly System.Collections.Generic.Dictionary<string, fg.RosterRole> _dataMap;
    private readonly System.Collections.Generic.List<fg.RosterRole> _dataList;
    
    public TbRosterRole(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.RosterRole>(n);
        _dataList = new System.Collections.Generic.List<fg.RosterRole>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.RosterRole _v;
            _v = global::GameConfig.fg.RosterRole.DeserializeRosterRole(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.RosterRole> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.RosterRole> DataList => _dataList;

    public fg.RosterRole GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.RosterRole Get(string key) => _dataMap[key];
    public fg.RosterRole this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

