
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 护盾状态机
/// </summary>
public partial class TbShieldState
{
    private readonly System.Collections.Generic.Dictionary<string, fg.ShieldState> _dataMap;
    private readonly System.Collections.Generic.List<fg.ShieldState> _dataList;
    
    public TbShieldState(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.ShieldState>(n);
        _dataList = new System.Collections.Generic.List<fg.ShieldState>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.ShieldState _v;
            _v = global::GameConfig.fg.ShieldState.DeserializeShieldState(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.ShieldState> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.ShieldState> DataList => _dataList;

    public fg.ShieldState GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.ShieldState Get(string key) => _dataMap[key];
    public fg.ShieldState this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

