
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城单位参数
/// </summary>
public partial class TbSiegeUnit
{
    private readonly System.Collections.Generic.Dictionary<string, fg.SiegeUnit> _dataMap;
    private readonly System.Collections.Generic.List<fg.SiegeUnit> _dataList;
    
    public TbSiegeUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.SiegeUnit>(n);
        _dataList = new System.Collections.Generic.List<fg.SiegeUnit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.SiegeUnit _v;
            _v = global::GameConfig.fg.SiegeUnit.DeserializeSiegeUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.EnemyTypeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.SiegeUnit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.SiegeUnit> DataList => _dataList;

    public fg.SiegeUnit GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.SiegeUnit Get(string key) => _dataMap[key];
    public fg.SiegeUnit this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

