
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城职能目标
/// </summary>
public partial class TbSiegeTarget
{
    private readonly System.Collections.Generic.Dictionary<string, fg.SiegeTarget> _dataMap;
    private readonly System.Collections.Generic.List<fg.SiegeTarget> _dataList;
    
    public TbSiegeTarget(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.SiegeTarget>(n);
        _dataList = new System.Collections.Generic.List<fg.SiegeTarget>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.SiegeTarget _v;
            _v = global::GameConfig.fg.SiegeTarget.DeserializeSiegeTarget(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.SiegeTarget> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.SiegeTarget> DataList => _dataList;

    public fg.SiegeTarget GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.SiegeTarget Get(string key) => _dataMap[key];
    public fg.SiegeTarget this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

