
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 攻城职能
/// </summary>
public partial class TbSiegeRole
{
    private readonly System.Collections.Generic.Dictionary<string, fg.SiegeRole> _dataMap;
    private readonly System.Collections.Generic.List<fg.SiegeRole> _dataList;
    
    public TbSiegeRole(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.SiegeRole>(n);
        _dataList = new System.Collections.Generic.List<fg.SiegeRole>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.SiegeRole _v;
            _v = global::GameConfig.fg.SiegeRole.DeserializeSiegeRole(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Role, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.SiegeRole> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.SiegeRole> DataList => _dataList;

    public fg.SiegeRole GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.SiegeRole Get(string key) => _dataMap[key];
    public fg.SiegeRole this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

