
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 状态标签
/// </summary>
public partial class TbStatusTag
{
    private readonly System.Collections.Generic.Dictionary<string, fg.StatusTag> _dataMap;
    private readonly System.Collections.Generic.List<fg.StatusTag> _dataList;
    
    public TbStatusTag(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.StatusTag>(n);
        _dataList = new System.Collections.Generic.List<fg.StatusTag>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.StatusTag _v;
            _v = global::GameConfig.fg.StatusTag.DeserializeStatusTag(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.StatusTag> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.StatusTag> DataList => _dataList;

    public fg.StatusTag GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.StatusTag Get(string key) => _dataMap[key];
    public fg.StatusTag this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

