
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 开局布局
/// </summary>
public partial class TbStartLayout
{
    private readonly System.Collections.Generic.Dictionary<string, fg.StartLayout> _dataMap;
    private readonly System.Collections.Generic.List<fg.StartLayout> _dataList;
    
    public TbStartLayout(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.StartLayout>(n);
        _dataList = new System.Collections.Generic.List<fg.StartLayout>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.StartLayout _v;
            _v = global::GameConfig.fg.StartLayout.DeserializeStartLayout(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AnchorId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.StartLayout> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.StartLayout> DataList => _dataList;

    public fg.StartLayout GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.StartLayout Get(string key) => _dataMap[key];
    public fg.StartLayout this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

