
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 表面
/// </summary>
public partial class TbSurface
{
    private readonly System.Collections.Generic.Dictionary<string, fg.Surface> _dataMap;
    private readonly System.Collections.Generic.List<fg.Surface> _dataList;
    
    public TbSurface(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.Surface>(n);
        _dataList = new System.Collections.Generic.List<fg.Surface>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.Surface _v;
            _v = global::GameConfig.fg.Surface.DeserializeSurface(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.Surface> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.Surface> DataList => _dataList;

    public fg.Surface GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.Surface Get(string key) => _dataMap[key];
    public fg.Surface this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

