
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 领地规划
/// </summary>
public partial class TbTerritory
{
    private readonly System.Collections.Generic.Dictionary<string, fg.Territory> _dataMap;
    private readonly System.Collections.Generic.List<fg.Territory> _dataList;
    
    public TbTerritory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.Territory>(n);
        _dataList = new System.Collections.Generic.List<fg.Territory>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.Territory _v;
            _v = global::GameConfig.fg.Territory.DeserializeTerritory(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.Territory> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.Territory> DataList => _dataList;

    public fg.Territory GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.Territory Get(string key) => _dataMap[key];
    public fg.Territory this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

