
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 陷阱参数
/// </summary>
public partial class TbTrapProfile
{
    private readonly System.Collections.Generic.Dictionary<string, fg.TrapProfile> _dataMap;
    private readonly System.Collections.Generic.List<fg.TrapProfile> _dataList;
    
    public TbTrapProfile(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.TrapProfile>(n);
        _dataList = new System.Collections.Generic.List<fg.TrapProfile>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.TrapProfile _v;
            _v = global::GameConfig.fg.TrapProfile.DeserializeTrapProfile(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FirmwareId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.TrapProfile> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.TrapProfile> DataList => _dataList;

    public fg.TrapProfile GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.TrapProfile Get(string key) => _dataMap[key];
    public fg.TrapProfile this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

