
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 炮塔目标模式
/// </summary>
public partial class TbTurretTargetMode
{
    private readonly System.Collections.Generic.Dictionary<string, fg.TurretTargetMode> _dataMap;
    private readonly System.Collections.Generic.List<fg.TurretTargetMode> _dataList;
    
    public TbTurretTargetMode(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.TurretTargetMode>(n);
        _dataList = new System.Collections.Generic.List<fg.TurretTargetMode>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.TurretTargetMode _v;
            _v = global::GameConfig.fg.TurretTargetMode.DeserializeTurretTargetMode(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.TurretTargetMode> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.TurretTargetMode> DataList => _dataList;

    public fg.TurretTargetMode GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.TurretTargetMode Get(string key) => _dataMap[key];
    public fg.TurretTargetMode this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

