
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 界面调参
/// </summary>
public partial class TbUiTuning
{
    private readonly System.Collections.Generic.Dictionary<string, fg.UiTuning> _dataMap;
    private readonly System.Collections.Generic.List<fg.UiTuning> _dataList;
    
    public TbUiTuning(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.UiTuning>(n);
        _dataList = new System.Collections.Generic.List<fg.UiTuning>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.UiTuning _v;
            _v = global::GameConfig.fg.UiTuning.DeserializeUiTuning(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.UiTuning> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.UiTuning> DataList => _dataList;

    public fg.UiTuning GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.UiTuning Get(string key) => _dataMap[key];
    public fg.UiTuning this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

