
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 起始区平地快照
/// </summary>
public partial class TbWorldStartClear
{
    private readonly System.Collections.Generic.Dictionary<string, fg.WorldStartClear> _dataMap;
    private readonly System.Collections.Generic.List<fg.WorldStartClear> _dataList;
    
    public TbWorldStartClear(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.WorldStartClear>(n);
        _dataList = new System.Collections.Generic.List<fg.WorldStartClear>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.WorldStartClear _v;
            _v = global::GameConfig.fg.WorldStartClear.DeserializeWorldStartClear(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.WorldStartClear> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.WorldStartClear> DataList => _dataList;

    public fg.WorldStartClear GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.WorldStartClear Get(string key) => _dataMap[key];
    public fg.WorldStartClear this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

