
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 起始区资源保证
/// </summary>
public partial class TbWorldStartGuarantee
{
    private readonly System.Collections.Generic.Dictionary<string, fg.WorldStartGuarantee> _dataMap;
    private readonly System.Collections.Generic.List<fg.WorldStartGuarantee> _dataList;
    
    public TbWorldStartGuarantee(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.WorldStartGuarantee>(n);
        _dataList = new System.Collections.Generic.List<fg.WorldStartGuarantee>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.WorldStartGuarantee _v;
            _v = global::GameConfig.fg.WorldStartGuarantee.DeserializeWorldStartGuarantee(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.WorldStartGuarantee> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.WorldStartGuarantee> DataList => _dataList;

    public fg.WorldStartGuarantee GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.WorldStartGuarantee Get(string key) => _dataMap[key];
    public fg.WorldStartGuarantee this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

