
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 世界设置预设
/// </summary>
public partial class TbWorldPreset
{
    private readonly System.Collections.Generic.Dictionary<string, fg.WorldPreset> _dataMap;
    private readonly System.Collections.Generic.List<fg.WorldPreset> _dataList;
    
    public TbWorldPreset(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.WorldPreset>(n);
        _dataList = new System.Collections.Generic.List<fg.WorldPreset>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.WorldPreset _v;
            _v = global::GameConfig.fg.WorldPreset.DeserializeWorldPreset(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.WorldPreset> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.WorldPreset> DataList => _dataList;

    public fg.WorldPreset GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.WorldPreset Get(string key) => _dataMap[key];
    public fg.WorldPreset this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

