
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 分项世界设置
/// </summary>
public partial class TbWorldSettingAxis
{
    private readonly System.Collections.Generic.Dictionary<string, fg.WorldSettingAxis> _dataMap;
    private readonly System.Collections.Generic.List<fg.WorldSettingAxis> _dataList;
    
    public TbWorldSettingAxis(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, fg.WorldSettingAxis>(n);
        _dataList = new System.Collections.Generic.List<fg.WorldSettingAxis>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fg.WorldSettingAxis _v;
            _v = global::GameConfig.fg.WorldSettingAxis.DeserializeWorldSettingAxis(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, fg.WorldSettingAxis> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fg.WorldSettingAxis> DataList => _dataList;

    public fg.WorldSettingAxis GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fg.WorldSettingAxis Get(string key) => _dataMap[key];
    public fg.WorldSettingAxis this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

