
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 陷阱参数
/// </summary>
public sealed partial class TrapProfile : Luban.BeanBase
{
    public TrapProfile(ByteBuf _buf) 
    {
        FirmwareId = _buf.ReadString();
        Tag = _buf.ReadString();
        Fluid = _buf.ReadString();
        LitersPerLay = _buf.ReadFloat();
        Dps = _buf.ReadFloat();
        NameKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static TrapProfile DeserializeTrapProfile(ByteBuf _buf)
    {
        return new fg.TrapProfile(_buf);
    }

    /// <summary>
    /// 常规固件ID(fg.TbFirmwareKind.id;混合固件不登记 = 不能装进陷阱发射器)
    /// </summary>
    public readonly string FirmwareId;
    /// <summary>
    /// 铺出的场地挂的状态标签(fg.TbStatusTag 主标签,与固件的标签一致)
    /// </summary>
    public readonly string Tag;
    /// <summary>
    /// 每轮消耗的流体键(fg.TbFluid.key;none = 只用电)
    /// </summary>
    public readonly string Fluid;
    /// <summary>
    /// 每轮消耗(升;fluid=none 时 0)
    /// </summary>
    public readonly float LitersPerLay;
    /// <summary>
    /// 场地本身每秒伤害(0 = 只挂标签,作反应底料)
    /// </summary>
    public readonly float Dps;
    /// <summary>
    /// 场地名文本键(面板 / 状态行:油膜带、冷却液带、电磁场……)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 面板下拉排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -335969297;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "firmwareId:" + FirmwareId + ","
        + "tag:" + Tag + ","
        + "fluid:" + Fluid + ","
        + "litersPerLay:" + LitersPerLay + ","
        + "dps:" + Dps + ","
        + "nameKey:" + NameKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

