
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 炮塔流体消耗
/// </summary>
public sealed partial class TurretFluid : Luban.BeanBase
{
    public TurretFluid(ByteBuf _buf) 
    {
        FirmwareId = _buf.ReadString();
        Fluid = _buf.ReadString();
        LitersPerShot = _buf.ReadFloat();
    }

    public static TurretFluid DeserializeTurretFluid(ByteBuf _buf)
    {
        return new fg.TurretFluid(_buf);
    }

    /// <summary>
    /// 流体类固件ID(fg.TbFirmwareKind.id,category=fluid;混合固件按两个来源各自的行相加,不在本表)
    /// </summary>
    public readonly string FirmwareId;
    /// <summary>
    /// 消耗的流体键(fg.TbFluid.key)
    /// </summary>
    public readonly string Fluid;
    /// <summary>
    /// 每发消耗(升),&gt;0
    /// </summary>
    public readonly float LitersPerShot;
   
    public const int __ID__ = -919518995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "firmwareId:" + FirmwareId + ","
        + "fluid:" + Fluid + ","
        + "litersPerShot:" + LitersPerShot + ","
        + "}";
    }
}
}

