
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 炮塔参数
/// </summary>
public sealed partial class TurretProfile : Luban.BeanBase
{
    public TurretProfile(ByteBuf _buf) 
    {
        ComponentId = _buf.ReadString();
        Size = _buf.ReadString();
        Range = _buf.ReadFloat();
        TurnRate = _buf.ReadFloat();
        ProjectileSpeed = _buf.ReadFloat();
        ProjectileRadius = _buf.ReadFloat();
    }

    public static TurretProfile DeserializeTurretProfile(ByteBuf _buf)
    {
        return new fg.TurretProfile(_buf);
    }

    /// <summary>
    /// 主作战组件ID(fg.TbCombatComponent.id,slot=main 且炮塔兼容)
    /// </summary>
    public readonly string ComponentId;
    /// <summary>
    /// 炮塔座:light=轻型 2&#215;2 / heavy=重型 3&#215;3(FG06 第 10 节;决定放成哪种炮塔座)
    /// </summary>
    public readonly string Size;
    /// <summary>
    /// 射程(米;T1,T2/T3 乘等级效果值;格斗 / 力场仍按触及收紧)
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// 转速(度/游戏秒;0=不需要转向:力场、无人机、环扫)
    /// </summary>
    public readonly float TurnRate;
    /// <summary>
    /// 弹速(米/秒;&gt;0 = 打真实飞行弹体,只给射弹载体;0 = 沿用机器的即时投送)
    /// </summary>
    public readonly float ProjectileSpeed;
    /// <summary>
    /// 弹体半径(米;弹速为 0 时填 0)
    /// </summary>
    public readonly float ProjectileRadius;
   
    public const int __ID__ = 1556763660;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "componentId:" + ComponentId + ","
        + "size:" + Size + ","
        + "range:" + Range + ","
        + "turnRate:" + TurnRate + ","
        + "projectileSpeed:" + ProjectileSpeed + ","
        + "projectileRadius:" + ProjectileRadius + ","
        + "}";
    }
}
}

