
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 炮塔目标模式
/// </summary>
public sealed partial class TurretTargetMode : Luban.BeanBase
{
    public TurretTargetMode(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Code = _buf.ReadInt();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static TurretTargetMode DeserializeTurretTargetMode(ByteBuf _buf)
    {
        return new fg.TurretTargetMode(_buf);
    }

    /// <summary>
    /// 模式ID(存档存 code,不存它)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 内核 CombatTargetMode 的值:0 最近 / 1 最低耐久 / 2 最高威胁 / 3 精英优先 / 4 优先打正在破坏建筑的敌人
    /// </summary>
    public readonly int Code;
    /// <summary>
    /// 名称文本键
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 说明文本键(悬停 / 面板写明怎么选目标)
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 面板上的排序(按 FG06 FGR-DEF-003 的列举顺序)
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 2078467473;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "nameKey:" + NameKey + ","
        + "descKey:" + DescKey + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

