
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 世界设置预设
/// </summary>
public sealed partial class WorldPreset : Luban.BeanBase
{
    public WorldPreset(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Set = _buf.ReadString();
        Id = _buf.ReadString();
        NameKey = _buf.ReadString();
        ResourceAbundance = _buf.ReadFloat();
        PollutionIntensity = _buf.ReadFloat();
        TerritoryDistanceScale = _buf.ReadFloat();
        StartZone = _buf.ReadString();
    }

    public static WorldPreset DeserializeWorldPreset(ByteBuf _buf)
    {
        return new fg.WorldPreset(_buf);
    }

    /// <summary>
    /// 主键=集合.预设ID(如 p1.default)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 集合(由生成器版本行 presetSet 引用;已发布集合禁止改)
    /// </summary>
    public readonly string Set;
    /// <summary>
    /// 预设ID(存档 WorldGenState.WorldSettingsId)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 资源丰度:矿脉出现概率倍率(1=标准)
    /// </summary>
    public readonly float ResourceAbundance;
    /// <summary>
    /// 污染强度:距离污染增长倍率(1=标准)
    /// </summary>
    public readonly float PollutionIntensity;
    /// <summary>
    /// 领地距离:按比例缩放领地中心离核心的距离(1=标准)
    /// </summary>
    public readonly float TerritoryDistanceScale;
    /// <summary>
    /// 起始区:standard/relaxed(宽松=保护半径&#215;1.5)
    /// </summary>
    public readonly string StartZone;
   
    public const int __ID__ = -286013628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "set:" + Set + ","
        + "id:" + Id + ","
        + "nameKey:" + NameKey + ","
        + "resourceAbundance:" + ResourceAbundance + ","
        + "pollutionIntensity:" + PollutionIntensity + ","
        + "territoryDistanceScale:" + TerritoryDistanceScale + ","
        + "startZone:" + StartZone + ","
        + "}";
    }
}
}

