
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 起始区资源保证
/// </summary>
public sealed partial class WorldStartGuarantee : Luban.BeanBase
{
    public WorldStartGuarantee(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Set = _buf.ReadString();
        Item = _buf.ReadString();
        Terrain = _buf.ReadString();
        Radius = _buf.ReadInt();
        MinCells = _buf.ReadInt();
        MinSquare = _buf.ReadInt();
        StampRadius = _buf.ReadInt();
        NameKey = _buf.ReadString();
    }

    public static WorldStartGuarantee DeserializeWorldStartGuarantee(ByteBuf _buf)
    {
        return new fg.WorldStartGuarantee(_buf);
    }

    /// <summary>
    /// 主键=集合.项(如 g2.water)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 集合(由生成器版本行 guaranteeSet 引用;已发布集合禁止改,行序也不能改)
    /// </summary>
    public readonly string Set;
    /// <summary>
    /// 保证项ID
    /// </summary>
    public readonly string Item;
    /// <summary>
    /// 地形ID(fg.TbGridTerrain)
    /// </summary>
    public readonly string Terrain;
    /// <summary>
    /// 核心半径(格,欧氏)
    /// </summary>
    public readonly int Radius;
    /// <summary>
    /// 连通区至少多少格(只数圆内)
    /// </summary>
    public readonly int MinCells;
    /// <summary>
    /// 连通区里至少有一个多大的整块(边长,格)
    /// </summary>
    public readonly int MinSquare;
    /// <summary>
    /// 不满足时放置的保证点半径(格);圆盘必须装得下 minSquare 整块且不少于 minCells 格
    /// </summary>
    public readonly int StampRadius;
    /// <summary>
    /// 名称文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
   
    public const int __ID__ = 1021155243;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "set:" + Set + ","
        + "item:" + Item + ","
        + "terrain:" + Terrain + ","
        + "radius:" + Radius + ","
        + "minCells:" + MinCells + ","
        + "minSquare:" + MinSquare + ","
        + "stampRadius:" + StampRadius + ","
        + "nameKey:" + NameKey + ","
        + "}";
    }
}
}

