
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 分项世界设置
/// </summary>
public sealed partial class WorldSettingAxis : Luban.BeanBase
{
    public WorldSettingAxis(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Set = _buf.ReadString();
        Axis = _buf.ReadString();
        Level = _buf.ReadInt();
        LevelId = _buf.ReadString();
        IsDefault = _buf.ReadInt();
        NameKey = _buf.ReadString();
        Value = _buf.ReadFloat();
    }

    public static WorldSettingAxis DeserializeWorldSettingAxis(ByteBuf _buf)
    {
        return new fg.WorldSettingAxis(_buf);
    }

    /// <summary>
    /// 主键=集合.分项.档(如 a2.resource.1)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 集合(由生成器版本行 settingSet 引用;已发布集合禁止改)
    /// </summary>
    public readonly string Set;
    /// <summary>
    /// 分项:resource/outposts/pollution/distance/start
    /// </summary>
    public readonly string Axis;
    /// <summary>
    /// 档(0起连续;标准档见 isDefault)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 档ID(low/standard/high/near/far/relaxed)
    /// </summary>
    public readonly string LevelId;
    /// <summary>
    /// 1=标准档(新游戏默认,分项代码 default 的取值)
    /// </summary>
    public readonly int IsDefault;
    /// <summary>
    /// 档名文本键(fg.TbLocText)
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 倍率(含义见上)
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -1218980660;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "set:" + Set + ","
        + "axis:" + Axis + ","
        + "level:" + Level + ","
        + "levelId:" + LevelId + ","
        + "isDefault:" + IsDefault + ","
        + "nameKey:" + NameKey + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

