
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 起始区平地快照
/// </summary>
public sealed partial class WorldStartClear : Luban.BeanBase
{
    public WorldStartClear(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Set = _buf.ReadString();
        Variant = _buf.ReadString();
        Idx = _buf.ReadInt();
        MinX = _buf.ReadInt();
        MinY = _buf.ReadInt();
        MaxX = _buf.ReadInt();
        MaxY = _buf.ReadInt();
    }

    public static WorldStartClear DeserializeWorldStartClear(ByteBuf _buf)
    {
        return new fg.WorldStartClear(_buf);
    }

    /// <summary>
    /// 主键=集合.变体.序号(如 c1.standard.0)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 集合(由生成器版本行 startClearSet 引用;已发布集合禁止改)
    /// </summary>
    public readonly string Set;
    /// <summary>
    /// standard/relaxed(v1 宽松起始区=保护半径&#215;1.5;v2 两种起始区都用 standard,宽松改为放大保证半径)
    /// </summary>
    public readonly string Variant;
    /// <summary>
    /// 序号(从0连续)
    /// </summary>
    public readonly int Idx;
    /// <summary>
    /// 相对核心的最小x(格)
    /// </summary>
    public readonly int MinX;
    /// <summary>
    /// 相对核心的最小y(格)
    /// </summary>
    public readonly int MinY;
    /// <summary>
    /// 相对核心的最大x(格)
    /// </summary>
    public readonly int MaxX;
    /// <summary>
    /// 相对核心的最大y(格)
    /// </summary>
    public readonly int MaxY;
   
    public const int __ID__ = 2106169584;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "set:" + Set + ","
        + "variant:" + Variant + ","
        + "idx:" + Idx + ","
        + "minX:" + MinX + ","
        + "minY:" + MinY + ","
        + "maxX:" + MaxX + ","
        + "maxY:" + MaxY + ","
        + "}";
    }
}
}

