
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fg
{
/// <summary>
/// 生成器版本
/// </summary>
public sealed partial class WorldGenVersion : Luban.BeanBase
{
    public WorldGenVersion(ByteBuf _buf) 
    {
        Version = _buf.ReadInt();
        FeatureScale = _buf.ReadFloat();
        CliffThreshold = _buf.ReadFloat();
        WaterThreshold = _buf.ReadFloat();
        OreThreshold = _buf.ReadFloat();
        RareBias = _buf.ReadFloat();
        OilBias = _buf.ReadFloat();
        PollutionThreshold = _buf.ReadFloat();
        PollutionScale = _buf.ReadFloat();
        PollutionDistanceStart = _buf.ReadInt();
        PollutionDistancePerLevel = _buf.ReadInt();
        ResourceDistancePerStep = _buf.ReadInt();
        ResourceDistanceStep = _buf.ReadFloat();
        ResourceDistanceMaxSteps = _buf.ReadInt();
        TerritoryPollutionBonus = _buf.ReadInt();
        HazardPollution = _buf.ReadInt();
        ProtectRadius = _buf.ReadInt();
        ProtectMargin = _buf.ReadInt();
        AnchorProtectRadius = _buf.ReadInt();
        InteriorPillarSpacing = _buf.ReadInt();
        InteriorRuinThreshold = _buf.ReadFloat();
        HomeZoneRadius = _buf.ReadInt();
        TerritoryMinAngle = _buf.ReadInt();
        PlanMaxAttempts = _buf.ReadInt();
        TerritorySet = _buf.ReadString();
        PresetSet = _buf.ReadString();
        Note = _buf.ReadString();
    }

    public static WorldGenVersion DeserializeWorldGenVersion(ByteBuf _buf)
    {
        return new fg.WorldGenVersion(_buf);
    }

    /// <summary>
    /// 生成器版本(主键),从1连续编号;已发布的行禁止改动(回归哈希守护)
    /// </summary>
    public readonly int Version;
    /// <summary>
    /// 地形特征格距(格),越大地形块越大
    /// </summary>
    public readonly float FeatureScale;
    /// <summary>
    /// 悬崖噪声阈值(0~1,越大越少)
    /// </summary>
    public readonly float CliffThreshold;
    /// <summary>
    /// 水源噪声阈值
    /// </summary>
    public readonly float WaterThreshold;
    /// <summary>
    /// 金属矿脉/废墟噪声阈值
    /// </summary>
    public readonly float OreThreshold;
    /// <summary>
    /// 稀土阈值=矿阈值+(1-矿阈值)&#215;该值
    /// </summary>
    public readonly float RareBias;
    /// <summary>
    /// 油井阈值=矿阈值+(1-矿阈值)&#215;该值
    /// </summary>
    public readonly float OilBias;
    /// <summary>
    /// 污染噪声阈值,超出部分按比例分成1~3级
    /// </summary>
    public readonly float PollutionThreshold;
    /// <summary>
    /// 污染噪声格距=特征格距&#215;该值
    /// </summary>
    public readonly float PollutionScale;
    /// <summary>
    /// 离核心多少格起污染随距离上升(FGR-GEN-030)
    /// </summary>
    public readonly int PollutionDistanceStart;
    /// <summary>
    /// 超出起点后每多少格污染+1级
    /// </summary>
    public readonly int PollutionDistancePerLevel;
    /// <summary>
    /// 离核心每多少格矿阈值下降一档(越远越丰富,FGR-GEN-032)
    /// </summary>
    public readonly int ResourceDistancePerStep;
    /// <summary>
    /// 每档矿阈值下降量
    /// </summary>
    public readonly float ResourceDistanceStep;
    /// <summary>
    /// 矿阈值最多下降几档
    /// </summary>
    public readonly int ResourceDistanceMaxSteps;
    /// <summary>
    /// 阵营领地内部污染+级(越靠中心越接近阵营风格)
    /// </summary>
    public readonly int TerritoryPollutionBonus;
    /// <summary>
    /// 领地外圈危害带的污染等级(1~3)
    /// </summary>
    public readonly int HazardPollution;
    /// <summary>
    /// 核心周围强制为可建空地的半径(格,切比雪夫距离)
    /// </summary>
    public readonly int ProtectRadius;
    /// <summary>
    /// 开局布局每个建筑/建造位占地外强制为空地的圈数(格)
    /// </summary>
    public readonly int ProtectMargin;
    /// <summary>
    /// 非建筑锚点(出生点、残骸……)周围强制为空地的半径(格)
    /// </summary>
    public readonly int AnchorProtectRadius;
    /// <summary>
    /// 室内表面立柱间距(格),&gt;=4
    /// </summary>
    public readonly int InteriorPillarSpacing;
    /// <summary>
    /// 室内表面废墟噪声阈值
    /// </summary>
    public readonly float InteriorRuinThreshold;
    /// <summary>
    /// 家园区半径(格):规划层不把任何领地放进去(FGR-GEN-021)
    /// </summary>
    public readonly int HomeZoneRadius;
    /// <summary>
    /// 四个阵营领地方向两两最小夹角(度),FGR-GEN-021
    /// </summary>
    public readonly int TerritoryMinAngle;
    /// <summary>
    /// 规划层单个领地的确定性重试次数上限(FGR-GEN-090 局部重生成)
    /// </summary>
    public readonly int PlanMaxAttempts;
    /// <summary>
    /// 本版本使用的领地集合(fg.TbTerritory 的 set);已发布集合禁止改
    /// </summary>
    public readonly string TerritorySet;
    /// <summary>
    /// 本版本使用的世界设置集合(fg.TbWorldPreset 的 set);已发布集合禁止改
    /// </summary>
    public readonly string PresetSet;
    /// <summary>
    /// 这一版改了什么
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -1068010163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "version:" + Version + ","
        + "featureScale:" + FeatureScale + ","
        + "cliffThreshold:" + CliffThreshold + ","
        + "waterThreshold:" + WaterThreshold + ","
        + "oreThreshold:" + OreThreshold + ","
        + "rareBias:" + RareBias + ","
        + "oilBias:" + OilBias + ","
        + "pollutionThreshold:" + PollutionThreshold + ","
        + "pollutionScale:" + PollutionScale + ","
        + "pollutionDistanceStart:" + PollutionDistanceStart + ","
        + "pollutionDistancePerLevel:" + PollutionDistancePerLevel + ","
        + "resourceDistancePerStep:" + ResourceDistancePerStep + ","
        + "resourceDistanceStep:" + ResourceDistanceStep + ","
        + "resourceDistanceMaxSteps:" + ResourceDistanceMaxSteps + ","
        + "territoryPollutionBonus:" + TerritoryPollutionBonus + ","
        + "hazardPollution:" + HazardPollution + ","
        + "protectRadius:" + ProtectRadius + ","
        + "protectMargin:" + ProtectMargin + ","
        + "anchorProtectRadius:" + AnchorProtectRadius + ","
        + "interiorPillarSpacing:" + InteriorPillarSpacing + ","
        + "interiorRuinThreshold:" + InteriorRuinThreshold + ","
        + "homeZoneRadius:" + HomeZoneRadius + ","
        + "territoryMinAngle:" + TerritoryMinAngle + ","
        + "planMaxAttempts:" + PlanMaxAttempts + ","
        + "territorySet:" + TerritorySet + ","
        + "presetSet:" + PresetSet + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

