
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    /// <summary>
    /// 主动技能
    /// </summary>
    public cell.TbAbility TbAbility {get; }
    /// <summary>
    /// 技能效果
    /// </summary>
    public cell.TbAbilityEffect TbAbilityEffect {get; }
    /// <summary>
    /// 词缀
    /// </summary>
    public cell.TbAffix TbAffix {get; }
    /// <summary>
    /// 行为原型
    /// </summary>
    public cell.TbBehaviorArchetype TbBehaviorArchetype {get; }
    /// <summary>
    /// 首领阶段
    /// </summary>
    public cell.TbBossPhase TbBossPhase {get; }
    /// <summary>
    /// 卡牌
    /// </summary>
    public cell.TbCard TbCard {get; }
    /// <summary>
    /// 卡牌效果
    /// </summary>
    public cell.TbCardEffect TbCardEffect {get; }
    /// <summary>
    /// 卡牌属性修正
    /// </summary>
    public cell.TbCardStat TbCardStat {get; }
    /// <summary>
    /// 敌人配置
    /// </summary>
    public cell.TbCellEnemy TbCellEnemy {get; }
    /// <summary>
    /// 全局常量
    /// </summary>
    public cell.TbCellGlobal TbCellGlobal {get; }
    /// <summary>
    /// 生态事件
    /// </summary>
    public cell.TbEcoEvent TbEcoEvent {get; }
    /// <summary>
    /// 升级曲线
    /// </summary>
    public cell.TbLevelCurve TbLevelCurve {get; }
    /// <summary>
    /// 生态时期
    /// </summary>
    public cell.TbPhase TbPhase {get; }
    /// <summary>
    /// 压力曲线
    /// </summary>
    public cell.TbPressureCurve TbPressureCurve {get; }
    /// <summary>
    /// 状态效果
    /// </summary>
    public cell.TbStatusEffect TbStatusEffect {get; }
    /// <summary>
    /// 细胞阶段场地与时间轴
    /// </summary>
    public fp.TbCellArena TbCellArena {get; }
    /// <summary>
    /// 生物阶段场地与时间轴
    /// </summary>
    public fp.TbCreatureArena TbCreatureArena {get; }
    /// <summary>
    /// 敌人配置
    /// </summary>
    public fp.TbEnemy TbEnemy {get; }
    /// <summary>
    /// 敌人技能
    /// </summary>
    public fp.TbEnemySkill TbEnemySkill {get; }
    /// <summary>
    /// 食物配置
    /// </summary>
    public fp.TbFood TbFood {get; }
    /// <summary>
    /// FP全局公式与门槛
    /// </summary>
    public fp.TbGlobal TbGlobal {get; }
    /// <summary>
    /// 细胞微选择
    /// </summary>
    public fp.TbMicroChoice TbMicroChoice {get; }
    /// <summary>
    /// 构筑模块
    /// </summary>
    public fp.TbModule TbModule {get; }
    /// <summary>
    /// 玩家形态基础面板
    /// </summary>
    public fp.TbPlayerForm TbPlayerForm {get; }
    /// <summary>
    /// 细胞波次
    /// </summary>
    public fp.TbWave TbWave {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbAbility = new cell.TbAbility(loader("cell_tbability"));
        TbAbilityEffect = new cell.TbAbilityEffect(loader("cell_tbabilityeffect"));
        TbAffix = new cell.TbAffix(loader("cell_tbaffix"));
        TbBehaviorArchetype = new cell.TbBehaviorArchetype(loader("cell_tbbehaviorarchetype"));
        TbBossPhase = new cell.TbBossPhase(loader("cell_tbbossphase"));
        TbCard = new cell.TbCard(loader("cell_tbcard"));
        TbCardEffect = new cell.TbCardEffect(loader("cell_tbcardeffect"));
        TbCardStat = new cell.TbCardStat(loader("cell_tbcardstat"));
        TbCellEnemy = new cell.TbCellEnemy(loader("cell_tbcellenemy"));
        TbCellGlobal = new cell.TbCellGlobal(loader("cell_tbcellglobal"));
        TbEcoEvent = new cell.TbEcoEvent(loader("cell_tbecoevent"));
        TbLevelCurve = new cell.TbLevelCurve(loader("cell_tblevelcurve"));
        TbPhase = new cell.TbPhase(loader("cell_tbphase"));
        TbPressureCurve = new cell.TbPressureCurve(loader("cell_tbpressurecurve"));
        TbStatusEffect = new cell.TbStatusEffect(loader("cell_tbstatuseffect"));
        TbCellArena = new fp.TbCellArena(loader("fp_tbcellarena"));
        TbCreatureArena = new fp.TbCreatureArena(loader("fp_tbcreaturearena"));
        TbEnemy = new fp.TbEnemy(loader("fp_tbenemy"));
        TbEnemySkill = new fp.TbEnemySkill(loader("fp_tbenemyskill"));
        TbFood = new fp.TbFood(loader("fp_tbfood"));
        TbGlobal = new fp.TbGlobal(loader("fp_tbglobal"));
        TbMicroChoice = new fp.TbMicroChoice(loader("fp_tbmicrochoice"));
        TbModule = new fp.TbModule(loader("fp_tbmodule"));
        TbPlayerForm = new fp.TbPlayerForm(loader("fp_tbplayerform"));
        TbWave = new fp.TbWave(loader("fp_tbwave"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbAbilityEffect.ResolveRef(this);
        TbAffix.ResolveRef(this);
        TbBehaviorArchetype.ResolveRef(this);
        TbBossPhase.ResolveRef(this);
        TbCard.ResolveRef(this);
        TbCardEffect.ResolveRef(this);
        TbCardStat.ResolveRef(this);
        TbCellEnemy.ResolveRef(this);
        TbCellGlobal.ResolveRef(this);
        TbEcoEvent.ResolveRef(this);
        TbLevelCurve.ResolveRef(this);
        TbPhase.ResolveRef(this);
        TbPressureCurve.ResolveRef(this);
        TbStatusEffect.ResolveRef(this);
        TbCellArena.ResolveRef(this);
        TbCreatureArena.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbEnemySkill.ResolveRef(this);
        TbFood.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbMicroChoice.ResolveRef(this);
        TbModule.ResolveRef(this);
        TbPlayerForm.ResolveRef(this);
        TbWave.ResolveRef(this);
    }
}

}
