
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    /// <summary>
    /// 主动技能
    /// </summary>
    public cell.TbAbility TbAbility {get; }
    /// <summary>
    /// 技能效果
    /// </summary>
    public cell.TbAbilityEffect TbAbilityEffect {get; }
    /// <summary>
    /// 词缀
    /// </summary>
    public cell.TbAffix TbAffix {get; }
    /// <summary>
    /// 行为原型
    /// </summary>
    public cell.TbBehaviorArchetype TbBehaviorArchetype {get; }
    /// <summary>
    /// 首领阶段
    /// </summary>
    public cell.TbBossPhase TbBossPhase {get; }
    /// <summary>
    /// 卡牌
    /// </summary>
    public cell.TbCard TbCard {get; }
    /// <summary>
    /// 卡牌效果
    /// </summary>
    public cell.TbCardEffect TbCardEffect {get; }
    /// <summary>
    /// 卡牌属性修正
    /// </summary>
    public cell.TbCardStat TbCardStat {get; }
    /// <summary>
    /// 敌人配置
    /// </summary>
    public cell.TbCellEnemy TbCellEnemy {get; }
    /// <summary>
    /// 全局常量
    /// </summary>
    public cell.TbCellGlobal TbCellGlobal {get; }
    /// <summary>
    /// 生态事件
    /// </summary>
    public cell.TbEcoEvent TbEcoEvent {get; }
    /// <summary>
    /// 基因模块参数
    /// </summary>
    public cell.TbGeneModuleParams TbGeneModuleParams {get; }
    /// <summary>
    /// 升级曲线
    /// </summary>
    public cell.TbLevelCurve TbLevelCurve {get; }
    /// <summary>
    /// 器官模块参数
    /// </summary>
    public cell.TbOrganModuleParams TbOrganModuleParams {get; }
    /// <summary>
    /// 生态时期
    /// </summary>
    public cell.TbPhase TbPhase {get; }
    /// <summary>
    /// 压力曲线
    /// </summary>
    public cell.TbPressureCurve TbPressureCurve {get; }
    /// <summary>
    /// 状态效果
    /// </summary>
    public cell.TbStatusEffect TbStatusEffect {get; }
    /// <summary>
    /// 结构器官常驻被动
    /// </summary>
    public cell.TbStructuralEffectParams TbStructuralEffectParams {get; }
    /// <summary>
    /// 结构器官触发钩子
    /// </summary>
    public cell.TbStructuralTriggerHookParams TbStructuralTriggerHookParams {get; }
    /// <summary>
    /// 解析种类
    /// </summary>
    public fg.TbAnalysisKind TbAnalysisKind {get; }
    /// <summary>
    /// 背景资料
    /// </summary>
    public fg.TbAnalysisLore TbAnalysisLore {get; }
    /// <summary>
    /// 机器材料
    /// </summary>
    public fg.TbAssemblyMaterial TbAssemblyMaterial {get; }
    /// <summary>
    /// 过滤器预设
    /// </summary>
    public fg.TbBeltFilterPreset TbBeltFilterPreset {get; }
    /// <summary>
    /// 建造菜单分类
    /// </summary>
    public fg.TbBuildCategory TbBuildCategory {get; }
    /// <summary>
    /// 建筑
    /// </summary>
    public fg.TbBuilding TbBuilding {get; }
    /// <summary>
    /// 建筑流体端口
    /// </summary>
    public fg.TbBuildingFluidPort TbBuildingFluidPort {get; }
    /// <summary>
    /// 建筑格网属性
    /// </summary>
    public fg.TbBuildingGrid TbBuildingGrid {get; }
    /// <summary>
    /// 建筑端口
    /// </summary>
    public fg.TbBuildingPort TbBuildingPort {get; }
    /// <summary>
    /// 建筑通用
    /// </summary>
    public fg.TbBuildingService TbBuildingService {get; }
    /// <summary>
    /// 多座建筑叠加
    /// </summary>
    public fg.TbBuildingStack TbBuildingStack {get; }
    /// <summary>
    /// 建筑等级
    /// </summary>
    public fg.TbBuildingTier TbBuildingTier {get; }
    /// <summary>
    /// 建筑材料
    /// </summary>
    public fg.TbBuildMaterial TbBuildMaterial {get; }
    /// <summary>
    /// 建造菜单工具
    /// </summary>
    public fg.TbBuildTool TbBuildTool {get; }
    /// <summary>
    /// 升级路线
    /// </summary>
    public fg.TbBuildUpgrade TbBuildUpgrade {get; }
    /// <summary>
    /// 载体读法
    /// </summary>
    public fg.TbCarrierReading TbCarrierReading {get; }
    /// <summary>
    /// 机制图鉴条目
    /// </summary>
    public fg.TbCodexEntry TbCodexEntry {get; }
    /// <summary>
    /// 作战组件
    /// </summary>
    public fg.TbCombatComponent TbCombatComponent {get; }
    /// <summary>
    /// 物品
    /// </summary>
    public fg.TbEcoItem TbEcoItem {get; }
    /// <summary>
    /// 固件种类
    /// </summary>
    public fg.TbFirmwareKind TbFirmwareKind {get; }
    /// <summary>
    /// 流体
    /// </summary>
    public fg.TbFluid TbFluid {get; }
    /// <summary>
    /// 熔合合并上限
    /// </summary>
    public fg.TbFusionMerge TbFusionMerge {get; }
    /// <summary>
    /// 熔合配方
    /// </summary>
    public fg.TbFusionRecipe TbFusionRecipe {get; }
    /// <summary>
    /// 地形类型
    /// </summary>
    public fg.TbGridTerrain TbGridTerrain {get; }
    /// <summary>
    /// 家园与格网调参
    /// </summary>
    public fg.TbHomeTuning TbHomeTuning {get; }
    /// <summary>
    /// 输入动作
    /// </summary>
    public fg.TbInputAction TbInputAction {get; }
    /// <summary>
    /// 首领弱点情报
    /// </summary>
    public fg.TbIntelBoss TbIntelBoss {get; }
    /// <summary>
    /// 舰队信号片段
    /// </summary>
    public fg.TbIntelFragment TbIntelFragment {get; }
    /// <summary>
    /// 情报类型
    /// </summary>
    public fg.TbIntelKind TbIntelKind {get; }
    /// <summary>
    /// 本地化文本
    /// </summary>
    public fg.TbLocText TbLocText {get; }
    /// <summary>
    /// 机械敌人
    /// </summary>
    public fg.TbMechEnemy TbMechEnemy {get; }
    /// <summary>
    /// 通知分级
    /// </summary>
    public fg.TbNotifyTier TbNotifyTier {get; }
    /// <summary>
    /// 通知类型
    /// </summary>
    public fg.TbNotifyType TbNotifyType {get; }
    /// <summary>
    /// 电力节点
    /// </summary>
    public fg.TbPowerNode TbPowerNode {get; }
    /// <summary>
    /// 发电类别
    /// </summary>
    public fg.TbPowerSource TbPowerSource {get; }
    /// <summary>
    /// 生产参数
    /// </summary>
    public fg.TbProducer TbProducer {get; }
    /// <summary>
    /// 靶子类型
    /// </summary>
    public fg.TbRangeTarget TbRangeTarget {get; }
    /// <summary>
    /// 具名反应
    /// </summary>
    public fg.TbReaction TbReaction {get; }
    /// <summary>
    /// 配方
    /// </summary>
    public fg.TbRecipe TbRecipe {get; }
    /// <summary>
    /// 配方行
    /// </summary>
    public fg.TbRecipeIo TbRecipeIo {get; }
    /// <summary>
    /// 已移除内容
    /// </summary>
    public fg.TbRemovedContent TbRemovedContent {get; }
    /// <summary>
    /// 研发分支
    /// </summary>
    public fg.TbResearchBranch TbResearchBranch {get; }
    /// <summary>
    /// 研发节点
    /// </summary>
    public fg.TbResearchNode TbResearchNode {get; }
    /// <summary>
    /// 机器岗位
    /// </summary>
    public fg.TbRosterRole TbRosterRole {get; }
    /// <summary>
    /// 规则类型
    /// </summary>
    public fg.TbRuleKind TbRuleKind {get; }
    /// <summary>
    /// 规则预设
    /// </summary>
    public fg.TbRulePreset TbRulePreset {get; }
    /// <summary>
    /// 护盾状态机
    /// </summary>
    public fg.TbShieldState TbShieldState {get; }
    /// <summary>
    /// 开局布局
    /// </summary>
    public fg.TbStartLayout TbStartLayout {get; }
    /// <summary>
    /// 状态标签
    /// </summary>
    public fg.TbStatusTag TbStatusTag {get; }
    /// <summary>
    /// 表面
    /// </summary>
    public fg.TbSurface TbSurface {get; }
    /// <summary>
    /// 领地规划
    /// </summary>
    public fg.TbTerritory TbTerritory {get; }
    /// <summary>
    /// 陷阱参数
    /// </summary>
    public fg.TbTrapProfile TbTrapProfile {get; }
    /// <summary>
    /// 炮塔流体消耗
    /// </summary>
    public fg.TbTurretFluid TbTurretFluid {get; }
    /// <summary>
    /// 炮塔参数
    /// </summary>
    public fg.TbTurretProfile TbTurretProfile {get; }
    /// <summary>
    /// 炮塔目标模式
    /// </summary>
    public fg.TbTurretTargetMode TbTurretTargetMode {get; }
    /// <summary>
    /// 界面调参
    /// </summary>
    public fg.TbUiTuning TbUiTuning {get; }
    /// <summary>
    /// 生成器版本
    /// </summary>
    public fg.TbWorldGenVersion TbWorldGenVersion {get; }
    /// <summary>
    /// 世界设置预设
    /// </summary>
    public fg.TbWorldPreset TbWorldPreset {get; }
    /// <summary>
    /// 分项世界设置
    /// </summary>
    public fg.TbWorldSettingAxis TbWorldSettingAxis {get; }
    /// <summary>
    /// 起始区平地快照
    /// </summary>
    public fg.TbWorldStartClear TbWorldStartClear {get; }
    /// <summary>
    /// 起始区资源保证
    /// </summary>
    public fg.TbWorldStartGuarantee TbWorldStartGuarantee {get; }
    /// <summary>
    /// 细胞阶段场地与时间轴
    /// </summary>
    public fp.TbCellArena TbCellArena {get; }
    /// <summary>
    /// 生物阶段场地与时间轴
    /// </summary>
    public fp.TbCreatureArena TbCreatureArena {get; }
    /// <summary>
    /// 敌人配置
    /// </summary>
    public fp.TbEnemy TbEnemy {get; }
    /// <summary>
    /// 敌人技能
    /// </summary>
    public fp.TbEnemySkill TbEnemySkill {get; }
    /// <summary>
    /// 食物配置
    /// </summary>
    public fp.TbFood TbFood {get; }
    /// <summary>
    /// FP全局公式与门槛
    /// </summary>
    public fp.TbGlobal TbGlobal {get; }
    /// <summary>
    /// 细胞微选择
    /// </summary>
    public fp.TbMicroChoice TbMicroChoice {get; }
    /// <summary>
    /// 构筑模块
    /// </summary>
    public fp.TbModule TbModule {get; }
    /// <summary>
    /// 玩家形态基础面板
    /// </summary>
    public fp.TbPlayerForm TbPlayerForm {get; }
    /// <summary>
    /// 细胞波次
    /// </summary>
    public fp.TbWave TbWave {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbAbility = new cell.TbAbility(loader("cell_tbability"));
        TbAbilityEffect = new cell.TbAbilityEffect(loader("cell_tbabilityeffect"));
        TbAffix = new cell.TbAffix(loader("cell_tbaffix"));
        TbBehaviorArchetype = new cell.TbBehaviorArchetype(loader("cell_tbbehaviorarchetype"));
        TbBossPhase = new cell.TbBossPhase(loader("cell_tbbossphase"));
        TbCard = new cell.TbCard(loader("cell_tbcard"));
        TbCardEffect = new cell.TbCardEffect(loader("cell_tbcardeffect"));
        TbCardStat = new cell.TbCardStat(loader("cell_tbcardstat"));
        TbCellEnemy = new cell.TbCellEnemy(loader("cell_tbcellenemy"));
        TbCellGlobal = new cell.TbCellGlobal(loader("cell_tbcellglobal"));
        TbEcoEvent = new cell.TbEcoEvent(loader("cell_tbecoevent"));
        TbGeneModuleParams = new cell.TbGeneModuleParams(loader("cell_tbgenemoduleparams"));
        TbLevelCurve = new cell.TbLevelCurve(loader("cell_tblevelcurve"));
        TbOrganModuleParams = new cell.TbOrganModuleParams(loader("cell_tborganmoduleparams"));
        TbPhase = new cell.TbPhase(loader("cell_tbphase"));
        TbPressureCurve = new cell.TbPressureCurve(loader("cell_tbpressurecurve"));
        TbStatusEffect = new cell.TbStatusEffect(loader("cell_tbstatuseffect"));
        TbStructuralEffectParams = new cell.TbStructuralEffectParams(loader("cell_tbstructuraleffectparams"));
        TbStructuralTriggerHookParams = new cell.TbStructuralTriggerHookParams(loader("cell_tbstructuraltriggerhookparams"));
        TbAnalysisKind = new fg.TbAnalysisKind(loader("fg_tbanalysiskind"));
        TbAnalysisLore = new fg.TbAnalysisLore(loader("fg_tbanalysislore"));
        TbAssemblyMaterial = new fg.TbAssemblyMaterial(loader("fg_tbassemblymaterial"));
        TbBeltFilterPreset = new fg.TbBeltFilterPreset(loader("fg_tbbeltfilterpreset"));
        TbBuildCategory = new fg.TbBuildCategory(loader("fg_tbbuildcategory"));
        TbBuilding = new fg.TbBuilding(loader("fg_tbbuilding"));
        TbBuildingFluidPort = new fg.TbBuildingFluidPort(loader("fg_tbbuildingfluidport"));
        TbBuildingGrid = new fg.TbBuildingGrid(loader("fg_tbbuildinggrid"));
        TbBuildingPort = new fg.TbBuildingPort(loader("fg_tbbuildingport"));
        TbBuildingService = new fg.TbBuildingService(loader("fg_tbbuildingservice"));
        TbBuildingStack = new fg.TbBuildingStack(loader("fg_tbbuildingstack"));
        TbBuildingTier = new fg.TbBuildingTier(loader("fg_tbbuildingtier"));
        TbBuildMaterial = new fg.TbBuildMaterial(loader("fg_tbbuildmaterial"));
        TbBuildTool = new fg.TbBuildTool(loader("fg_tbbuildtool"));
        TbBuildUpgrade = new fg.TbBuildUpgrade(loader("fg_tbbuildupgrade"));
        TbCarrierReading = new fg.TbCarrierReading(loader("fg_tbcarrierreading"));
        TbCodexEntry = new fg.TbCodexEntry(loader("fg_tbcodexentry"));
        TbCombatComponent = new fg.TbCombatComponent(loader("fg_tbcombatcomponent"));
        TbEcoItem = new fg.TbEcoItem(loader("fg_tbecoitem"));
        TbFirmwareKind = new fg.TbFirmwareKind(loader("fg_tbfirmwarekind"));
        TbFluid = new fg.TbFluid(loader("fg_tbfluid"));
        TbFusionMerge = new fg.TbFusionMerge(loader("fg_tbfusionmerge"));
        TbFusionRecipe = new fg.TbFusionRecipe(loader("fg_tbfusionrecipe"));
        TbGridTerrain = new fg.TbGridTerrain(loader("fg_tbgridterrain"));
        TbHomeTuning = new fg.TbHomeTuning(loader("fg_tbhometuning"));
        TbInputAction = new fg.TbInputAction(loader("fg_tbinputaction"));
        TbIntelBoss = new fg.TbIntelBoss(loader("fg_tbintelboss"));
        TbIntelFragment = new fg.TbIntelFragment(loader("fg_tbintelfragment"));
        TbIntelKind = new fg.TbIntelKind(loader("fg_tbintelkind"));
        TbLocText = new fg.TbLocText(loader("fg_tbloctext"));
        TbMechEnemy = new fg.TbMechEnemy(loader("fg_tbmechenemy"));
        TbNotifyTier = new fg.TbNotifyTier(loader("fg_tbnotifytier"));
        TbNotifyType = new fg.TbNotifyType(loader("fg_tbnotifytype"));
        TbPowerNode = new fg.TbPowerNode(loader("fg_tbpowernode"));
        TbPowerSource = new fg.TbPowerSource(loader("fg_tbpowersource"));
        TbProducer = new fg.TbProducer(loader("fg_tbproducer"));
        TbRangeTarget = new fg.TbRangeTarget(loader("fg_tbrangetarget"));
        TbReaction = new fg.TbReaction(loader("fg_tbreaction"));
        TbRecipe = new fg.TbRecipe(loader("fg_tbrecipe"));
        TbRecipeIo = new fg.TbRecipeIo(loader("fg_tbrecipeio"));
        TbRemovedContent = new fg.TbRemovedContent(loader("fg_tbremovedcontent"));
        TbResearchBranch = new fg.TbResearchBranch(loader("fg_tbresearchbranch"));
        TbResearchNode = new fg.TbResearchNode(loader("fg_tbresearchnode"));
        TbRosterRole = new fg.TbRosterRole(loader("fg_tbrosterrole"));
        TbRuleKind = new fg.TbRuleKind(loader("fg_tbrulekind"));
        TbRulePreset = new fg.TbRulePreset(loader("fg_tbrulepreset"));
        TbShieldState = new fg.TbShieldState(loader("fg_tbshieldstate"));
        TbStartLayout = new fg.TbStartLayout(loader("fg_tbstartlayout"));
        TbStatusTag = new fg.TbStatusTag(loader("fg_tbstatustag"));
        TbSurface = new fg.TbSurface(loader("fg_tbsurface"));
        TbTerritory = new fg.TbTerritory(loader("fg_tbterritory"));
        TbTrapProfile = new fg.TbTrapProfile(loader("fg_tbtrapprofile"));
        TbTurretFluid = new fg.TbTurretFluid(loader("fg_tbturretfluid"));
        TbTurretProfile = new fg.TbTurretProfile(loader("fg_tbturretprofile"));
        TbTurretTargetMode = new fg.TbTurretTargetMode(loader("fg_tbturrettargetmode"));
        TbUiTuning = new fg.TbUiTuning(loader("fg_tbuituning"));
        TbWorldGenVersion = new fg.TbWorldGenVersion(loader("fg_tbworldgenversion"));
        TbWorldPreset = new fg.TbWorldPreset(loader("fg_tbworldpreset"));
        TbWorldSettingAxis = new fg.TbWorldSettingAxis(loader("fg_tbworldsettingaxis"));
        TbWorldStartClear = new fg.TbWorldStartClear(loader("fg_tbworldstartclear"));
        TbWorldStartGuarantee = new fg.TbWorldStartGuarantee(loader("fg_tbworldstartguarantee"));
        TbCellArena = new fp.TbCellArena(loader("fp_tbcellarena"));
        TbCreatureArena = new fp.TbCreatureArena(loader("fp_tbcreaturearena"));
        TbEnemy = new fp.TbEnemy(loader("fp_tbenemy"));
        TbEnemySkill = new fp.TbEnemySkill(loader("fp_tbenemyskill"));
        TbFood = new fp.TbFood(loader("fp_tbfood"));
        TbGlobal = new fp.TbGlobal(loader("fp_tbglobal"));
        TbMicroChoice = new fp.TbMicroChoice(loader("fp_tbmicrochoice"));
        TbModule = new fp.TbModule(loader("fp_tbmodule"));
        TbPlayerForm = new fp.TbPlayerForm(loader("fp_tbplayerform"));
        TbWave = new fp.TbWave(loader("fp_tbwave"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbAbilityEffect.ResolveRef(this);
        TbAffix.ResolveRef(this);
        TbBehaviorArchetype.ResolveRef(this);
        TbBossPhase.ResolveRef(this);
        TbCard.ResolveRef(this);
        TbCardEffect.ResolveRef(this);
        TbCardStat.ResolveRef(this);
        TbCellEnemy.ResolveRef(this);
        TbCellGlobal.ResolveRef(this);
        TbEcoEvent.ResolveRef(this);
        TbGeneModuleParams.ResolveRef(this);
        TbLevelCurve.ResolveRef(this);
        TbOrganModuleParams.ResolveRef(this);
        TbPhase.ResolveRef(this);
        TbPressureCurve.ResolveRef(this);
        TbStatusEffect.ResolveRef(this);
        TbStructuralEffectParams.ResolveRef(this);
        TbStructuralTriggerHookParams.ResolveRef(this);
        TbAnalysisKind.ResolveRef(this);
        TbAnalysisLore.ResolveRef(this);
        TbAssemblyMaterial.ResolveRef(this);
        TbBeltFilterPreset.ResolveRef(this);
        TbBuildCategory.ResolveRef(this);
        TbBuilding.ResolveRef(this);
        TbBuildingFluidPort.ResolveRef(this);
        TbBuildingGrid.ResolveRef(this);
        TbBuildingPort.ResolveRef(this);
        TbBuildingService.ResolveRef(this);
        TbBuildingStack.ResolveRef(this);
        TbBuildingTier.ResolveRef(this);
        TbBuildMaterial.ResolveRef(this);
        TbBuildTool.ResolveRef(this);
        TbBuildUpgrade.ResolveRef(this);
        TbCarrierReading.ResolveRef(this);
        TbCodexEntry.ResolveRef(this);
        TbCombatComponent.ResolveRef(this);
        TbEcoItem.ResolveRef(this);
        TbFirmwareKind.ResolveRef(this);
        TbFluid.ResolveRef(this);
        TbFusionMerge.ResolveRef(this);
        TbFusionRecipe.ResolveRef(this);
        TbGridTerrain.ResolveRef(this);
        TbHomeTuning.ResolveRef(this);
        TbInputAction.ResolveRef(this);
        TbIntelBoss.ResolveRef(this);
        TbIntelFragment.ResolveRef(this);
        TbIntelKind.ResolveRef(this);
        TbLocText.ResolveRef(this);
        TbMechEnemy.ResolveRef(this);
        TbNotifyTier.ResolveRef(this);
        TbNotifyType.ResolveRef(this);
        TbPowerNode.ResolveRef(this);
        TbPowerSource.ResolveRef(this);
        TbProducer.ResolveRef(this);
        TbRangeTarget.ResolveRef(this);
        TbReaction.ResolveRef(this);
        TbRecipe.ResolveRef(this);
        TbRecipeIo.ResolveRef(this);
        TbRemovedContent.ResolveRef(this);
        TbResearchBranch.ResolveRef(this);
        TbResearchNode.ResolveRef(this);
        TbRosterRole.ResolveRef(this);
        TbRuleKind.ResolveRef(this);
        TbRulePreset.ResolveRef(this);
        TbShieldState.ResolveRef(this);
        TbStartLayout.ResolveRef(this);
        TbStatusTag.ResolveRef(this);
        TbSurface.ResolveRef(this);
        TbTerritory.ResolveRef(this);
        TbTrapProfile.ResolveRef(this);
        TbTurretFluid.ResolveRef(this);
        TbTurretProfile.ResolveRef(this);
        TbTurretTargetMode.ResolveRef(this);
        TbUiTuning.ResolveRef(this);
        TbWorldGenVersion.ResolveRef(this);
        TbWorldPreset.ResolveRef(this);
        TbWorldSettingAxis.ResolveRef(this);
        TbWorldStartClear.ResolveRef(this);
        TbWorldStartGuarantee.ResolveRef(this);
        TbCellArena.ResolveRef(this);
        TbCreatureArena.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbEnemySkill.ResolveRef(this);
        TbFood.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbMicroChoice.ResolveRef(this);
        TbModule.ResolveRef(this);
        TbPlayerForm.ResolveRef(this);
        TbWave.ResolveRef(this);
    }
}

}
