
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 细胞阶段场地与时间轴
/// </summary>
public sealed partial class CellArena : Luban.BeanBase
{
    public CellArena(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ArenaHalfSize = _buf.ReadFloat();
        FoodConcurrent = _buf.ReadInt();
        FoodRespawnDelay = _buf.ReadFloat();
        FoodBRatio = _buf.ReadFloat();
        ThreatBaseCount = _buf.ReadInt();
        HazardCount = _buf.ReadInt();
        HazardRadius = _buf.ReadFloat();
        HazardDamagePerSecond = _buf.ReadFloat();
        MicroChoiceTime = _buf.ReadFloat();
        ForceEvolveTime = _buf.ReadFloat();
    }

    public static CellArena DeserializeCellArena(ByteBuf _buf)
    {
        return new fp.CellArena(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 半边长
    /// </summary>
    public readonly float ArenaHalfSize;
    /// <summary>
    /// 同时食物数
    /// </summary>
    public readonly int FoodConcurrent;
    /// <summary>
    /// 食物补充间隔
    /// </summary>
    public readonly float FoodRespawnDelay;
    /// <summary>
    /// B型占比
    /// </summary>
    public readonly float FoodBRatio;
    /// <summary>
    /// 首波威胁数
    /// </summary>
    public readonly int ThreatBaseCount;
    /// <summary>
    /// 危险区数量
    /// </summary>
    public readonly int HazardCount;
    /// <summary>
    /// 危险区半径
    /// </summary>
    public readonly float HazardRadius;
    /// <summary>
    /// 危险区DPS
    /// </summary>
    public readonly float HazardDamagePerSecond;
    /// <summary>
    /// 微选择触发时间
    /// </summary>
    public readonly float MicroChoiceTime;
    /// <summary>
    /// 强制进化时间
    /// </summary>
    public readonly float ForceEvolveTime;
   
    public const int __ID__ = -251796863;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "arenaHalfSize:" + ArenaHalfSize + ","
        + "foodConcurrent:" + FoodConcurrent + ","
        + "foodRespawnDelay:" + FoodRespawnDelay + ","
        + "foodBRatio:" + FoodBRatio + ","
        + "threatBaseCount:" + ThreatBaseCount + ","
        + "hazardCount:" + HazardCount + ","
        + "hazardRadius:" + HazardRadius + ","
        + "hazardDamagePerSecond:" + HazardDamagePerSecond + ","
        + "microChoiceTime:" + MicroChoiceTime + ","
        + "forceEvolveTime:" + ForceEvolveTime + ","
        + "}";
    }
}
}

