
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 生物阶段场地与时间轴
/// </summary>
public sealed partial class CreatureArena : Luban.BeanBase
{
    public CreatureArena(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ExploreEnd = _buf.ReadFloat();
        PressureEnd = _buf.ReadFloat();
        ArenaHalfSize = _buf.ReadFloat();
        EnemyRespawnDelay = _buf.ReadFloat();
        EnemyCapPhase1 = _buf.ReadInt();
        EnemyCapPhase2 = _buf.ReadInt();
    }

    public static CreatureArena DeserializeCreatureArena(ByteBuf _buf)
    {
        return new fp.CreatureArena(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 探索阶段结束
    /// </summary>
    public readonly float ExploreEnd;
    /// <summary>
    /// 压力阶段结束
    /// </summary>
    public readonly float PressureEnd;
    /// <summary>
    /// 半边长
    /// </summary>
    public readonly float ArenaHalfSize;
    /// <summary>
    /// 刷怪间隔
    /// </summary>
    public readonly float EnemyRespawnDelay;
    /// <summary>
    /// 阶段1敌人数上限
    /// </summary>
    public readonly int EnemyCapPhase1;
    /// <summary>
    /// 阶段2敌人数上限
    /// </summary>
    public readonly int EnemyCapPhase2;
   
    public const int __ID__ = -721366076;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "exploreEnd:" + ExploreEnd + ","
        + "pressureEnd:" + PressureEnd + ","
        + "arenaHalfSize:" + ArenaHalfSize + ","
        + "enemyRespawnDelay:" + EnemyRespawnDelay + ","
        + "enemyCapPhase1:" + EnemyCapPhase1 + ","
        + "enemyCapPhase2:" + EnemyCapPhase2 + ","
        + "}";
    }
}
}

