
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.fp
{ 
    public enum EEnemyId
    {
        /// <summary>
        /// 细胞威胁
        /// </summary>
        Threat = 1,
        /// <summary>
        /// 草食虫
        /// </summary>
        Herbivore = 2,
        /// <summary>
        /// 掠食虫
        /// </summary>
        Predator = 3,
        /// <summary>
        /// 精英
        /// </summary>
        Elite = 4,
    }

} 

