
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.fp
{ 
    public enum EMicroChoice
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 贪食囊
        /// </summary>
        Gluttony = 1,
        /// <summary>
        /// 趋光纤毛
        /// </summary>
        Phototaxis = 2,
        /// <summary>
        /// 代谢泡
        /// </summary>
        Metabolic = 3,
    }

} 

