
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 敌人技能
/// </summary>
public sealed partial class EnemySkill : Luban.BeanBase
{
    public EnemySkill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Damage = _buf.ReadFloat();
        Cooldown = _buf.ReadFloat();
        Range = _buf.ReadFloat();
    }

    public static EnemySkill DeserializeEnemySkill(ByteBuf _buf)
    {
        return new fp.EnemySkill(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 冷却
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 射程
    /// </summary>
    public readonly float Range;
   
    public const int __ID__ = 156527469;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "damage:" + Damage + ","
        + "cooldown:" + Cooldown + ","
        + "range:" + Range + ","
        + "}";
    }
}
}

