
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 敌人配置
/// </summary>
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(ByteBuf _buf) 
    {
        Id = (fp.EEnemyId)_buf.ReadInt();
        Name = _buf.ReadString();
        Volume = _buf.ReadFloat();
        Hp = _buf.ReadFloat();
        ContactDamage = _buf.ReadFloat();
        Speed = _buf.ReadFloat();
        EvoPoint = _buf.ReadInt();
        Biomass = _buf.ReadInt();
        SkillId = _buf.ReadInt();
        Tags = _buf.ReadString();
    }

    public static Enemy DeserializeEnemy(ByteBuf _buf)
    {
        return new fp.Enemy(_buf);
    }

    /// <summary>
    /// 敌人ID
    /// </summary>
    public readonly fp.EEnemyId Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体积
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 生命
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 接触伤害
    /// </summary>
    public readonly float ContactDamage;
    /// <summary>
    /// 移速
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 被吞噬进化点
    /// </summary>
    public readonly int EvoPoint;
    /// <summary>
    /// 被吞噬生物质
    /// </summary>
    public readonly int Biomass;
    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 扩展标签预留
    /// </summary>
    public readonly string Tags;
   
    public const int __ID__ = -621766332;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "volume:" + Volume + ","
        + "hp:" + Hp + ","
        + "contactDamage:" + ContactDamage + ","
        + "speed:" + Speed + ","
        + "evoPoint:" + EvoPoint + ","
        + "biomass:" + Biomass + ","
        + "skillId:" + SkillId + ","
        + "tags:" + Tags + ","
        + "}";
    }
}
}

