
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.fp
{ 
    public enum ERoute
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 吞噬扩张型
        /// </summary>
        Devour = 1,
        /// <summary>
        /// 功能特化型
        /// </summary>
        Specialist = 2,
        /// <summary>
        /// 科技统治型
        /// </summary>
        Tech = 3,
    }

} 

