
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 食物配置
/// </summary>
public sealed partial class Food : Luban.BeanBase
{
    public Food(ByteBuf _buf) 
    {
        Id = (fp.EFoodId)_buf.ReadInt();
        Name = _buf.ReadString();
        Volume = _buf.ReadFloat();
        EvoPoint = _buf.ReadInt();
        Biomass = _buf.ReadInt();
    }

    public static Food DeserializeFood(ByteBuf _buf)
    {
        return new fp.Food(_buf);
    }

    /// <summary>
    /// 食物ID
    /// </summary>
    public readonly fp.EFoodId Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体积
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 进化点
    /// </summary>
    public readonly int EvoPoint;
    /// <summary>
    /// 生物质
    /// </summary>
    public readonly int Biomass;
   
    public const int __ID__ = -712762590;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "volume:" + Volume + ","
        + "evoPoint:" + EvoPoint + ","
        + "biomass:" + Biomass + ","
        + "}";
    }
}
}

