
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// FP全局公式与门槛
/// </summary>
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EngulfRatio = _buf.ReadFloat();
        VolumeGainRatio = _buf.ReadFloat();
        SpeedVolumePenalty = _buf.ReadFloat();
        SpeedFloorRatio = _buf.ReadFloat();
        ContactDamageInterval = _buf.ReadFloat();
        EvoPointThreshold = _buf.ReadInt();
        WaveInterval = _buf.ReadFloat();
        WaveCount = _buf.ReadInt();
        EnemyBaseAggroRange = _buf.ReadFloat();
        ZapDamage = _buf.ReadFloat();
        ZapRange = _buf.ReadFloat();
        ZapCooldown = _buf.ReadFloat();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new fp.Global(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 吞噬阈值k
    /// </summary>
    public readonly float EngulfRatio;
    /// <summary>
    /// 体积增长比
    /// </summary>
    public readonly float VolumeGainRatio;
    /// <summary>
    /// 体积移速惩罚
    /// </summary>
    public readonly float SpeedVolumePenalty;
    /// <summary>
    /// 移速下限比
    /// </summary>
    public readonly float SpeedFloorRatio;
    /// <summary>
    /// 接触伤害间隔
    /// </summary>
    public readonly float ContactDamageInterval;
    /// <summary>
    /// 进化点门槛
    /// </summary>
    public readonly int EvoPointThreshold;
    /// <summary>
    /// 波次间隔秒
    /// </summary>
    public readonly float WaveInterval;
    /// <summary>
    /// 波次数
    /// </summary>
    public readonly int WaveCount;
    /// <summary>
    /// 敌人基础察觉范围
    /// </summary>
    public readonly float EnemyBaseAggroRange;
    /// <summary>
    /// 放电伤害
    /// </summary>
    public readonly float ZapDamage;
    /// <summary>
    /// 放电射程
    /// </summary>
    public readonly float ZapRange;
    /// <summary>
    /// 放电冷却
    /// </summary>
    public readonly float ZapCooldown;
   
    public const int __ID__ = -2039189145;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "engulfRatio:" + EngulfRatio + ","
        + "volumeGainRatio:" + VolumeGainRatio + ","
        + "speedVolumePenalty:" + SpeedVolumePenalty + ","
        + "speedFloorRatio:" + SpeedFloorRatio + ","
        + "contactDamageInterval:" + ContactDamageInterval + ","
        + "evoPointThreshold:" + EvoPointThreshold + ","
        + "waveInterval:" + WaveInterval + ","
        + "waveCount:" + WaveCount + ","
        + "enemyBaseAggroRange:" + EnemyBaseAggroRange + ","
        + "zapDamage:" + ZapDamage + ","
        + "zapRange:" + ZapRange + ","
        + "zapCooldown:" + ZapCooldown + ","
        + "}";
    }
}
}

