
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 细胞微选择
/// </summary>
public sealed partial class MicroChoice : Luban.BeanBase
{
    public MicroChoice(ByteBuf _buf) 
    {
        Id = (fp.EMicroChoice)_buf.ReadInt();
        Name = _buf.ReadString();
        Route = (fp.ERoute)_buf.ReadInt();
        Desc = _buf.ReadString();
        BiomassBonus = _buf.ReadFloat();
        SpeedBonus = _buf.ReadFloat();
        HealPerEat = _buf.ReadFloat();
    }

    public static MicroChoice DeserializeMicroChoice(ByteBuf _buf)
    {
        return new fp.MicroChoice(_buf);
    }

    /// <summary>
    /// 微选择ID
    /// </summary>
    public readonly fp.EMicroChoice Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 路线
    /// </summary>
    public readonly fp.ERoute Route;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 生物质加成
    /// </summary>
    public readonly float BiomassBonus;
    /// <summary>
    /// 移速加成
    /// </summary>
    public readonly float SpeedBonus;
    /// <summary>
    /// 每次吞噬回血
    /// </summary>
    public readonly float HealPerEat;
   
    public const int __ID__ = -1252462015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "route:" + Route + ","
        + "desc:" + Desc + ","
        + "biomassBonus:" + BiomassBonus + ","
        + "speedBonus:" + SpeedBonus + ","
        + "healPerEat:" + HealPerEat + ","
        + "}";
    }
}
}

