
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 构筑模块
/// </summary>
public sealed partial class Module : Luban.BeanBase
{
    public Module(ByteBuf _buf) 
    {
        Id = (fp.EModuleId)_buf.ReadInt();
        Name = _buf.ReadString();
        Route = (fp.ERoute)_buf.ReadInt();
        Price = _buf.ReadInt();
        Desc = _buf.ReadString();
        MaxHpFlat = _buf.ReadFloat();
        SpeedMulDelta = _buf.ReadFloat();
        MeleeMulDelta = _buf.ReadFloat();
        StaminaMaxFlat = _buf.ReadFloat();
        StaminaCostMulDelta = _buf.ReadFloat();
        StaminaRegenMulDelta = _buf.ReadFloat();
        DashInvulnFlat = _buf.ReadFloat();
        AggroMulDelta = _buf.ReadFloat();
        KillHeal = _buf.ReadFloat();
        UnlockAbilityId = _buf.ReadInt();
        Tags = _buf.ReadString();
    }

    public static Module DeserializeModule(ByteBuf _buf)
    {
        return new fp.Module(_buf);
    }

    /// <summary>
    /// 模块ID
    /// </summary>
    public readonly fp.EModuleId Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 路线
    /// </summary>
    public readonly fp.ERoute Route;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 生命加算
    /// </summary>
    public readonly float MaxHpFlat;
    /// <summary>
    /// 移速增量
    /// </summary>
    public readonly float SpeedMulDelta;
    /// <summary>
    /// 近战增量
    /// </summary>
    public readonly float MeleeMulDelta;
    /// <summary>
    /// 体力上限加算
    /// </summary>
    public readonly float StaminaMaxFlat;
    /// <summary>
    /// 体力消耗增量
    /// </summary>
    public readonly float StaminaCostMulDelta;
    /// <summary>
    /// 体力回复增量
    /// </summary>
    public readonly float StaminaRegenMulDelta;
    /// <summary>
    /// 无敌帧加算
    /// </summary>
    public readonly float DashInvulnFlat;
    /// <summary>
    /// 察觉范围增量
    /// </summary>
    public readonly float AggroMulDelta;
    /// <summary>
    /// 击杀回血
    /// </summary>
    public readonly float KillHeal;
    /// <summary>
    /// 解锁技能ID
    /// </summary>
    public readonly int UnlockAbilityId;
    /// <summary>
    /// 扩展标签预留
    /// </summary>
    public readonly string Tags;
   
    public const int __ID__ = -1864952784;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "route:" + Route + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "maxHpFlat:" + MaxHpFlat + ","
        + "speedMulDelta:" + SpeedMulDelta + ","
        + "meleeMulDelta:" + MeleeMulDelta + ","
        + "staminaMaxFlat:" + StaminaMaxFlat + ","
        + "staminaCostMulDelta:" + StaminaCostMulDelta + ","
        + "staminaRegenMulDelta:" + StaminaRegenMulDelta + ","
        + "dashInvulnFlat:" + DashInvulnFlat + ","
        + "aggroMulDelta:" + AggroMulDelta + ","
        + "killHeal:" + KillHeal + ","
        + "unlockAbilityId:" + UnlockAbilityId + ","
        + "tags:" + Tags + ","
        + "}";
    }
}
}

