
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 玩家形态基础面板
/// </summary>
public sealed partial class PlayerForm : Luban.BeanBase
{
    public PlayerForm(ByteBuf _buf) 
    {
        Id = (fp.EFormId)_buf.ReadInt();
        MaxHp = _buf.ReadFloat();
        StartVolume = _buf.ReadFloat();
        MaxVolume = _buf.ReadFloat();
        BaseSpeed = _buf.ReadFloat();
        Accel = _buf.ReadFloat();
        Drag = _buf.ReadFloat();
        MeleeDamage = _buf.ReadFloat();
        MeleeInterval = _buf.ReadFloat();
        MeleeRange = _buf.ReadFloat();
        StaminaMax = _buf.ReadFloat();
        DashCost = _buf.ReadFloat();
        StaminaRegen = _buf.ReadFloat();
        DashInvulnTime = _buf.ReadFloat();
        StaminaRegenDelay = _buf.ReadFloat();
        DashSpeedMultiplier = _buf.ReadFloat();
        DashDuration = _buf.ReadFloat();
    }

    public static PlayerForm DeserializePlayerForm(ByteBuf _buf)
    {
        return new fp.PlayerForm(_buf);
    }

    /// <summary>
    /// 形态ID
    /// </summary>
    public readonly fp.EFormId Id;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly float MaxHp;
    /// <summary>
    /// 初始体积
    /// </summary>
    public readonly float StartVolume;
    /// <summary>
    /// 体积上限
    /// </summary>
    public readonly float MaxVolume;
    /// <summary>
    /// 基础移速
    /// </summary>
    public readonly float BaseSpeed;
    /// <summary>
    /// 加速度
    /// </summary>
    public readonly float Accel;
    /// <summary>
    /// 阻力
    /// </summary>
    public readonly float Drag;
    /// <summary>
    /// 近战伤害
    /// </summary>
    public readonly float MeleeDamage;
    /// <summary>
    /// 近战间隔
    /// </summary>
    public readonly float MeleeInterval;
    /// <summary>
    /// 近战范围
    /// </summary>
    public readonly float MeleeRange;
    /// <summary>
    /// 体力上限
    /// </summary>
    public readonly float StaminaMax;
    /// <summary>
    /// 冲刺消耗
    /// </summary>
    public readonly float DashCost;
    /// <summary>
    /// 体力回复
    /// </summary>
    public readonly float StaminaRegen;
    /// <summary>
    /// 冲刺无敌时长
    /// </summary>
    public readonly float DashInvulnTime;
    /// <summary>
    /// 体力回复延迟
    /// </summary>
    public readonly float StaminaRegenDelay;
    /// <summary>
    /// 冲刺移速倍率
    /// </summary>
    public readonly float DashSpeedMultiplier;
    /// <summary>
    /// 冲刺持续
    /// </summary>
    public readonly float DashDuration;
   
    public const int __ID__ = 448573193;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxHp:" + MaxHp + ","
        + "startVolume:" + StartVolume + ","
        + "maxVolume:" + MaxVolume + ","
        + "baseSpeed:" + BaseSpeed + ","
        + "accel:" + Accel + ","
        + "drag:" + Drag + ","
        + "meleeDamage:" + MeleeDamage + ","
        + "meleeInterval:" + MeleeInterval + ","
        + "meleeRange:" + MeleeRange + ","
        + "staminaMax:" + StaminaMax + ","
        + "dashCost:" + DashCost + ","
        + "staminaRegen:" + StaminaRegen + ","
        + "dashInvulnTime:" + DashInvulnTime + ","
        + "staminaRegenDelay:" + StaminaRegenDelay + ","
        + "dashSpeedMultiplier:" + DashSpeedMultiplier + ","
        + "dashDuration:" + DashDuration + ","
        + "}";
    }
}
}

