
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 生物阶段场地与时间轴
/// </summary>
public partial class TbCreatureArena
{
    private readonly System.Collections.Generic.Dictionary<int, fp.CreatureArena> _dataMap;
    private readonly System.Collections.Generic.List<fp.CreatureArena> _dataList;
    
    public TbCreatureArena(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fp.CreatureArena>(n);
        _dataList = new System.Collections.Generic.List<fp.CreatureArena>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.CreatureArena _v;
            _v = global::GameConfig.fp.CreatureArena.DeserializeCreatureArena(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fp.CreatureArena> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.CreatureArena> DataList => _dataList;

    public fp.CreatureArena GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.CreatureArena Get(int key) => _dataMap[key];
    public fp.CreatureArena this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

