
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 敌人配置
/// </summary>
public partial class TbEnemy
{
    private readonly System.Collections.Generic.Dictionary<fp.EEnemyId, fp.Enemy> _dataMap;
    private readonly System.Collections.Generic.List<fp.Enemy> _dataList;
    
    public TbEnemy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<fp.EEnemyId, fp.Enemy>(n);
        _dataList = new System.Collections.Generic.List<fp.Enemy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.Enemy _v;
            _v = global::GameConfig.fp.Enemy.DeserializeEnemy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<fp.EEnemyId, fp.Enemy> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.Enemy> DataList => _dataList;

    public fp.Enemy GetOrDefault(fp.EEnemyId key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.Enemy Get(fp.EEnemyId key) => _dataMap[key];
    public fp.Enemy this[fp.EEnemyId key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

