
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 敌人技能
/// </summary>
public partial class TbEnemySkill
{
    private readonly System.Collections.Generic.Dictionary<int, fp.EnemySkill> _dataMap;
    private readonly System.Collections.Generic.List<fp.EnemySkill> _dataList;
    
    public TbEnemySkill(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fp.EnemySkill>(n);
        _dataList = new System.Collections.Generic.List<fp.EnemySkill>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.EnemySkill _v;
            _v = global::GameConfig.fp.EnemySkill.DeserializeEnemySkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fp.EnemySkill> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.EnemySkill> DataList => _dataList;

    public fp.EnemySkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.EnemySkill Get(int key) => _dataMap[key];
    public fp.EnemySkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

