
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 食物配置
/// </summary>
public partial class TbFood
{
    private readonly System.Collections.Generic.Dictionary<fp.EFoodId, fp.Food> _dataMap;
    private readonly System.Collections.Generic.List<fp.Food> _dataList;
    
    public TbFood(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<fp.EFoodId, fp.Food>(n);
        _dataList = new System.Collections.Generic.List<fp.Food>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.Food _v;
            _v = global::GameConfig.fp.Food.DeserializeFood(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<fp.EFoodId, fp.Food> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.Food> DataList => _dataList;

    public fp.Food GetOrDefault(fp.EFoodId key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.Food Get(fp.EFoodId key) => _dataMap[key];
    public fp.Food this[fp.EFoodId key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

