
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// FP全局公式与门槛
/// </summary>
public partial class TbGlobal
{
    private readonly System.Collections.Generic.Dictionary<int, fp.Global> _dataMap;
    private readonly System.Collections.Generic.List<fp.Global> _dataList;
    
    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fp.Global>(n);
        _dataList = new System.Collections.Generic.List<fp.Global>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.Global _v;
            _v = global::GameConfig.fp.Global.DeserializeGlobal(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fp.Global> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.Global> DataList => _dataList;

    public fp.Global GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.Global Get(int key) => _dataMap[key];
    public fp.Global this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

