
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 细胞微选择
/// </summary>
public partial class TbMicroChoice
{
    private readonly System.Collections.Generic.Dictionary<fp.EMicroChoice, fp.MicroChoice> _dataMap;
    private readonly System.Collections.Generic.List<fp.MicroChoice> _dataList;
    
    public TbMicroChoice(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<fp.EMicroChoice, fp.MicroChoice>(n);
        _dataList = new System.Collections.Generic.List<fp.MicroChoice>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.MicroChoice _v;
            _v = global::GameConfig.fp.MicroChoice.DeserializeMicroChoice(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<fp.EMicroChoice, fp.MicroChoice> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.MicroChoice> DataList => _dataList;

    public fp.MicroChoice GetOrDefault(fp.EMicroChoice key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.MicroChoice Get(fp.EMicroChoice key) => _dataMap[key];
    public fp.MicroChoice this[fp.EMicroChoice key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

