
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 构筑模块
/// </summary>
public partial class TbModule
{
    private readonly System.Collections.Generic.Dictionary<fp.EModuleId, fp.Module> _dataMap;
    private readonly System.Collections.Generic.List<fp.Module> _dataList;
    
    public TbModule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<fp.EModuleId, fp.Module>(n);
        _dataList = new System.Collections.Generic.List<fp.Module>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.Module _v;
            _v = global::GameConfig.fp.Module.DeserializeModule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<fp.EModuleId, fp.Module> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.Module> DataList => _dataList;

    public fp.Module GetOrDefault(fp.EModuleId key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.Module Get(fp.EModuleId key) => _dataMap[key];
    public fp.Module this[fp.EModuleId key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

