
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 细胞波次
/// </summary>
public partial class TbWave
{
    private readonly System.Collections.Generic.Dictionary<int, fp.Wave> _dataMap;
    private readonly System.Collections.Generic.List<fp.Wave> _dataList;
    
    public TbWave(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, fp.Wave>(n);
        _dataList = new System.Collections.Generic.List<fp.Wave>(n);
        for(int i = n ; i > 0 ; --i)
        {
            fp.Wave _v;
            _v = global::GameConfig.fp.Wave.DeserializeWave(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.WaveIndex, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, fp.Wave> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<fp.Wave> DataList => _dataList;

    public fp.Wave GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public fp.Wave Get(int key) => _dataMap[key];
    public fp.Wave this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

