
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.fp
{
/// <summary>
/// 细胞波次
/// </summary>
public sealed partial class Wave : Luban.BeanBase
{
    public Wave(ByteBuf _buf) 
    {
        WaveIndex = _buf.ReadInt();
        TriggerTime = _buf.ReadFloat();
        ThreatMul = _buf.ReadFloat();
    }

    public static Wave DeserializeWave(ByteBuf _buf)
    {
        return new fp.Wave(_buf);
    }

    /// <summary>
    /// 波次序号
    /// </summary>
    public readonly int WaveIndex;
    /// <summary>
    /// 触发时间
    /// </summary>
    public readonly float TriggerTime;
    /// <summary>
    /// 威胁数量倍率
    /// </summary>
    public readonly float ThreatMul;
   
    public const int __ID__ = -712269379;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "waveIndex:" + WaveIndex + ","
        + "triggerTime:" + TriggerTime + ","
        + "threatMul:" + ThreatMul + ","
        + "}";
    }
}
}

