
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 主动技能
/// </summary>
public sealed partial class Ability : Luban.BeanBase
{
    public Ability(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Cooldown = _buf.ReadFloat();
        Charges = _buf.ReadInt();
        StaminaCost = _buf.ReadFloat();
        CastRange = _buf.ReadFloat();
        TargetMode = (cell.ETargetMode)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Tags.Add(_e0);}}
        IsStarter = _buf.ReadBool();
    }

    public static Ability DeserializeAbility(ByteBuf _buf)
    {
        return new cell.Ability(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 冷却(秒)
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 充能数
    /// </summary>
    public readonly int Charges;
    /// <summary>
    /// 体力消耗
    /// </summary>
    public readonly float StaminaCost;
    /// <summary>
    /// 施放距离,0=不限
    /// </summary>
    public readonly float CastRange;
    /// <summary>
    /// 瞄准方式
    /// </summary>
    public readonly cell.ETargetMode TargetMode;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// 是否初始技能
    /// </summary>
    public readonly bool IsStarter;
   
    public const int __ID__ = 434660478;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "cooldown:" + Cooldown + ","
        + "charges:" + Charges + ","
        + "staminaCost:" + StaminaCost + ","
        + "castRange:" + CastRange + ","
        + "targetMode:" + TargetMode + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "isStarter:" + IsStarter + ","
        + "}";
    }
}
}

