
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 词缀
/// </summary>
public sealed partial class Affix : Luban.BeanBase
{
    public Affix(ByteBuf _buf) 
    {
        Id = (cell.EAffix)_buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
    }

    public static Affix DeserializeAffix(ByteBuf _buf)
    {
        return new cell.Affix(_buf);
    }

    /// <summary>
    /// 词缀
    /// </summary>
    public readonly cell.EAffix Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 效果方向
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1841907236;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

