
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 行为原型
/// </summary>
public sealed partial class BehaviorArchetype : Luban.BeanBase
{
    public BehaviorArchetype(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Kind = (cell.EBehaviorKind)_buf.ReadInt();
        Accel = _buf.ReadFloat();
        TurnRate = _buf.ReadFloat();
        AggroRange = _buf.ReadFloat();
        AttackRange = _buf.ReadFloat();
        AttackCooldown = _buf.ReadFloat();
        AttackDamage = _buf.ReadFloat();
        Separation = _buf.ReadFloat();
        PreferredRange = _buf.ReadFloat();
        ChargeTelegraph = _buf.ReadFloat();
        ChargeSpeedMul = _buf.ReadFloat();
        WanderStrength = _buf.ReadFloat();
    }

    public static BehaviorArchetype DeserializeBehaviorArchetype(ByteBuf _buf)
    {
        return new cell.BehaviorArchetype(_buf);
    }

    /// <summary>
    /// 原型索引
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 行为种类
    /// </summary>
    public readonly cell.EBehaviorKind Kind;
    /// <summary>
    /// 加速度
    /// </summary>
    public readonly float Accel;
    /// <summary>
    /// 转向角速度(弧度/秒),0=不限
    /// </summary>
    public readonly float TurnRate;
    /// <summary>
    /// 索敌半径,0=不索敌
    /// </summary>
    public readonly float AggroRange;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// 攻击间隔(秒)
    /// </summary>
    public readonly float AttackCooldown;
    /// <summary>
    /// 接触伤害
    /// </summary>
    public readonly float AttackDamage;
    /// <summary>
    /// 分离强度,0=允许重叠
    /// </summary>
    public readonly float Separation;
    /// <summary>
    /// Orbit/Ranged 保持半径
    /// </summary>
    public readonly float PreferredRange;
    /// <summary>
    /// 蓄力时间(秒)
    /// </summary>
    public readonly float ChargeTelegraph;
    /// <summary>
    /// 冲刺速度倍率
    /// </summary>
    public readonly float ChargeSpeedMul;
    /// <summary>
    /// 游走强度
    /// </summary>
    public readonly float WanderStrength;
   
    public const int __ID__ = 822037163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "kind:" + Kind + ","
        + "accel:" + Accel + ","
        + "turnRate:" + TurnRate + ","
        + "aggroRange:" + AggroRange + ","
        + "attackRange:" + AttackRange + ","
        + "attackCooldown:" + AttackCooldown + ","
        + "attackDamage:" + AttackDamage + ","
        + "separation:" + Separation + ","
        + "preferredRange:" + PreferredRange + ","
        + "chargeTelegraph:" + ChargeTelegraph + ","
        + "chargeSpeedMul:" + ChargeSpeedMul + ","
        + "wanderStrength:" + WanderStrength + ","
        + "}";
    }
}
}

