
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 首领阶段
/// </summary>
public sealed partial class BossPhase : Luban.BeanBase
{
    public BossPhase(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BossEnemyId = _buf.ReadInt();
        PhaseIndex = _buf.ReadInt();
        Name = _buf.ReadString();
        HpThreshold = _buf.ReadFloat();
        ArchetypeId = _buf.ReadInt();
    }

    public static BossPhase DeserializeBossPhase(ByteBuf _buf)
    {
        return new cell.BossPhase(_buf);
    }

    /// <summary>
    /// 阶段全局id(bossEnemyId*10+phaseIndex)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属首领敌人id(cell.TbCellEnemy)
    /// </summary>
    public readonly int BossEnemyId;
    /// <summary>
    /// 阶段序号,0起，数值越大越后期
    /// </summary>
    public readonly int PhaseIndex;
    /// <summary>
    /// 阶段名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 进入本阶段的生命值百分比上限(0-1]，按满足条件中门槛最小的一项生效
    /// </summary>
    public readonly float HpThreshold;
    /// <summary>
    /// 本阶段生效的行为原型id(cell.TbBehaviorArchetype)，覆盖敌人默认原型
    /// </summary>
    public readonly int ArchetypeId;
   
    public const int __ID__ = 933176418;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bossEnemyId:" + BossEnemyId + ","
        + "phaseIndex:" + PhaseIndex + ","
        + "name:" + Name + ","
        + "hpThreshold:" + HpThreshold + ","
        + "archetypeId:" + ArchetypeId + ","
        + "}";
    }
}
}

