
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 卡牌
/// </summary>
public sealed partial class Card : Luban.BeanBase
{
    public Card(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Route = (cell.ERoute)_buf.ReadInt();
        Rarity = (cell.ERarity)_buf.ReadInt();
        UnlockPhase = _buf.ReadInt();
        MaxStack = _buf.ReadInt();
        Trigger = (cell.ETrigger)_buf.ReadInt();
        TriggerInterval = _buf.ReadFloat();
        TriggerChance = _buf.ReadFloat();
        TriggerCooldown = _buf.ReadFloat();
        GrantAbilityId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); RuleFlags = new System.Collections.Generic.List<cell.ERuleFlag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { cell.ERuleFlag _e0;  _e0 = (cell.ERuleFlag)_buf.ReadInt(); RuleFlags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SynergyTags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SynergyTags.Add(_e0);}}
        PollutionCost = _buf.ReadFloat();
        DrawbackDesc = _buf.ReadString();
        IsPureStatCard = _buf.ReadBool();
        ContentKind = (cell.EContentKind)_buf.ReadInt();
        ContentId = _buf.ReadString();
    }

    public static Card DeserializeCard(ByteBuf _buf)
    {
        return new cell.Card(_buf);
    }

    /// <summary>
    /// 卡牌id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 一句话主效果
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 路线
    /// </summary>
    public readonly cell.ERoute Route;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly cell.ERarity Rarity;
    /// <summary>
    /// 解锁所需生态时期序号
    /// </summary>
    public readonly int UnlockPhase;
    /// <summary>
    /// 可叠加层数上限
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 触发时机
    /// </summary>
    public readonly cell.ETrigger Trigger;
    /// <summary>
    /// OnTick 触发间隔(秒)
    /// </summary>
    public readonly float TriggerInterval;
    /// <summary>
    /// 触发概率0-1
    /// </summary>
    public readonly float TriggerChance;
    /// <summary>
    /// 触发内置冷却(秒)
    /// </summary>
    public readonly float TriggerCooldown;
    /// <summary>
    /// 授予的技能id,0=不授予
    /// </summary>
    public readonly int GrantAbilityId;
    /// <summary>
    /// 开启的规则开关
    /// </summary>
    public readonly System.Collections.Generic.List<cell.ERuleFlag> RuleFlags;
    /// <summary>
    /// 联动标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> SynergyTags;
    /// <summary>
    /// 取卡时增加的污染度
    /// </summary>
    public readonly float PollutionCost;
    /// <summary>
    /// 副作用描述
    /// </summary>
    public readonly string DrawbackDesc;
    /// <summary>
    /// 是否纯数值卡
    /// </summary>
    public readonly bool IsPureStatCard;
    /// <summary>
    /// 内容种类：器官/基因（代谢化迁移，None=旧战斗卡/未归类）
    /// </summary>
    public readonly cell.EContentKind ContentKind;
    /// <summary>
    /// 对应 OrganelleCatalog/GeneCatalog 的字符串 Id，contentKind=None 时为空
    /// </summary>
    public readonly string ContentId;
   
    public const int __ID__ = 1583492156;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "route:" + Route + ","
        + "rarity:" + Rarity + ","
        + "unlockPhase:" + UnlockPhase + ","
        + "maxStack:" + MaxStack + ","
        + "trigger:" + Trigger + ","
        + "triggerInterval:" + TriggerInterval + ","
        + "triggerChance:" + TriggerChance + ","
        + "triggerCooldown:" + TriggerCooldown + ","
        + "grantAbilityId:" + GrantAbilityId + ","
        + "ruleFlags:" + Luban.StringUtil.CollectionToString(RuleFlags) + ","
        + "synergyTags:" + Luban.StringUtil.CollectionToString(SynergyTags) + ","
        + "pollutionCost:" + PollutionCost + ","
        + "drawbackDesc:" + DrawbackDesc + ","
        + "isPureStatCard:" + IsPureStatCard + ","
        + "contentKind:" + ContentKind + ","
        + "contentId:" + ContentId + ","
        + "}";
    }
}
}

