
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 卡牌效果
/// </summary>
public sealed partial class CardEffect : Luban.BeanBase
{
    public CardEffect(ByteBuf _buf) 
    {
        Uid = _buf.ReadInt();
        CardId = _buf.ReadInt();
        Order = _buf.ReadInt();
        Kind = (cell.EEffectKind)_buf.ReadInt();
        Shape = (cell.EEffectShape)_buf.ReadInt();
        Value = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        Duration = _buf.ReadFloat();
        Count = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Status = new System.Collections.Generic.List<cell.EStatus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { cell.EStatus _e0;  _e0 = (cell.EStatus)_buf.ReadInt(); Status.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RequireStatus = new System.Collections.Generic.List<cell.EStatus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { cell.EStatus _e0;  _e0 = (cell.EStatus)_buf.ReadInt(); RequireStatus.Add(_e0);}}
        TargetFaction = (cell.EFaction)_buf.ReadInt();
        Stat = (cell.EStatId)_buf.ReadInt();
        Op = (cell.EModifierOp)_buf.ReadInt();
        Resource = (cell.EResourceKind)_buf.ReadInt();
        SpawnEnemyId = _buf.ReadInt();
        Rule = (cell.ERuleFlag)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Affixes = new System.Collections.Generic.List<cell.EAffix>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { cell.EAffix _e0;  _e0 = (cell.EAffix)_buf.ReadInt(); Affixes.Add(_e0);}}
        ScaleWithPower = _buf.ReadBool();
    }

    public static CardEffect DeserializeCardEffect(ByteBuf _buf)
    {
        return new cell.CardEffect(_buf);
    }

    /// <summary>
    /// 唯一id=卡牌id*10+序号
    /// </summary>
    public readonly int Uid;
    /// <summary>
    /// 所属卡牌id
    /// </summary>
    public readonly int CardId;
    /// <summary>
    /// 执行顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 效果类别
    /// </summary>
    public readonly cell.EEffectKind Kind;
    /// <summary>
    /// 作用形状
    /// </summary>
    public readonly cell.EEffectShape Shape;
    /// <summary>
    /// 主数值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 半径/长度
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 持续时间,0=瞬时
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 整数参数
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 施加状态
    /// </summary>
    public readonly System.Collections.Generic.List<cell.EStatus> Status;
    /// <summary>
    /// 只命中带此状态的目标
    /// </summary>
    public readonly System.Collections.Generic.List<cell.EStatus> RequireStatus;
    /// <summary>
    /// 作用阵营
    /// </summary>
    public readonly cell.EFaction TargetFaction;
    /// <summary>
    /// 属性id
    /// </summary>
    public readonly cell.EStatId Stat;
    /// <summary>
    /// 修正层级
    /// </summary>
    public readonly cell.EModifierOp Op;
    /// <summary>
    /// 资源种类
    /// </summary>
    public readonly cell.EResourceKind Resource;
    /// <summary>
    /// 生成的敌人id
    /// </summary>
    public readonly int SpawnEnemyId;
    /// <summary>
    /// 规则开关
    /// </summary>
    public readonly cell.ERuleFlag Rule;
    /// <summary>
    /// 词缀
    /// </summary>
    public readonly System.Collections.Generic.List<cell.EAffix> Affixes;
    /// <summary>
    /// 是否随技能强度缩放
    /// </summary>
    public readonly bool ScaleWithPower;
   
    public const int __ID__ = 9614573;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "uid:" + Uid + ","
        + "cardId:" + CardId + ","
        + "order:" + Order + ","
        + "kind:" + Kind + ","
        + "shape:" + Shape + ","
        + "value:" + Value + ","
        + "radius:" + Radius + ","
        + "duration:" + Duration + ","
        + "count:" + Count + ","
        + "status:" + Luban.StringUtil.CollectionToString(Status) + ","
        + "requireStatus:" + Luban.StringUtil.CollectionToString(RequireStatus) + ","
        + "targetFaction:" + TargetFaction + ","
        + "stat:" + Stat + ","
        + "op:" + Op + ","
        + "resource:" + Resource + ","
        + "spawnEnemyId:" + SpawnEnemyId + ","
        + "rule:" + Rule + ","
        + "affixes:" + Luban.StringUtil.CollectionToString(Affixes) + ","
        + "scaleWithPower:" + ScaleWithPower + ","
        + "}";
    }
}
}

