
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 卡牌属性修正
/// </summary>
public sealed partial class CardStat : Luban.BeanBase
{
    public CardStat(ByteBuf _buf) 
    {
        Uid = _buf.ReadInt();
        CardId = _buf.ReadInt();
        Stat = (cell.EStatId)_buf.ReadInt();
        Op = (cell.EModifierOp)_buf.ReadInt();
        Value = _buf.ReadFloat();
        IsDrawback = _buf.ReadBool();
    }

    public static CardStat DeserializeCardStat(ByteBuf _buf)
    {
        return new cell.CardStat(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Uid;
    /// <summary>
    /// 所属卡牌id
    /// </summary>
    public readonly int CardId;
    /// <summary>
    /// 属性id
    /// </summary>
    public readonly cell.EStatId Stat;
    /// <summary>
    /// 修正层级
    /// </summary>
    public readonly cell.EModifierOp Op;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 是否副作用(负面)
    /// </summary>
    public readonly bool IsDrawback;
   
    public const int __ID__ = -857659216;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "uid:" + Uid + ","
        + "cardId:" + CardId + ","
        + "stat:" + Stat + ","
        + "op:" + Op + ","
        + "value:" + Value + ","
        + "isDrawback:" + IsDrawback + ","
        + "}";
    }
}
}

