
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 全局常量
/// </summary>
public sealed partial class CellGlobal : Luban.BeanBase
{
    public CellGlobal(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BaseMaxHealth = _buf.ReadFloat();
        BaseMoveSpeed = _buf.ReadFloat();
        BaseVolume = _buf.ReadFloat();
        BaseMeleeDamage = _buf.ReadFloat();
        DevourRatio = _buf.ReadFloat();
        BreachedDiscount = _buf.ReadFloat();
        CorrodedDiscount = _buf.ReadFloat();
        VolumeGrowthRatio = _buf.ReadFloat();
        ComboWindow = _buf.ReadFloat();
        ComboGainPerStack = _buf.ReadFloat();
        StaminaMax = _buf.ReadFloat();
        StaminaRegen = _buf.ReadFloat();
        PollutionCap = _buf.ReadFloat();
        StartAbilitySlots = _buf.ReadInt();
        MaxAbilitySlots = _buf.ReadInt();
        UnitCapacity = _buf.ReadInt();
        ArenaHalfExtent = _buf.ReadFloat();
        HashCellSize = _buf.ReadFloat();
        PityThreshold = _buf.ReadInt();
        LowHealthPercent = _buf.ReadFloat();
        RouteAffinityPerCard = _buf.ReadFloat();
        RouteAffinityCap = _buf.ReadFloat();
        SynergyBonusPerMatch = _buf.ReadFloat();
        SynergyBonusCap = _buf.ReadFloat();
        ObstacleCount = _buf.ReadInt();
    }

    public static CellGlobal DeserializeCellGlobal(ByteBuf _buf)
    {
        return new cell.CellGlobal(_buf);
    }

    /// <summary>
    /// 固定填 1
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 初始最大生命
    /// </summary>
    public readonly float BaseMaxHealth;
    /// <summary>
    /// 初始移速
    /// </summary>
    public readonly float BaseMoveSpeed;
    /// <summary>
    /// 初始体积
    /// </summary>
    public readonly float BaseVolume;
    /// <summary>
    /// 初始近战伤害
    /// </summary>
    public readonly float BaseMeleeDamage;
    /// <summary>
    /// 吞噬体积门槛倍率
    /// </summary>
    public readonly float DevourRatio;
    /// <summary>
    /// 破体门槛折扣
    /// </summary>
    public readonly float BreachedDiscount;
    /// <summary>
    /// 腐蚀门槛折扣
    /// </summary>
    public readonly float CorrodedDiscount;
    /// <summary>
    /// 吞噬体积转化率
    /// </summary>
    public readonly float VolumeGrowthRatio;
    /// <summary>
    /// 连吃断连时间(秒)
    /// </summary>
    public readonly float ComboWindow;
    /// <summary>
    /// 每层连吃收益加成
    /// </summary>
    public readonly float ComboGainPerStack;
    /// <summary>
    /// 体力上限
    /// </summary>
    public readonly float StaminaMax;
    /// <summary>
    /// 体力回复/秒
    /// </summary>
    public readonly float StaminaRegen;
    /// <summary>
    /// 污染度上限
    /// </summary>
    public readonly float PollutionCap;
    /// <summary>
    /// 初始技能槽
    /// </summary>
    public readonly int StartAbilitySlots;
    /// <summary>
    /// 技能槽上限
    /// </summary>
    public readonly int MaxAbilitySlots;
    /// <summary>
    /// 内核单位容量
    /// </summary>
    public readonly int UnitCapacity;
    /// <summary>
    /// 场地半边长
    /// </summary>
    public readonly float ArenaHalfExtent;
    /// <summary>
    /// 空间哈希cell边长
    /// </summary>
    public readonly float HashCellSize;
    /// <summary>
    /// 连续未出稀有的保底次数
    /// </summary>
    public readonly int PityThreshold;
    /// <summary>
    /// 低血保底阈值
    /// </summary>
    public readonly float LowHealthPercent;
    /// <summary>
    /// 每张同路线卡的权重加成
    /// </summary>
    public readonly float RouteAffinityPerCard;
    /// <summary>
    /// 路线亲和上限
    /// </summary>
    public readonly float RouteAffinityCap;
    /// <summary>
    /// 每个联动标签的权重加成
    /// </summary>
    public readonly float SynergyBonusPerMatch;
    /// <summary>
    /// 联动加成上限
    /// </summary>
    public readonly float SynergyBonusCap;
    /// <summary>
    /// 局内静态障碍数量
    /// </summary>
    public readonly int ObstacleCount;
   
    public const int __ID__ = -1924036655;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "baseMaxHealth:" + BaseMaxHealth + ","
        + "baseMoveSpeed:" + BaseMoveSpeed + ","
        + "baseVolume:" + BaseVolume + ","
        + "baseMeleeDamage:" + BaseMeleeDamage + ","
        + "devourRatio:" + DevourRatio + ","
        + "breachedDiscount:" + BreachedDiscount + ","
        + "corrodedDiscount:" + CorrodedDiscount + ","
        + "volumeGrowthRatio:" + VolumeGrowthRatio + ","
        + "comboWindow:" + ComboWindow + ","
        + "comboGainPerStack:" + ComboGainPerStack + ","
        + "staminaMax:" + StaminaMax + ","
        + "staminaRegen:" + StaminaRegen + ","
        + "pollutionCap:" + PollutionCap + ","
        + "startAbilitySlots:" + StartAbilitySlots + ","
        + "maxAbilitySlots:" + MaxAbilitySlots + ","
        + "unitCapacity:" + UnitCapacity + ","
        + "arenaHalfExtent:" + ArenaHalfExtent + ","
        + "hashCellSize:" + HashCellSize + ","
        + "pityThreshold:" + PityThreshold + ","
        + "lowHealthPercent:" + LowHealthPercent + ","
        + "routeAffinityPerCard:" + RouteAffinityPerCard + ","
        + "routeAffinityCap:" + RouteAffinityCap + ","
        + "synergyBonusPerMatch:" + SynergyBonusPerMatch + ","
        + "synergyBonusCap:" + SynergyBonusCap + ","
        + "obstacleCount:" + ObstacleCount + ","
        + "}";
    }
}
}

