
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EAffix
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 生成数量翻倍
        /// </summary>
        Proliferate = 1,
        /// <summary>
        /// 与电系联动
        /// </summary>
        Conductive = 2,
        /// <summary>
        /// 持续削弱体积护壳速度
        /// </summary>
        Corrosive = 3,
        /// <summary>
        /// 返还体力冷却营养
        /// </summary>
        Refund = 4,
        /// <summary>
        /// 结束时生成次级效果
        /// </summary>
        Fission = 5,
        /// <summary>
        /// 复制上次触发的弱版
        /// </summary>
        Mimic = 6,
        /// <summary>
        /// 低资源时更强
        /// </summary>
        Hunger = 7,
        /// <summary>
        /// 静止筑巢时更强
        /// </summary>
        Homeostasis = 8,
        /// <summary>
        /// 强化但自损
        /// </summary>
        Overload = 9,
        /// <summary>
        /// 附属体越多本体越强
        /// </summary>
        Symbiosis = 10,
        /// <summary>
        /// 效果穿透目标
        /// </summary>
        Pierce = 11,
        /// <summary>
        /// 命中后跳向下一目标
        /// </summary>
        Ricochet = 12,
        /// <summary>
        /// 留下持续区域
        /// </summary>
        Lingering = 13,
        /// <summary>
        /// 拉拽附近目标
        /// </summary>
        Gravity = 14,
        /// <summary>
        /// 逼退小型敌人
        /// </summary>
        Fear = 15,
        /// <summary>
        /// 施加易伤标记
        /// </summary>
        Mark = 16,
        /// <summary>
        /// 附着并持续削弱
        /// </summary>
        Parasite = 17,
        /// <summary>
        /// 转化敌方资源
        /// </summary>
        Siphon = 18,
        /// <summary>
        /// 提高受击阈值
        /// </summary>
        Harden = 19,
        /// <summary>
        /// 受击时转换形态
        /// </summary>
        Molt = 20,
        /// <summary>
        /// 触发次数递增
        /// </summary>
        Chain = 21,
        /// <summary>
        /// 多目标互相加成
        /// </summary>
        Resonate = 22,
        /// <summary>
        /// 效果延迟但加倍
        /// </summary>
        Delayed = 23,
        /// <summary>
        /// 缩短其他冷却
        /// </summary>
        Catalyze = 24,
        /// <summary>
        /// 大目标死亡裂成小块
        /// </summary>
        Split = 25,
        /// <summary>
        /// 延迟生成友方单位
        /// </summary>
        Hatch = 26,
        /// <summary>
        /// 累积破碎层数
        /// </summary>
        Crystallize = 27,
        /// <summary>
        /// 周期性强弱交替
        /// </summary>
        Tidal = 28,
        /// <summary>
        /// 对高体积目标增伤
        /// </summary>
        BoneEater = 29,
        /// <summary>
        /// 效果可脱离本体存在
        /// </summary>
        Detached = 30,
        /// <summary>
        /// 消耗污染度换取回复
        /// </summary>
        Entropy = 31,
        /// <summary>
        /// 消耗自身资源大幅强化
        /// </summary>
        Sacrifice = 32,
    }

} 

