
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EBehaviorKind
    {
        /// <summary>
        /// 固守
        /// </summary>
        Stationary = 0,
        /// <summary>
        /// 漂浮
        /// </summary>
        Drift = 1,
        /// <summary>
        /// 追猎
        /// </summary>
        Chase = 2,
        /// <summary>
        /// 巡逻
        /// </summary>
        Patrol = 3,
        /// <summary>
        /// 冲撞
        /// </summary>
        Charge = 4,
        /// <summary>
        /// 远程
        /// </summary>
        Ranged = 5,
        /// <summary>
        /// 群体
        /// </summary>
        Swarm = 6,
        /// <summary>
        /// 逃逸
        /// </summary>
        Flee = 7,
        /// <summary>
        /// 环绕
        /// </summary>
        Orbit = 8,
        /// <summary>
        /// 附着
        /// </summary>
        Latch = 9,
    }

} 

