
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 生态事件
/// </summary>
public sealed partial class EcoEvent : Luban.BeanBase
{
    public EcoEvent(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Duration = _buf.ReadFloat();
        PressureMul = _buf.ReadFloat();
        PlayerSpeedMul = _buf.ReadFloat();
        EnemySpeedMul = _buf.ReadFloat();
        DevourGainMul = _buf.ReadFloat();
        FavoredRoute = (cell.ERoute)_buf.ReadInt();
        RewardKind = (cell.EResourceKind)_buf.ReadInt();
        RewardAmount = _buf.ReadFloat();
        GrantsDraft = _buf.ReadBool();
        DraftKind = (cell.EDraftKind)_buf.ReadInt();
    }

    public static EcoEvent DeserializeEcoEvent(ByteBuf _buf)
    {
        return new cell.EcoEvent(_buf);
    }

    /// <summary>
    /// 事件id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 事件名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 持续(秒)
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 压力倍率
    /// </summary>
    public readonly float PressureMul;
    /// <summary>
    /// 玩家移速倍率
    /// </summary>
    public readonly float PlayerSpeedMul;
    /// <summary>
    /// 敌人移速倍率
    /// </summary>
    public readonly float EnemySpeedMul;
    /// <summary>
    /// 吞噬收益倍率
    /// </summary>
    public readonly float DevourGainMul;
    /// <summary>
    /// 偏向路线
    /// </summary>
    public readonly cell.ERoute FavoredRoute;
    /// <summary>
    /// 奖励资源
    /// </summary>
    public readonly cell.EResourceKind RewardKind;
    /// <summary>
    /// 奖励量
    /// </summary>
    public readonly float RewardAmount;
    /// <summary>
    /// 是否给一次选卡
    /// </summary>
    public readonly bool GrantsDraft;
    /// <summary>
    /// 选卡类型
    /// </summary>
    public readonly cell.EDraftKind DraftKind;
   
    public const int __ID__ = -5486411;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "duration:" + Duration + ","
        + "pressureMul:" + PressureMul + ","
        + "playerSpeedMul:" + PlayerSpeedMul + ","
        + "enemySpeedMul:" + EnemySpeedMul + ","
        + "devourGainMul:" + DevourGainMul + ","
        + "favoredRoute:" + FavoredRoute + ","
        + "rewardKind:" + RewardKind + ","
        + "rewardAmount:" + RewardAmount + ","
        + "grantsDraft:" + GrantsDraft + ","
        + "draftKind:" + DraftKind + ","
        + "}";
    }
}
}

