
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EContentKind
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 器官
        /// </summary>
        Organelle = 1,
        /// <summary>
        /// 基因
        /// </summary>
        Gene = 2,
    }

} 

