
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EDraftKind
    {
        /// <summary>
        /// 3 选 1
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 4 选 1
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 3 选 1 带代价
        /// </summary>
        Corrupt = 2,
        /// <summary>
        /// 2 选 1 保底
        /// </summary>
        Repair = 3,
        /// <summary>
        /// 3 选 1 遗产卡
        /// </summary>
        Legacy = 4,
    }

} 

