
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EEffectShape
    {
        /// <summary>
        /// 自身
        /// </summary>
        Self = 0,
        /// <summary>
        /// 圆形
        /// </summary>
        Circle = 1,
        /// <summary>
        /// 锥形
        /// </summary>
        Cone = 2,
        /// <summary>
        /// 直线
        /// </summary>
        Line = 3,
        /// <summary>
        /// 单目标
        /// </summary>
        Target = 4,
        /// <summary>
        /// 指定点
        /// </summary>
        Point = 5,
    }

} 

