
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EEffectKind
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 伤害
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 状态
        /// </summary>
        Status = 2,
        /// <summary>
        /// 生成单位
        /// </summary>
        Spawn = 3,
        /// <summary>
        /// 属性修正
        /// </summary>
        Stat = 4,
        /// <summary>
        /// 资源变化
        /// </summary>
        Resource = 5,
        /// <summary>
        /// 位移
        /// </summary>
        Dash = 6,
        /// <summary>
        /// 投射物
        /// </summary>
        Projectile = 7,
        /// <summary>
        /// 持续区域
        /// </summary>
        Area = 8,
        /// <summary>
        /// 改规则
        /// </summary>
        Rule = 9,
    }

} 

