
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EFaction
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 玩家附属体
        /// </summary>
        PlayerMinion = 2,
        /// <summary>
        /// 敌对
        /// </summary>
        Hostile = 3,
        /// <summary>
        /// 中立
        /// </summary>
        Neutral = 4,
        /// <summary>
        /// 拾取物
        /// </summary>
        Pickup = 5,
    }

} 

