
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EModifierOp
    {
        /// <summary>
        /// 加值
        /// </summary>
        Flat = 0,
        /// <summary>
        /// 同类相加
        /// </summary>
        PctAdd = 1,
        /// <summary>
        /// 独立相乘
        /// </summary>
        PctMul = 2,
    }

} 

