
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EResourceKind
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 生命值
        /// </summary>
        Health = 1,
        /// <summary>
        /// 营养质
        /// </summary>
        Nutrient = 2,
        /// <summary>
        /// 突变质
        /// </summary>
        Mutagen = 3,
        /// <summary>
        /// 进化能
        /// </summary>
        EvoEnergy = 4,
        /// <summary>
        /// 污染度
        /// </summary>
        Pollution = 5,
        /// <summary>
        /// 体积
        /// </summary>
        Volume = 6,
        /// <summary>
        /// 体力
        /// </summary>
        Stamina = 7,
    }

} 

