
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum ERoute
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 吞噬扩张
        /// </summary>
        Devour = 1,
        /// <summary>
        /// 机动猎食
        /// </summary>
        Agile = 2,
        /// <summary>
        /// 电化统治
        /// </summary>
        Electric = 3,
        /// <summary>
        /// 孢子繁殖
        /// </summary>
        Spore = 4,
        /// <summary>
        /// 菌毯筑巢
        /// </summary>
        Nest = 5,
        /// <summary>
        /// 异化污染
        /// </summary>
        Corrupt = 6,
        /// <summary>
        /// 跨路线联动
        /// </summary>
        Hybrid = 7,
    }

} 

