
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum ERuleFlag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 尸体可食
        /// </summary>
        CorpseEdible = 1,
        /// <summary>
        /// 吞噬失败致腐蚀
        /// </summary>
        FailedDevourCorrodes = 2,
        /// <summary>
        /// 连吃不清空
        /// </summary>
        ComboNeverResets = 3,
        /// <summary>
        /// 冲刺穿体
        /// </summary>
        DashPierces = 4,
        /// <summary>
        /// 冲刺留电流
        /// </summary>
        DashLeavesCurrent = 5,
        /// <summary>
        /// 尸体导电
        /// </summary>
        CorpseConducts = 6,
        /// <summary>
        /// 菌毯增益吞噬
        /// </summary>
        MyceliumBoostsDevour = 7,
        /// <summary>
        /// 濒死脱战
        /// </summary>
        AutoEscapeOnLowHp = 8,
        /// <summary>
        /// 污染满转霸主
        /// </summary>
        PollutionBecomesOverlord = 9,
        /// <summary>
        /// 附属体集火标记
        /// </summary>
        MinionsFocusMarked = 10,
        /// <summary>
        /// 大目标裂解
        /// </summary>
        LargeTargetsSplit = 11,
        /// <summary>
        /// 处决致恐惧
        /// </summary>
        ExecuteCausesFear = 12,
    }

} 

