
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EStatus
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 导电
        /// </summary>
        Conductive = 1,
        /// <summary>
        /// 破体
        /// </summary>
        Breached = 2,
        /// <summary>
        /// 标记
        /// </summary>
        Marked = 4,
        /// <summary>
        /// 减速
        /// </summary>
        Slowed = 8,
        /// <summary>
        /// 麻痹
        /// </summary>
        Stunned = 16,
        /// <summary>
        /// 腐蚀
        /// </summary>
        Corroded = 32,
        /// <summary>
        /// 恐惧
        /// </summary>
        Feared = 64,
        /// <summary>
        /// 寄生
        /// </summary>
        Parasited = 128,
        /// <summary>
        /// 无敌
        /// </summary>
        Invulnerable = 256,
        /// <summary>
        /// 硬化
        /// </summary>
        Hardened = 512,
        /// <summary>
        /// 晶化
        /// </summary>
        Crystallized = 1024,
        /// <summary>
        /// 感染
        /// </summary>
        Infected = 2048,
        /// <summary>
        /// 易伤
        /// </summary>
        Vulnerable = 4096,
        /// <summary>
        /// 燃烧
        /// </summary>
        Burning = 8192,
        /// <summary>
        /// 污染
        /// </summary>
        Polluted = 16384,
        /// <summary>
        /// 被拉拽
        /// </summary>
        Pulled = 32768,
        /// <summary>
        /// 不可吞噬
        /// </summary>
        Unedible = 65536,
        /// <summary>
        /// 精英
        /// </summary>
        Elite = 131072,
        /// <summary>
        /// 首领
        /// </summary>
        Boss = 262144,
        /// <summary>
        /// 菌毯上
        /// </summary>
        OnMycelium = 524288,
    }

} 

