
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum EStatId
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大生命
        /// </summary>
        MaxHealth = 1,
        /// <summary>
        /// 移速
        /// </summary>
        MoveSpeed = 2,
        /// <summary>
        /// 体积
        /// </summary>
        Volume = 3,
        /// <summary>
        /// 近战伤害
        /// </summary>
        MeleeDamage = 4,
        /// <summary>
        /// 吞噬门槛
        /// </summary>
        DevourRatio = 5,
        /// <summary>
        /// 吞噬收益
        /// </summary>
        DevourGain = 6,
        /// <summary>
        /// 体力上限
        /// </summary>
        StaminaMax = 7,
        /// <summary>
        /// 体力回复
        /// </summary>
        StaminaRegen = 8,
        /// <summary>
        /// 冲刺消耗
        /// </summary>
        DashCost = 9,
        /// <summary>
        /// 冲刺距离
        /// </summary>
        DashDistance = 10,
        /// <summary>
        /// 冲刺无敌时长
        /// </summary>
        DashInvulnTime = 11,
        /// <summary>
        /// 冷却缩减
        /// </summary>
        CooldownReduction = 12,
        /// <summary>
        /// 范围倍率
        /// </summary>
        AreaScale = 13,
        /// <summary>
        /// 技能强度
        /// </summary>
        AbilityPower = 14,
        /// <summary>
        /// 电系强度
        /// </summary>
        ElectricPower = 15,
        /// <summary>
        /// 连锁加成
        /// </summary>
        ChainBonus = 16,
        /// <summary>
        /// 附属体上限
        /// </summary>
        MinionCap = 17,
        /// <summary>
        /// 附属体强度
        /// </summary>
        MinionPower = 18,
        /// <summary>
        /// 生命回复
        /// </summary>
        HealthRegen = 19,
        /// <summary>
        /// 击杀回复
        /// </summary>
        KillHeal = 20,
        /// <summary>
        /// 受伤倍率
        /// </summary>
        DamageTaken = 21,
        /// <summary>
        /// 仇恨倍率
        /// </summary>
        AggroScale = 22,
        /// <summary>
        /// 拾取半径
        /// </summary>
        PickupRadius = 23,
        /// <summary>
        /// 进化能收益
        /// </summary>
        EvoGain = 24,
        /// <summary>
        /// 营养质收益
        /// </summary>
        NutrientGain = 25,
        /// <summary>
        /// 技能槽位
        /// </summary>
        AbilitySlots = 26,
        /// <summary>
        /// 污染度上限
        /// </summary>
        PollutionCap = 27,
        /// <summary>
        /// 菌毯范围
        /// </summary>
        MyceliumScale = 28,
        /// <summary>
        /// 投射物数量
        /// </summary>
        ProjectileCount = 29,
        /// <summary>
        /// 状态时长
        /// </summary>
        StatusDuration = 30,
    }

} 

