
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum ETargetMode
    {
        /// <summary>
        /// 自身
        /// </summary>
        Self = 0,
        /// <summary>
        /// 移动方向
        /// </summary>
        MoveDirection = 1,
        /// <summary>
        /// 鼠标方向
        /// </summary>
        Cursor = 2,
        /// <summary>
        /// 最近敌人
        /// </summary>
        NearestEnemy = 3,
        /// <summary>
        /// 已标记敌人
        /// </summary>
        MarkedEnemy = 4,
    }

} 

