
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.cell
{ 
    public enum ETrigger
    {
        /// <summary>
        /// 获得即生效
        /// </summary>
        Passive = 0,
        /// <summary>
        /// 吞噬时
        /// </summary>
        OnDevour = 1,
        /// <summary>
        /// 击杀时
        /// </summary>
        OnKill = 2,
        /// <summary>
        /// 命中时
        /// </summary>
        OnHit = 3,
        /// <summary>
        /// 受伤时
        /// </summary>
        OnHurt = 4,
        /// <summary>
        /// 冲刺时
        /// </summary>
        OnDash = 5,
        /// <summary>
        /// 施放技能时
        /// </summary>
        OnAbilityCast = 6,
        /// <summary>
        /// 升级时
        /// </summary>
        OnLevelUp = 7,
        /// <summary>
        /// 低血时
        /// </summary>
        OnLowHealth = 8,
        /// <summary>
        /// 时期开始时
        /// </summary>
        OnPhaseStart = 9,
        /// <summary>
        /// 周期性
        /// </summary>
        OnTick = 10,
        /// <summary>
        /// 体积变化时
        /// </summary>
        OnVolumeChanged = 11,
        /// <summary>
        /// 生态事件时
        /// </summary>
        OnEcoEvent = 12,
    }

} 

