
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 基因模块参数
/// </summary>
public sealed partial class GeneModuleParams : Luban.BeanBase
{
    public GeneModuleParams(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        HomingStrength = _buf.ReadFloat();
        SpreadAngle = _buf.ReadFloat();
        ScattererCount = _buf.ReadInt();
        BounceCount = _buf.ReadInt();
        PierceCount = _buf.ReadInt();
        GrowScale = _buf.ReadFloat();
        OrbitSpeed = _buf.ReadFloat();
        OrbitRadius = _buf.ReadFloat();
        EchoDelay = _buf.ReadFloat();
        TrailDamage = _buf.ReadFloat();
        LingerSeconds = _buf.ReadFloat();
        ChainCount = _buf.ReadInt();
        CapacitorRatio = _buf.ReadFloat();
        SplitCount = _buf.ReadInt();
        PullStrength = _buf.ReadFloat();
        BallisticsSpeed = _buf.ReadFloat();
        BallisticsLifetime = _buf.ReadFloat();
        BallisticsGravity = _buf.ReadFloat();
        TickRate = _buf.ReadFloat();
        RippleRate = _buf.ReadFloat();
        RhythmRate = _buf.ReadFloat();
        CatalystAmplifier = _buf.ReadFloat();
        WeaveRadius = _buf.ReadFloat();
    }

    public static GeneModuleParams DeserializeGeneModuleParams(ByteBuf _buf)
    {
        return new cell.GeneModuleParams(_buf);
    }

    /// <summary>
    /// 基因id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 追踪强度(HomingModule.strength)
    /// </summary>
    public readonly float HomingStrength;
    /// <summary>
    /// 扇散角度(SpreadModule.angleDegrees)
    /// </summary>
    public readonly float SpreadAngle;
    /// <summary>
    /// 散射基础数(Scatterer.baseCount)
    /// </summary>
    public readonly int ScattererCount;
    /// <summary>
    /// 弹跳次数(BounceModule.count)
    /// </summary>
    public readonly int BounceCount;
    /// <summary>
    /// 穿透数(PierceModule.count)
    /// </summary>
    public readonly int PierceCount;
    /// <summary>
    /// 生长倍率(Grow.baseGrowRate)
    /// </summary>
    public readonly float GrowScale;
    /// <summary>
    /// 环绕角速度(OrbitSpin.angularSpeed)
    /// </summary>
    public readonly float OrbitSpeed;
    /// <summary>
    /// 环绕半径(OrbitRadiusModule.radius)
    /// </summary>
    public readonly float OrbitRadius;
    /// <summary>
    /// 残影延迟秒(EchoModule.delaySeconds)
    /// </summary>
    public readonly float EchoDelay;
    /// <summary>
    /// 拖尾伤害(TrailModule.damage)
    /// </summary>
    public readonly float TrailDamage;
    /// <summary>
    /// 留坑持续秒数(LingerModule.seconds)
    /// </summary>
    public readonly float LingerSeconds;
    /// <summary>
    /// 连锁目标数(ChainModule.targetCount)
    /// </summary>
    public readonly int ChainCount;
    /// <summary>
    /// 蓄能倍率(Capacitor.chargeMult)
    /// </summary>
    public readonly float CapacitorRatio;
    /// <summary>
    /// 分裂数(SplitModule.count)
    /// </summary>
    public readonly int SplitCount;
    /// <summary>
    /// 牵引强度(PullModule.strength)
    /// </summary>
    public readonly float PullStrength;
    /// <summary>
    /// 弹速(BallisticsModule.speed)
    /// </summary>
    public readonly float BallisticsSpeed;
    /// <summary>
    /// 弹体生存时间秒(BallisticsModule.lifetime)
    /// </summary>
    public readonly float BallisticsLifetime;
    /// <summary>
    /// 弹道重力(BallisticsModule.gravity)
    /// </summary>
    public readonly float BallisticsGravity;
    /// <summary>
    /// 每秒跳算次数(TickModule.ratePerSecond)
    /// </summary>
    public readonly float TickRate;
    /// <summary>
    /// 扩散频率(RippleModule.ratePerSecond)
    /// </summary>
    public readonly float RippleRate;
    /// <summary>
    /// 节律频率(RhythmModule.ratePerSecond)
    /// </summary>
    public readonly float RhythmRate;
    /// <summary>
    /// 催化放大(CatalystModule.amplifier)
    /// </summary>
    public readonly float CatalystAmplifier;
    /// <summary>
    /// 编织连接半径(WeaveModule.linkRadius)
    /// </summary>
    public readonly float WeaveRadius;
   
    public const int __ID__ = -345370125;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "homingStrength:" + HomingStrength + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "scattererCount:" + ScattererCount + ","
        + "bounceCount:" + BounceCount + ","
        + "pierceCount:" + PierceCount + ","
        + "growScale:" + GrowScale + ","
        + "orbitSpeed:" + OrbitSpeed + ","
        + "orbitRadius:" + OrbitRadius + ","
        + "echoDelay:" + EchoDelay + ","
        + "trailDamage:" + TrailDamage + ","
        + "lingerSeconds:" + LingerSeconds + ","
        + "chainCount:" + ChainCount + ","
        + "capacitorRatio:" + CapacitorRatio + ","
        + "splitCount:" + SplitCount + ","
        + "pullStrength:" + PullStrength + ","
        + "ballisticsSpeed:" + BallisticsSpeed + ","
        + "ballisticsLifetime:" + BallisticsLifetime + ","
        + "ballisticsGravity:" + BallisticsGravity + ","
        + "tickRate:" + TickRate + ","
        + "rippleRate:" + RippleRate + ","
        + "rhythmRate:" + RhythmRate + ","
        + "catalystAmplifier:" + CatalystAmplifier + ","
        + "weaveRadius:" + WeaveRadius + ","
        + "}";
    }
}
}

