
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 升级曲线
/// </summary>
public sealed partial class LevelCurve : Luban.BeanBase
{
    public LevelCurve(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Threshold = _buf.ReadFloat();
    }

    public static LevelCurve DeserializeLevelCurve(ByteBuf _buf)
    {
        return new cell.LevelCurve(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所需进化能
    /// </summary>
    public readonly float Threshold;
   
    public const int __ID__ = -45406217;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "threshold:" + Threshold + ","
        + "}";
    }
}
}

