
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 器官模块参数
/// </summary>
public sealed partial class OrganModuleParams : Luban.BeanBase
{
    public OrganModuleParams(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        BallisticsSpeed = _buf.ReadFloat();
        BallisticsLifetime = _buf.ReadFloat();
        SpreadAngle = _buf.ReadFloat();
        ReflectDamage = _buf.ReadFloat();
        TickRate = _buf.ReadFloat();
        LingerSeconds = _buf.ReadFloat();
        AuraRadius = _buf.ReadFloat();
        OrbitSpeed = _buf.ReadFloat();
        ScattererCount = _buf.ReadInt();
        KnockbackForce = _buf.ReadFloat();
        PierceCount = _buf.ReadInt();
        GrowScale = _buf.ReadFloat();
        SummonCount = _buf.ReadInt();
    }

    public static OrganModuleParams DeserializeOrganModuleParams(ByteBuf _buf)
    {
        return new cell.OrganModuleParams(_buf);
    }

    /// <summary>
    /// 器官id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 弹速(BallisticsModule.speed)
    /// </summary>
    public readonly float BallisticsSpeed;
    /// <summary>
    /// 弹体生存时间秒(BallisticsModule.lifetime)
    /// </summary>
    public readonly float BallisticsLifetime;
    /// <summary>
    /// 扇散角度(SpreadModule)
    /// </summary>
    public readonly float SpreadAngle;
    /// <summary>
    /// 反伤值(Thorns)
    /// </summary>
    public readonly float ReflectDamage;
    /// <summary>
    /// 每秒跳伤次数(TickModule)
    /// </summary>
    public readonly float TickRate;
    /// <summary>
    /// 留坑持续秒数(LingerModule)
    /// </summary>
    public readonly float LingerSeconds;
    /// <summary>
    /// 光环半径(AuraModule)
    /// </summary>
    public readonly float AuraRadius;
    /// <summary>
    /// 环绕角速度(OrbitSpin)
    /// </summary>
    public readonly float OrbitSpeed;
    /// <summary>
    /// 散射基础数(Scatterer)
    /// </summary>
    public readonly int ScattererCount;
    /// <summary>
    /// 击退力(KnockbackModule)
    /// </summary>
    public readonly float KnockbackForce;
    /// <summary>
    /// 穿透数(PierceModule)
    /// </summary>
    public readonly int PierceCount;
    /// <summary>
    /// 生长倍率(Grow)
    /// </summary>
    public readonly float GrowScale;
    /// <summary>
    /// 召唤数量(SummonModule.count)
    /// </summary>
    public readonly int SummonCount;
   
    public const int __ID__ = -1411385833;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ballisticsSpeed:" + BallisticsSpeed + ","
        + "ballisticsLifetime:" + BallisticsLifetime + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "reflectDamage:" + ReflectDamage + ","
        + "tickRate:" + TickRate + ","
        + "lingerSeconds:" + LingerSeconds + ","
        + "auraRadius:" + AuraRadius + ","
        + "orbitSpeed:" + OrbitSpeed + ","
        + "scattererCount:" + ScattererCount + ","
        + "knockbackForce:" + KnockbackForce + ","
        + "pierceCount:" + PierceCount + ","
        + "growScale:" + GrowScale + ","
        + "summonCount:" + SummonCount + ","
        + "}";
    }
}
}

