
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 压力曲线
/// </summary>
public sealed partial class PressureCurve : Luban.BeanBase
{
    public PressureCurve(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        FloorMul = _buf.ReadFloat();
        BaseMul = _buf.ReadFloat();
    }

    public static PressureCurve DeserializePressureCurve(ByteBuf _buf)
    {
        return new cell.PressureCurve(_buf);
    }

    /// <summary>
    /// 本局分钟数
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 下限倍率(不受玩家强度影响)
    /// </summary>
    public readonly float FloorMul;
    /// <summary>
    /// 基数倍率
    /// </summary>
    public readonly float BaseMul;
   
    public const int __ID__ = 1142423038;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "floorMul:" + FloorMul + ","
        + "baseMul:" + BaseMul + ","
        + "}";
    }
}
}

