
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 状态效果
/// </summary>
public sealed partial class StatusEffect : Luban.BeanBase
{
    public StatusEffect(ByteBuf _buf) 
    {
        Id = (cell.EStatus)_buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        DefaultDuration = _buf.ReadFloat();
        IsDebuff = _buf.ReadBool();
    }

    public static StatusEffect DeserializeStatusEffect(ByteBuf _buf)
    {
        return new cell.StatusEffect(_buf);
    }

    /// <summary>
    /// 状态位
    /// </summary>
    public readonly cell.EStatus Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 默认时长(秒),0=永久
    /// </summary>
    public readonly float DefaultDuration;
    /// <summary>
    /// 是否负面
    /// </summary>
    public readonly bool IsDebuff;
   
    public const int __ID__ = -1411646129;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "defaultDuration:" + DefaultDuration + ","
        + "isDebuff:" + IsDebuff + ","
        + "}";
    }
}
}

