
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 结构器官常驻被动
/// </summary>
public sealed partial class StructuralEffectParams : Luban.BeanBase
{
    public StructuralEffectParams(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        DamageTakenPct = _buf.ReadFloat();
        MoveSpeedPct = _buf.ReadFloat();
        MaxHealthFlat = _buf.ReadFloat();
        HealthRegenFlat = _buf.ReadFloat();
        PickupRadiusPct = _buf.ReadFloat();
        NutrientGainPct = _buf.ReadFloat();
        AggroScalePct = _buf.ReadFloat();
        StaminaMaxFlat = _buf.ReadFloat();
        StaminaRegenPct = _buf.ReadFloat();
        ShieldMaxFlat = _buf.ReadFloat();
        ShieldRegenFlat = _buf.ReadFloat();
    }

    public static StructuralEffectParams DeserializeStructuralEffectParams(ByteBuf _buf)
    {
        return new cell.StructuralEffectParams(_buf);
    }

    /// <summary>
    /// 结构器官id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 受伤倍率(StatId.DamageTaken,PctAdd)
    /// </summary>
    public readonly float DamageTakenPct;
    /// <summary>
    /// 移速(StatId.MoveSpeed,PctAdd)
    /// </summary>
    public readonly float MoveSpeedPct;
    /// <summary>
    /// 生命上限(StatId.MaxHealth,Flat)
    /// </summary>
    public readonly float MaxHealthFlat;
    /// <summary>
    /// 生命回复(StatId.HealthRegen,Flat)
    /// </summary>
    public readonly float HealthRegenFlat;
    /// <summary>
    /// 拾取半径(StatId.PickupRadius,PctAdd)
    /// </summary>
    public readonly float PickupRadiusPct;
    /// <summary>
    /// 营养质获取(StatId.NutrientGain,PctAdd)
    /// </summary>
    public readonly float NutrientGainPct;
    /// <summary>
    /// 敌人仇恨(StatId.AggroScale,PctAdd)
    /// </summary>
    public readonly float AggroScalePct;
    /// <summary>
    /// 耐力上限(StatId.StaminaMax,Flat)
    /// </summary>
    public readonly float StaminaMaxFlat;
    /// <summary>
    /// 耐力回复(StatId.StaminaRegen,PctAdd)
    /// </summary>
    public readonly float StaminaRegenPct;
    /// <summary>
    /// 屏障上限(StatId.ShieldMax,Flat)
    /// </summary>
    public readonly float ShieldMaxFlat;
    /// <summary>
    /// 屏障回复(StatId.ShieldRegen,Flat)
    /// </summary>
    public readonly float ShieldRegenFlat;
   
    public const int __ID__ = -1804460512;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damageTakenPct:" + DamageTakenPct + ","
        + "moveSpeedPct:" + MoveSpeedPct + ","
        + "maxHealthFlat:" + MaxHealthFlat + ","
        + "healthRegenFlat:" + HealthRegenFlat + ","
        + "pickupRadiusPct:" + PickupRadiusPct + ","
        + "nutrientGainPct:" + NutrientGainPct + ","
        + "aggroScalePct:" + AggroScalePct + ","
        + "staminaMaxFlat:" + StaminaMaxFlat + ","
        + "staminaRegenPct:" + StaminaRegenPct + ","
        + "shieldMaxFlat:" + ShieldMaxFlat + ","
        + "shieldRegenFlat:" + ShieldRegenFlat + ","
        + "}";
    }
}
}

