
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 结构器官触发钩子
/// </summary>
public sealed partial class StructuralTriggerHookParams : Luban.BeanBase
{
    public StructuralTriggerHookParams(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Probability = _buf.ReadFloat();
        ThornsRatio = _buf.ReadFloat();
        AbsorbRatio = _buf.ReadFloat();
        LingerRadius = _buf.ReadFloat();
        LingerSeconds = _buf.ReadFloat();
        LowHealthThreshold = _buf.ReadFloat();
        Cooldown = _buf.ReadFloat();
        TickRate = _buf.ReadFloat();
        MoveDistanceThreshold = _buf.ReadFloat();
        KillHealAmount = _buf.ReadFloat();
    }

    public static StructuralTriggerHookParams DeserializeStructuralTriggerHookParams(ByteBuf _buf)
    {
        return new cell.StructuralTriggerHookParams(_buf);
    }

    /// <summary>
    /// 结构器官id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 触发概率(TriggerHookSpec.Probability)
    /// </summary>
    public readonly float Probability;
    /// <summary>
    /// 反伤比例(ThornsRatio)
    /// </summary>
    public readonly float ThornsRatio;
    /// <summary>
    /// 转分摊比例(AbsorbRatio)
    /// </summary>
    public readonly float AbsorbRatio;
    /// <summary>
    /// 世界残留半径(LingerRadius)
    /// </summary>
    public readonly float LingerRadius;
    /// <summary>
    /// 世界残留秒数(LingerSeconds)
    /// </summary>
    public readonly float LingerSeconds;
    /// <summary>
    /// 低血量触发线(LowHealthThreshold)
    /// </summary>
    public readonly float LowHealthThreshold;
    /// <summary>
    /// 冷却秒数(Cooldown)
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 周期脉冲秒数(TickRate)
    /// </summary>
    public readonly float TickRate;
    /// <summary>
    /// 累计位移阈值(MoveDistanceThreshold)
    /// </summary>
    public readonly float MoveDistanceThreshold;
    /// <summary>
    /// 击杀回血量(KillHealAmount)
    /// </summary>
    public readonly float KillHealAmount;
   
    public const int __ID__ = 1816416856;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "probability:" + Probability + ","
        + "thornsRatio:" + ThornsRatio + ","
        + "absorbRatio:" + AbsorbRatio + ","
        + "lingerRadius:" + LingerRadius + ","
        + "lingerSeconds:" + LingerSeconds + ","
        + "lowHealthThreshold:" + LowHealthThreshold + ","
        + "cooldown:" + Cooldown + ","
        + "tickRate:" + TickRate + ","
        + "moveDistanceThreshold:" + MoveDistanceThreshold + ","
        + "killHealAmount:" + KillHealAmount + ","
        + "}";
    }
}
}

