
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 词缀
/// </summary>
public partial class TbAffix
{
    private readonly System.Collections.Generic.Dictionary<cell.EAffix, cell.Affix> _dataMap;
    private readonly System.Collections.Generic.List<cell.Affix> _dataList;
    
    public TbAffix(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<cell.EAffix, cell.Affix>(n);
        _dataList = new System.Collections.Generic.List<cell.Affix>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.Affix _v;
            _v = global::GameConfig.cell.Affix.DeserializeAffix(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<cell.EAffix, cell.Affix> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.Affix> DataList => _dataList;

    public cell.Affix GetOrDefault(cell.EAffix key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.Affix Get(cell.EAffix key) => _dataMap[key];
    public cell.Affix this[cell.EAffix key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

