
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 行为原型
/// </summary>
public partial class TbBehaviorArchetype
{
    private readonly System.Collections.Generic.Dictionary<int, cell.BehaviorArchetype> _dataMap;
    private readonly System.Collections.Generic.List<cell.BehaviorArchetype> _dataList;
    
    public TbBehaviorArchetype(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.BehaviorArchetype>(n);
        _dataList = new System.Collections.Generic.List<cell.BehaviorArchetype>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.BehaviorArchetype _v;
            _v = global::GameConfig.cell.BehaviorArchetype.DeserializeBehaviorArchetype(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.BehaviorArchetype> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.BehaviorArchetype> DataList => _dataList;

    public cell.BehaviorArchetype GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.BehaviorArchetype Get(int key) => _dataMap[key];
    public cell.BehaviorArchetype this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

