
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 卡牌效果
/// </summary>
public partial class TbCardEffect
{
    private readonly System.Collections.Generic.Dictionary<int, cell.CardEffect> _dataMap;
    private readonly System.Collections.Generic.List<cell.CardEffect> _dataList;
    
    public TbCardEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.CardEffect>(n);
        _dataList = new System.Collections.Generic.List<cell.CardEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.CardEffect _v;
            _v = global::GameConfig.cell.CardEffect.DeserializeCardEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Uid, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.CardEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.CardEffect> DataList => _dataList;

    public cell.CardEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.CardEffect Get(int key) => _dataMap[key];
    public cell.CardEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

