
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 敌人配置
/// </summary>
public partial class TbCellEnemy
{
    private readonly System.Collections.Generic.Dictionary<int, cell.CellEnemy> _dataMap;
    private readonly System.Collections.Generic.List<cell.CellEnemy> _dataList;
    
    public TbCellEnemy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.CellEnemy>(n);
        _dataList = new System.Collections.Generic.List<cell.CellEnemy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.CellEnemy _v;
            _v = global::GameConfig.cell.CellEnemy.DeserializeCellEnemy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.CellEnemy> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.CellEnemy> DataList => _dataList;

    public cell.CellEnemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.CellEnemy Get(int key) => _dataMap[key];
    public cell.CellEnemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

