
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 基因模块参数
/// </summary>
public partial class TbGeneModuleParams
{
    private readonly System.Collections.Generic.Dictionary<string, cell.GeneModuleParams> _dataMap;
    private readonly System.Collections.Generic.List<cell.GeneModuleParams> _dataList;
    
    public TbGeneModuleParams(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cell.GeneModuleParams>(n);
        _dataList = new System.Collections.Generic.List<cell.GeneModuleParams>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.GeneModuleParams _v;
            _v = global::GameConfig.cell.GeneModuleParams.DeserializeGeneModuleParams(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cell.GeneModuleParams> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.GeneModuleParams> DataList => _dataList;

    public cell.GeneModuleParams GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.GeneModuleParams Get(string key) => _dataMap[key];
    public cell.GeneModuleParams this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

