
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 升级曲线
/// </summary>
public partial class TbLevelCurve
{
    private readonly System.Collections.Generic.Dictionary<int, cell.LevelCurve> _dataMap;
    private readonly System.Collections.Generic.List<cell.LevelCurve> _dataList;
    
    public TbLevelCurve(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.LevelCurve>(n);
        _dataList = new System.Collections.Generic.List<cell.LevelCurve>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.LevelCurve _v;
            _v = global::GameConfig.cell.LevelCurve.DeserializeLevelCurve(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.LevelCurve> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.LevelCurve> DataList => _dataList;

    public cell.LevelCurve GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.LevelCurve Get(int key) => _dataMap[key];
    public cell.LevelCurve this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

