
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 器官模块参数
/// </summary>
public partial class TbOrganModuleParams
{
    private readonly System.Collections.Generic.Dictionary<string, cell.OrganModuleParams> _dataMap;
    private readonly System.Collections.Generic.List<cell.OrganModuleParams> _dataList;
    
    public TbOrganModuleParams(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cell.OrganModuleParams>(n);
        _dataList = new System.Collections.Generic.List<cell.OrganModuleParams>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.OrganModuleParams _v;
            _v = global::GameConfig.cell.OrganModuleParams.DeserializeOrganModuleParams(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cell.OrganModuleParams> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.OrganModuleParams> DataList => _dataList;

    public cell.OrganModuleParams GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.OrganModuleParams Get(string key) => _dataMap[key];
    public cell.OrganModuleParams this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

