
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 生态时期
/// </summary>
public partial class TbPhase
{
    private readonly System.Collections.Generic.Dictionary<int, cell.Phase> _dataMap;
    private readonly System.Collections.Generic.List<cell.Phase> _dataList;
    
    public TbPhase(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.Phase>(n);
        _dataList = new System.Collections.Generic.List<cell.Phase>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.Phase _v;
            _v = global::GameConfig.cell.Phase.DeserializePhase(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.Phase> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.Phase> DataList => _dataList;

    public cell.Phase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.Phase Get(int key) => _dataMap[key];
    public cell.Phase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

