
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 压力曲线
/// </summary>
public partial class TbPressureCurve
{
    private readonly System.Collections.Generic.Dictionary<int, cell.PressureCurve> _dataMap;
    private readonly System.Collections.Generic.List<cell.PressureCurve> _dataList;
    
    public TbPressureCurve(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cell.PressureCurve>(n);
        _dataList = new System.Collections.Generic.List<cell.PressureCurve>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.PressureCurve _v;
            _v = global::GameConfig.cell.PressureCurve.DeserializePressureCurve(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cell.PressureCurve> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.PressureCurve> DataList => _dataList;

    public cell.PressureCurve GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.PressureCurve Get(int key) => _dataMap[key];
    public cell.PressureCurve this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

