
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 状态效果
/// </summary>
public partial class TbStatusEffect
{
    private readonly System.Collections.Generic.Dictionary<cell.EStatus, cell.StatusEffect> _dataMap;
    private readonly System.Collections.Generic.List<cell.StatusEffect> _dataList;
    
    public TbStatusEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<cell.EStatus, cell.StatusEffect>(n);
        _dataList = new System.Collections.Generic.List<cell.StatusEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.StatusEffect _v;
            _v = global::GameConfig.cell.StatusEffect.DeserializeStatusEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<cell.EStatus, cell.StatusEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.StatusEffect> DataList => _dataList;

    public cell.StatusEffect GetOrDefault(cell.EStatus key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.StatusEffect Get(cell.EStatus key) => _dataMap[key];
    public cell.StatusEffect this[cell.EStatus key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

