
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 结构器官常驻被动
/// </summary>
public partial class TbStructuralEffectParams
{
    private readonly System.Collections.Generic.Dictionary<string, cell.StructuralEffectParams> _dataMap;
    private readonly System.Collections.Generic.List<cell.StructuralEffectParams> _dataList;
    
    public TbStructuralEffectParams(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cell.StructuralEffectParams>(n);
        _dataList = new System.Collections.Generic.List<cell.StructuralEffectParams>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.StructuralEffectParams _v;
            _v = global::GameConfig.cell.StructuralEffectParams.DeserializeStructuralEffectParams(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cell.StructuralEffectParams> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.StructuralEffectParams> DataList => _dataList;

    public cell.StructuralEffectParams GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.StructuralEffectParams Get(string key) => _dataMap[key];
    public cell.StructuralEffectParams this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

