
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cell
{
/// <summary>
/// 结构器官触发钩子
/// </summary>
public partial class TbStructuralTriggerHookParams
{
    private readonly System.Collections.Generic.Dictionary<string, cell.StructuralTriggerHookParams> _dataMap;
    private readonly System.Collections.Generic.List<cell.StructuralTriggerHookParams> _dataList;
    
    public TbStructuralTriggerHookParams(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cell.StructuralTriggerHookParams>(n);
        _dataList = new System.Collections.Generic.List<cell.StructuralTriggerHookParams>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cell.StructuralTriggerHookParams _v;
            _v = global::GameConfig.cell.StructuralTriggerHookParams.DeserializeStructuralTriggerHookParams(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cell.StructuralTriggerHookParams> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cell.StructuralTriggerHookParams> DataList => _dataList;

    public cell.StructuralTriggerHookParams GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cell.StructuralTriggerHookParams Get(string key) => _dataMap[key];
    public cell.StructuralTriggerHookParams this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

